Repository VKCOM/VKUI, pull requests merged in 2022-07, with the labels that each got.

#2785 fix adding fallback values for css custom properties
  postcss.config.js
Labels: patch

#2796 fix(FixedLayout): add platform indent
  src/components/FixedLayout/FixedLayout.css
Labels: patch

#2809 fix(Epic): width warning 768px
  src/components/Epic/Epic.tsx
Labels: patch

#2821 feat(Avatar): add `object-fit: cover` for square images
  src/components/Avatar/Avatar.css
Labels: patch

#2819 fix(Button): remove transform
  src/components/Alert/__image_snapshots__/alert-android-light-1-snap.png
  src/components/Alert/__image_snapshots__/alert-vkcom-light-1-snap.png
  src/components/Button/Button.css
  src/components/Button/__image_snapshots__/button-android-light-1-snap.png
  src/components/Button/__image_snapshots__/button-ios-light-1-snap.png
  src/components/Button/__image_snapshots__/button-vkcom-light-1-snap.png
  src/components/ButtonGroup/__image_snapshots__/buttongroup-align-android-light-1-snap.png
  src/components/ButtonGroup/__image_snapshots__/buttongroup-align-ios-light-1-snap.png
  src/components/ButtonGroup/__image_snapshots__/buttongroup-align-vkcom-light-1-snap.png
  src/components/ButtonGroup/__image_snapshots__/buttongroup-android-light-1-snap.png
  src/components/ButtonGroup/__image_snapshots__/buttongroup-ios-light-1-snap.png
  src/components/ButtonGroup/__image_snapshots__/buttongroup-vkcom-light-1-snap.png
  src/components/Calendar/__image_snapshots__/calendar-android-light-1-snap.png
  src/components/Calendar/__image_snapshots__/calendar-ios-light-1-snap.png
  src/components/Calendar/__image_snapshots__/calendar-vkcom-light-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-light-w_2-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-mobile-ios-light-w_2-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-light-w_3-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-light-w_3-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-vkcom-light-1-snap.png
  src/components/Placeholder/__image_snapshots__/placeholder-android-light-1-snap.png
  src/components/Placeholder/__image_snapshots__/placeholder-ios-light-1-snap.png
  src/components/Placeholder/__image_snapshots__/placeholder-vkcom-light-1-snap.png
Labels: patch

#2832 fix(ConfigProvider): check `scheme === undefined`
  src/components/ConfigProvider/ConfigProvider.test.tsx
  src/helpers/getScheme.ts
  src/helpers/scheme.ts
Labels: patch

#2843 Add ability to disable portals in the app
  src/components/AppRoot/AppRoot.tsx
  src/components/AppRoot/AppRootContext.ts
  src/components/AppRoot/AppRootPortal.tsx
Labels: patch

#2851 fix(SegmentedControl): update tokens
  package.json
  src/components/SegmentedControl/SegmentedControl.css
  src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
  src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-light-1-snap.png
  src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-light-1-snap.png
  src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-light-1-snap.png
  yarn.lock
Labels: patch

#2857 fix-search-styles
  src/components/Search/Search.css
  src/components/Search/__image_snapshots__/search-android-light-1-snap.png
  src/components/Search/__image_snapshots__/search-ios-light-1-snap.png
  src/components/Search/__image_snapshots__/search-vkcom-light-1-snap.png
Labels: patch

#2867 build(deps): bump @vkontakte/vkui-tokens from 4.14.1 to 4.14.2
  package.json
  src/components/Search/__image_snapshots__/search-android-light-1-snap.png
  src/components/Search/__image_snapshots__/search-ios-light-1-snap.png
  yarn.lock
Labels: dependencies

#2874 Fix removing of vkui class in react 18
  src/components/AppRoot/AppRoot.tsx
Labels: patch

#2893 docs: remove ComponentType
  src/hoc/withAdaptivity.tsx
  src/hoc/withContext.tsx
  src/hoc/withPlatform.tsx
Labels: patch

#2900 fix(SplitCol): Заменить padding на margin
  src/components/SplitCol/SplitCol.css
Labels: type:bug, cmp:split-col, patch

#2875 fix ChipsSelect dropdown position when chips change
  src/components/ChipsSelect/ChipsSelect.tsx
  src/components/CustomSelect/CustomSelect.tsx
  src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
Labels: patch

#2907 fix(ScreenSpinner): Add token fallback
  src/components/ScreenSpinner/ScreenSpinner.css
Labels: patch

#2898 fix(FormField,Input,Select): use token for width/height; refactor docs
  src/components/Calendar/__image_snapshots__/calendar-android-light-1-snap.png
  src/components/Calendar/__image_snapshots__/calendar-ios-light-1-snap.png
  src/components/Calendar/__image_snapshots__/calendar-vkcom-light-1-snap.png
  src/components/CalendarRange/__image_snapshots__/calendarrange-android-light-1-snap.png
  src/components/CalendarRange/__image_snapshots__/calendarrange-ios-light-1-snap.png
  src/components/CalendarRange/__image_snapshots__/calendarrange-vkcom-light-1-snap.png
  src/components/ChipsInput/__image_snapshots__/chipsinput-android-light-1-snap.png
  src/components/ChipsInput/__image_snapshots__/chipsinput-ios-light-1-snap.png
  src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-light-1-snap.png
  src/components/CustomSelect/__image_snapshots__/customselect-android-light-1-snap.png
  src/components/CustomSelect/__image_snapshots__/customselect-ios-light-1-snap.png
  src/components/CustomSelect/__image_snapshots__/customselect-vkcom-light-1-snap.png
  src/components/DateInput/__image_snapshots__/dateinput-android-light-1-snap.png
  src/components/DateInput/__image_snapshots__/dateinput-ios-light-1-snap.png
  src/components/DateInput/__image_snapshots__/dateinput-vkcom-light-1-snap.png
  src/components/DateRangeInput/__image_snapshots__/daterangeinput-android-light-1-snap.png
  src/components/DateRangeInput/__image_snapshots__/daterangeinput-ios-light-1-snap.png
  src/components/DateRangeInput/__image_snapshots__/daterangeinput-vkcom-light-1-snap.png
  src/components/FormField/FormField.css
  src/components/FormField/FormField.tsx
  src/components/FormField/Readme.md
  src/components/IconButton/IconButton.css
  src/components/Input/Input.css
  src/components/Input/Input.tsx
  src/components/Input/Readme.md
  src/components/Input/__image_snapshots__/input-android-light-1-snap.png
  src/components/Input/__image_snapshots__/input-ios-light-1-snap.png
  src/components/Input/__image_snapshots__/input-vkcom-light-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-light-w_2-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-mobile-ios-light-w_2-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-light-w_3-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-light-w_3-1-snap.png
  src/components/ModalCard/__image_snapshots__/modalcard-vkcom-light-1-snap.png
  src/components/NativeSelect/__image_snapshots__/nativeselect-android-light-1-snap.png
  src/components/NativeSelect/__image_snapshots__/nativeselect-ios-light-1-snap.png
  src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-light-1-snap.png
  src/components/Select/Select.css
  src/components/SelectMimicry/SelectMimicry.tsx
  src/components/SelectMimicry/__image_snapshots__/selectmimicry-android-light-1-snap.png
  src/components/SelectMimicry/__image_snapshots__/selectmimicry-ios-light-1-snap.png
  src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-light-1-snap.png
  src/components/Textarea/Textarea.css
  src/components/Textarea/__image_snapshots__/textarea-android-light-1-snap.png
  src/components/Textarea/__image_snapshots__/textarea-fits-size-to-content-1-snap.png
  src/components/Textarea/__image_snapshots__/textarea-fits-size-to-content-2-snap.png
  src/components/Textarea/__image_snapshots__/textarea-ios-light-1-snap.png
  src/components/Textarea/__image_snapshots__/textarea-vkcom-light-1-snap.png
Labels: patch

#2859 fix: add displayName
  src/components/AppRoot/AppRoot.tsx
  src/components/Button/Button.tsx
  src/components/ChipsSelect/ChipsSelect.tsx
  src/components/HorizontalScroll/HorizontalScroll.tsx
  src/components/Input/Input.tsx
  src/components/ModalCardBase/ModalCardBase.tsx
  src/components/NativeSelect/NativeSelect.tsx
  src/components/Panel/Panel.tsx
  src/components/PanelHeader/PanelHeader.tsx
  src/components/Radio/Radio.tsx
  src/components/RangeSlider/UniversalSlider.tsx
  src/components/Select/Select.tsx
  src/components/SelectMimicry/SelectMimicry.tsx
  src/components/SimpleCell/SimpleCell.tsx
  src/components/Textarea/Textarea.tsx
Labels: patch
