Repository VKCOM/VKUI, pull requests merged in 2023-05, with the labels that each got.

#4964 fix(build): VKUI_PACKAGE_BUILD
  postcss.config.js
Labels: patch

#4950 fix(DateRangeInput): bad date mask
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
Labels: patch

#4839 refactor: rm global PanelHeaderContent__children
  packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.module.css
  packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.tsx
  packages/vkui/src/components/Typography/Headline/Headline.module.css
  packages/vkui/src/components/Typography/Text/Text.module.css
Labels: pr-needs-work

#4836 refactor(Textarea|Input): use Text component
  packages/vkui/src/components/Input/Input.module.css
  packages/vkui/src/components/Input/Input.tsx
  packages/vkui/src/components/Textarea/Textarea.module.css
  packages/vkui/src/components/Textarea/Textarea.tsx
Labels: pr-needs-work

#4904 test(unit): fix testRegex
  packages/vkui/jest.config.js
Labels: pr-needs-work

#4902 build(deps-dev): rm unused
  package.json
  yarn.lock
Labels: technical task

#4989 ci: add CODECOV_TOKEN
  .github/workflows/reusable_workflow_test.yml
  .github/workflows/reusable_workflow_test_a11y.yml
  .github/workflows/reusable_workflow_test_e2e.yml
Labels: technical task

#4997 ci: use VKCOM/gh-actions
  .github/actions/patch/.eslintrc.js
  .github/actions/patch/action.yml
  .github/actions/patch/package.json
  .github/actions/patch/src/main.ts
  .github/actions/patch/src/message.ts
  .github/actions/patch/tsconfig.json
  .github/actions/push-screenshots/.eslintrc.js
  .github/actions/push-screenshots/action.yml
  .github/actions/push-screenshots/package.json
  .github/actions/push-screenshots/src/main.ts
  .github/actions/push-screenshots/tsconfig.json
  .github/actions/reporter/.eslintrc.js
  .github/actions/reporter/action.yml
  .github/actions/reporter/package.json
  .github/actions/reporter/src/comment.ts
  .github/actions/reporter/src/jest.ts
  .github/actions/reporter/src/lint.ts
  .github/actions/reporter/src/main.ts
  .github/actions/reporter/src/playwrightReport.ts
  .github/actions/reporter/src/shared.ts
  .github/actions/reporter/tsconfig.json
  .github/actions/s3/.eslintrc.js
  .github/actions/s3/action.yml
  .github/actions/s3/package.json
  .github/actions/s3/src/main.ts
  .github/actions/s3/tsconfig.json
  .github/actions/stable-branch/.eslintrc.js
  .github/actions/stable-branch/action.yml
  .github/actions/stable-branch/package.json
  .github/actions/stable-branch/src/main.ts
  .github/actions/stable-branch/tsconfig.json
  .github/dependabot.yml
  .github/workflows/pr_close.yml
  .github/workflows/publish.yml
  .github/workflows/pull_request_packages.yml
  .github/workflows/update_screens.yml
  yarn.lock
Labels: technical task

#4976 tech(file-filters.yml): add postcss to package_vkui
  .github/file-filters.yml
Labels: technical task

#4986 build(deps): Bump @floating-ui/react-dom from 1.3.0 to 2.0.0
  packages/vkui/package.json
  packages/vkui/src/lib/floating/functions.test.ts
  packages/vkui/src/lib/floating/functions.ts
  yarn.lock
Labels: dependencies, technical task, javascript

#5016 docs(Link): fix Link story
  packages/vkui/src/components/Link/Link.stories.tsx
Labels: docs, a11y, patch, a11y:audit

#5020 docs(VisuallyHidden): show docs
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
Labels: docs, patch

#4979 fix(MiniInfoCell): add word-break
  packages/vkui/src/components/MiniInfoCell/MiniInfoCell.module.css
Labels: cmp:mini-info-cell, patch, pr-needs-work

#5077 tech: cleanup project configurations
  .github/dependabot.yml
  .github/file-filters.yml
  package.json
Labels: technical task

#5087 fix(PullToRefresh): исправляем моргание на iOS
  packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css
  packages/vkui/src/styles/constants.css
Labels: patch

#4199 fix(HorizontalCell): fix design review notes
  packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
  packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx
  packages/vkui/src/components/HorizontalCell/Readme.md
  packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-does-not-have-arrows-without-mouse-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-does-not-have-arrows-without-mouse-ios-webkit-light-1-snap.png
  packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-has-arrows-on-mouse-hover-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ImageBase/ImageBase.module.css
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/styles/constants.css
Labels: patch, no-stale

#4678 fix(ActionSheet, ActionSheetItem): fix design notes
  packages/vkui/src/components/ActionSheet/ActionSheet.e2e-playground.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.module.css
  packages/vkui/src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
Labels: pr-needs-work

#5090 tech(stylelint): fix atomic disable comments
  packages/vkui/src/components/ButtonGroup/ButtonGroup.module.css
  packages/vkui/src/components/FormField/FormField.module.css
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css
  packages/vkui/src/components/Link/Link.module.css
  packages/vkui/src/components/Tappable/Tappable.module.css
Labels: technical task

#5089 fix(FormLayoutGroup): rm `isolation` prop
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css
Labels: type:bug, cmp:form-layout-group, patch

#5088 fix(ModalRoot): always check resize
  packages/vkui/src/components/ModalPage/ModalPage.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/ModalRoot/types.ts
  packages/vkui/src/components/ModalRoot/useModalManager.tsx
Labels: patch

#4935 fix(a11y): Расставляем пробелы для скринридеров
  packages/vkui/src/components/Banner/Banner.module.css
  packages/vkui/src/components/Banner/Banner.tsx
  packages/vkui/src/components/InfoRow/InfoRow.tsx
  packages/vkui/src/components/TabsItem/TabsItem.tsx
  packages/vkui/src/components/Typography/Typography.module.css
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css
Labels: a11y, patch, pr-needs-work, a11y:audit

#4985 fix(Cell): stop propagation drag events
  packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx
  packages/vkui/src/components/Cell/useDraggable.tsx
Labels: patch, pr-needs-work

#5084 feat(Header): rm vkcom styles
  packages/vkui/src/components/Header/Header.module.css
  packages/vkui/src/components/Header/Header.tsx
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:header

#4649 feat: add ScrollArrow
  packages/vkui/src/components/BaseGallery/BaseGallery.module.css
  packages/vkui/src/components/BaseGallery/BaseGallery.tsx
  packages/vkui/src/components/BaseGallery/types.ts
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.module.css
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScrollArrow.module.css
  packages/vkui/src/components/HorizontalScroll/HorizontalScrollArrow.test.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScrollArrow.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.e2e-playground.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.e2e.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.module.css
  packages/vkui/src/components/ScrollArrow/ScrollArrow.test.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.tsx
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-android-chromium-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-webkit-light-1-snap.png
  packages/vkui/src/index.ts
  styleguide/config.js
Labels: type:feature

#5124 fix(View): fade after content
  packages/vkui/src/components/Panel/Panel.tsx
Labels: patch

#5127 deps(@csstools/postcss-global-data): fix to 1.0.1
  package.json
  yarn.lock
Labels: dependencies, technical task

#4850 fix(WriteBar): Fix WriteBar elements position
  packages/vkui/src/components/WriteBar/WriteBar.module.css
  packages/vkui/src/components/WriteBar/WriteBar.tsx
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-light-1-snap.png
Labels: patch, no-stale

#5129 fix(ChipsSelect): fix focusedOptionIndex logic
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
Labels: patch

#4842 build: update @swc/helpers 0.5.0
  package.json
  packages/vkui/package.json
  tools/swc-transform-css-modules/Cargo.lock
  tools/swc-transform-css-modules/Cargo.toml
  tools/swc-transform-css-modules/rust-toolchain.toml
  tools/swc-transform-css-modules/src/lib.rs
  tools/swc-transform-css-modules/swc_transform_css_modules.wasm
  tools/swc-transform-css-modules/tests/fixture/component/input.js
  tools/swc-transform-css-modules/tests/fixture/component/output.js
  yarn.lock
Labels: pr-needs-work, no-stale

#5132 fix(a11y/NativeSelect): hide duplication of selected option from screen reader
  packages/vkui/src/components/NativeSelect/NativeSelect.test.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
Labels: patch

#5119 build(deps-dev): playwright to 1.34.3
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
  package.json
  packages/vkui/docker-compose.yml
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-android-chromium-dark-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-android-chromium-light-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-ios-webkit-light-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/DateInput/__image_snapshots__/dateinput-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-ios-webkit-light-1-snap.png
  yarn.lock
Labels: dependencies, technical task

#5151 CLND-9207: В календаре в сайдбаре подчеркнут вчерашний день, до перезагрузки страницы
  packages/vkui/src/hooks/useTodayDate.ts
Labels: patch

#4380 fix(ModalRoot): drop state after close modal
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: patch
