Repository VKCOM/VKUI, pull requests merged in 2023-06, with the labels that each got.

#5159 fix(CustomSelect): Don't show clear button with empty props.value
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch

#4948 feat(Placeholder): add `withPadding`
  packages/vkui/src/components/Placeholder/Placeholder.module.css
  packages/vkui/src/components/Placeholder/Placeholder.tsx
Labels: type:feature, cmp:placeholder, pr-needs-work

#5123 fix(CustomSelect): click on already selected option triggers onChange
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch

#5185 build(deps): cargo update
  tools/swc-transform-css-modules/Cargo.lock
Labels: dependencies, rust

#5158 fix(ActionSheetItem): margin before for desktop
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
Labels: patch

#5156 fix(Tabbar): change padding
  packages/vkui/src/components/Badge/Badge.module.css
  packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/TabbarItem/TabbarItem.module.css
Labels: patch

#5163 fix(NativeSelect): omit `multiple`
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
Labels: patch

#5195 fix(Panel): Add z-index to fade element
  packages/vkui/src/components/View/View.module.css
  packages/vkui/src/styles/constants.css
Labels: patch

#5201 docs(Gallery): use placebear
  packages/vkui/src/components/Gallery/Readme.md
Labels: patch

#5207 docs(Popover): fix incorrect words ending
  packages/vkui/src/components/Popover/Popover.tsx
Labels: patch

#5209 docs: fix PanelHeader name
  packages/vkui/src/components/PanelHeader/LegacyPanelHeaderContent.tsx
  packages/vkui/src/components/PanelHeader/PanelHeader.tsx
Labels: patch

#5250 build(deps-dev): Bump playwright to 1.35.0
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
  package.json
  packages/vkui/docker-compose.yml
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png
  yarn.lock
Labels: dependencies, javascript

#5265 docs(Banner): header, subheader, text description
  packages/vkui/src/components/Banner/Banner.e2e-playground.tsx
  packages/vkui/src/components/Banner/Banner.tsx
  packages/vkui/src/components/Banner/Readme.md
  packages/vkui/src/components/Banner/__image_snapshots__/banner-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-android-chromium-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-webkit-light-1-snap.png
Labels: docs, cmp:banner, patch

#5224 fix(ModalCard): add getRootRef
  packages/vkui/src/components/ModalCard/ModalCard.tsx
Labels: patch

#5269 fix(TabbarItem): use getRootRef prop in ref
  packages/vkui/src/components/TabbarItem/TabbarItem.tsx
Labels: type:bug, cmp:tabbar-item, patch

#5277 docs: update doc url
  README.md
Labels: docs

#5263 build(deps-dev): Bump @swc/core to 1.3.64
  package.json
  tools/swc-transform-css-modules/Cargo.lock
  tools/swc-transform-css-modules/Cargo.toml
  tools/swc-transform-css-modules/swc_transform_css_modules.wasm
  yarn.lock
Labels: technical task

#5221 Remove useless onClick handler
  packages/vkui/src/components/Chip/Readme.md
Labels: patch

#5281 fix(TabbarItem): delete unnecessary styles
  packages/vkui/src/components/TabbarItem/TabbarItem.tsx
Labels: type:enhancement, cmp:tabbar-item

#5303 build(deps-dev): Bump playwright from 1.35.0 to 1.35.1
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
  package.json
  packages/vkui/docker-compose.yml
  yarn.lock
Labels: dependencies, javascript

#5307 tech(playwright): rm mouse pos reset
  packages/vkui/src/testing/e2e/index.playwright.ts
Labels: technical task

#5312 tech(deps): add schedule for complex cargo update
  .github/dependabot.yml
  .github/workflows/schedule_cargo_update.yml
Labels: dependencies, technical task

#5324 doc(FixedLayout): add filled
  packages/vkui/src/components/FixedLayout/Readme.md
Labels: patch

#5309 fix(Select): nativeProps
  packages/vkui/src/components/Select/Select.tsx
Labels: patch

#5279 fix(PullToRefresh): Center spinner related to content
  packages/vkui/src/components/FixedLayout/FixedLayout.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-renders-spinner-properly-when-parent-has-padding-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-renders-spinner-properly-when-parent-has-padding-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-renders-spinner-properly-when-parent-has-padding-vkcom-webkit-light-1-snap.png
Labels: patch

#5330 Discard adding creatable value without flag
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
Labels: type:bug, cmp:chips-select, patch

#5331 doc(types): add LiteralUnion
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/components/Tappable/Tappable.tsx
  packages/vkui/src/lib/platform.ts
  packages/vkui/src/types.ts
Labels: patch

#5262 fix: Доступность спиннеров
  packages/vkui/src/components/FormItem/Readme.md
  packages/vkui/src/components/PanelSpinner/Readme.md
  packages/vkui/src/components/ScreenSpinner/Readme.md
  packages/vkui/src/components/ScreenSpinner/ScreenSpinner.module.css
  packages/vkui/src/components/ScreenSpinner/ScreenSpinner.tsx
  packages/vkui/src/components/Slider/Readme.md
  packages/vkui/src/components/Spinner/Readme.md
  packages/vkui/src/components/Spinner/Spinner.tsx
  packages/vkui/src/components/Tabs/Readme.md
  styleguide/Components/Modals/Platforms.js
  styleguide/Components/Modals/Versions.js
Labels: patch

#5311 fix(CustomSelect): add selectOption
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch

#5304 fix(autoDetectAppearanceByBridge): bridge async
  packages/vkui/src/hooks/useAutoDetectAppearance.tsx
Labels: patch

#5344 fix(Group): adaptivity
  packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-android-chromium-light-1-snap.png
  packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ButtonGroup/__image_snapshots__/buttongroup-align-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Group/Group.module.css
  packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-viewwidth-small-tablet-haspointer-true-android-chromium-dark-1-snap.png
  packages/vkui/src/components/HorizontalScroll/__image_snapshots__/horizontalscroll-viewwidth-small-tablet-haspointer-true-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-desktop-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-desktop-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-desktop-ios-only-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-desktop-ios-only-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-android-chromium-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-android-chromium-light-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Placeholder/__image_snapshots__/placeholder-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-android-chromium-light-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Radio/__image_snapshots__/radio-vkcom-webkit-light-1-snap.png
Labels: patch

#5364 fix(Group): spacing adaptivity
  packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/CardScroll/__image_snapshots__/cardscroll-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Group/Group.module.css
  packages/vkui/src/components/Group/Group.tsx
Labels: patch

#5365 fix(Header): add multiline style + fix paddings
  packages/vkui/src/components/Group/Group.tsx
  packages/vkui/src/components/Header/Header.module.css
  packages/vkui/src/components/Header/Header.tsx
Labels: patch

#5370 Update Group doc for auto mode
  packages/vkui/src/components/Group/Group.tsx
Labels: docs, adaptivity, cmp:group

#5371 Fix Group padding for modal
  packages/vkui/src/components/Group/Group.module.css
  packages/vkui/src/components/Group/Group.tsx
Labels: type:bug, cmp:modal, cmp:group, patch

#5373 fix: Icon20TextHeading1Outline is 20 size
  packages/vkui/src/components/ImageBase/validators.ts
Labels: patch

#5366 ci: complete Playwright and Storybook update
  .github/actions/complete_playwright_update.yml
  .github/actions/complete_storybook_update.yml
  .github/dependabot.yml
  .github/workflows/pull_request_common.yml
Labels: dependencies, technical task

#5375 Изменена формулировка "следует следовать"
  docs/CONTRIBUTING.md
Labels: docs

#5374 fix(deps): use caret range
  packages/vkui/package.json
  yarn.lock
Labels: patch

#5387 fix(github actions): use correct infra for actions
  .github/actions/complete_playwright_update/action.yml
  .github/actions/complete_storybook_update/action.yml
Labels: type:bug, technical task, github_actions

#5388 fix(github actions): set git creds before push
  .github/actions/complete_playwright_update/action.yml
  .github/actions/complete_storybook_update/action.yml
Labels: type:bug, technical task, github_actions

#5391 refactor(github actions): create new workflow
  .github/workflows/pull_request_common.yml
  .github/workflows/pull_request_dependabot.yml
Labels: technical task, github_actions

#5395 fix(Routing): update children type
  packages/vkui/src/components/Epic/Epic.tsx
  packages/vkui/src/components/ModalRoot/types.ts
  packages/vkui/src/components/Root/Root.test.tsx
  packages/vkui/src/components/Root/Root.tsx
  packages/vkui/src/components/View/View.test.tsx
  packages/vkui/src/components/View/View.tsx
  packages/vkui/src/storybook/ModalWrapper.tsx
Labels: patch
