Repository VKCOM/VKUI, pull requests merged in 2023-12, with the labels that each got.

#6181 docs(useFloatingWithInteractions): reword descriptions
  packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts
Labels: docs

#6129 [BREAKING CHANGE] feat(Popover): mv to stable
  packages/vkui/src/components/Popover/Popover.module.css
  packages/vkui/src/components/Popover/Popover.stories.tsx
  packages/vkui/src/components/Popover/Popover.test.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popover/Readme.md
  packages/vkui/src/index.ts
  packages/vkui/src/lib/accessibility.test.ts
  packages/vkui/src/lib/accessibility.ts
  packages/vkui/src/lib/cssAnimation/fades.ts
  packages/vkui/src/lib/cssAnimation/index.ts
  packages/vkui/src/lib/cssAnimation/transformOrigin.ts
  packages/vkui/src/styles/animationFades.module.css
  packages/vkui/src/styles/transformOriginByPlacement.module.css
Labels: breaking-change

#6188 refactor: useKeyboardInputTracker()
  packages/vkui/src/components/AppRoot/AppRoot.tsx
  packages/vkui/src/hooks/useKeyboardInputTracker.test.ts
  packages/vkui/src/hooks/useKeyboardInputTracker.ts
  packages/vkui/src/lib/accessibility.ts
Labels: type:enhancement, technical task

#6187 fix(useDraggableWithDomApi): placeholder double render (React 18)
  packages/vkui/src/hooks/useDraggableWithDomApi/useDraggableWithDomApi.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/utils.ts
Labels: type:bug, cmp:cell

#6207 fix(Popper): rm unstable prefix
  packages/vkui/src/index.ts
Labels: type:bug, cmp:popper, breaking-change

#6139 [BREAKING CHANGE] refactor: Избавляемся от `aria-label` в пользу визуально скрытого текста
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/BaseGallery/types.ts
  packages/vkui/src/components/Calendar/Calendar.tsx
  packages/vkui/src/components/CalendarDay/CalendarDay.tsx
  packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/CalendarTime/CalendarTime.tsx
  packages/vkui/src/components/Cell/Cell.tsx
  packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx
  packages/vkui/src/components/Chip/Chip.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
  packages/vkui/src/components/InputLike/InputLike.tsx
  packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
  packages/vkui/src/components/ModalCardBase/ModalCardBaseCloseButton.tsx
  packages/vkui/src/components/ModalCardBase/Readme.md
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.tsx
  packages/vkui/src/components/ModalDismissButton/Readme.md
  packages/vkui/src/components/Pagination/Pagination.tsx
  packages/vkui/src/components/Pagination/PaginationPage/PaginationPageButton.tsx
  packages/vkui/src/components/Pagination/utils.ts
  packages/vkui/src/components/PanelHeader/PanelHeader.stories.tsx
  packages/vkui/src/components/PanelHeader/Readme.md
  packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
  packages/vkui/src/components/PanelHeaderClose/PanelHeaderClose.tsx
  packages/vkui/src/components/PanelHeaderEdit/PanelHeaderEdit.tsx
  packages/vkui/src/components/PanelHeaderSubmit/PanelHeaderSubmit.tsx
  packages/vkui/src/components/Removable/Removable.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.test.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.tsx
  packages/vkui/src/components/Search/Readme.md
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/TabbarItem/Readme.md
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
  packages/vkui/src/components/WriteBar/Readme.md
  packages/vkui/src/components/WriteBar/WriteBar.e2e-playground.tsx
  packages/vkui/src/components/WriteBar/WriteBar.stories.tsx
  packages/vkui/src/components/WriteBarIcon/Readme.md
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.test.tsx
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
  packages/vkui/src/index.ts
  packages/vkui/src/lib/select.ts
  packages/vkui/src/lib/utils.ts
  styleguide/Components/StyleGuide/StyleGuideMobile.js
Labels: breaking-change

#6132 BREAKING CHANGE: rewrite Tappable
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.test.tsx
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
  packages/vkui/src/components/Banner/Banner.tsx
  packages/vkui/src/components/Button/Button.tsx
  packages/vkui/src/components/Button/Readme.md
  packages/vkui/src/components/ButtonGroup/Readme.md
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/CalendarDay/CalendarDay.tsx
  packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
  packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
  packages/vkui/src/components/Cell/Cell.test.tsx
  packages/vkui/src/components/Cell/Cell.tsx
  packages/vkui/src/components/CellButton/CellButton.module.css
  packages/vkui/src/components/CellButton/CellButton.tsx
  packages/vkui/src/components/CellButton/Readme.md
  packages/vkui/src/components/Checkbox/Checkbox.tsx
  packages/vkui/src/components/Clickable/Clickable.module.css
  packages/vkui/src/components/Clickable/Clickable.stories.tsx
  packages/vkui/src/components/Clickable/Clickable.tsx
  packages/vkui/src/components/Clickable/useKeyboard.tsx
  packages/vkui/src/components/Clickable/useState.tsx
  packages/vkui/src/components/Clickable/useStateWithDelay.tsx
  packages/vkui/src/components/ContentCard/ContentCard.test.tsx
  packages/vkui/src/components/ContentCard/ContentCard.tsx
  packages/vkui/src/components/HorizontalCell/Readme.md
  packages/vkui/src/components/HorizontalCellShowMore/Readme.md
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.e2e-playground.tsx
  packages/vkui/src/components/HorizontalScroll/Readme.md
  packages/vkui/src/components/Image/Image.e2e-playground.tsx
  packages/vkui/src/components/Image/Readme.md
  packages/vkui/src/components/ImageBase/ImageBaseOverlay/ImageBaseOverlay.tsx
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.test.tsx
  packages/vkui/src/components/Radio/Radio.tsx
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/TabbarItem/TabbarItem.tsx
  packages/vkui/src/components/Tabs/Tabs.e2e-playground.tsx
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Tappable/Readme.md
  packages/vkui/src/components/Tappable/Ripple.tsx
  packages/vkui/src/components/Tappable/Tappable.e2e-playground.tsx
  packages/vkui/src/components/Tappable/Tappable.module.css
  packages/vkui/src/components/Tappable/Tappable.test.tsx
  packages/vkui/src/components/Tappable/Tappable.tsx
  packages/vkui/src/components/Tappable/state.tsx
  packages/vkui/src/components/View/View.stories.tsx
  packages/vkui/src/lib/mergeCalls.test.ts
  packages/vkui/src/lib/mergeCalls.ts
Labels: breaking-change

#6218 docs(styleguide): use gzipped https://registry.npmjs.org/@vkontakte/vkui req
  styleguide/Components/Modals/Versions.js
Labels: docs, technical task

#6238 refactor: migration_v6.md
  styleguide/Components/Heading/HeadingRenderer.js
  styleguide/Components/Link/LinkRenderer.js
  styleguide/pages/migration_v6.md
  styleguide/utils/index.js
  styleguide/utils/third-party/lodash/index.js
  styleguide/utils/third-party/lodash/unicodeWords.js
  styleguide/utils/third-party/lodash/words.js
  styleguide/utils/third-party/react-children-utils/index.js
Labels: docs, technical task

#6273 docs(styleguide): resolve technical debt after release `v6.0.0-beta.1`
  packages/vkui/src/components/ModalRoot/Readme.md
  packages/vkui/src/components/Slider/Readme.md
  packages/vkui/src/components/Tabs/Readme.md
  styleguide/Components/Heading/Heading.css
  styleguide/Components/Heading/HeadingRenderer.js
  styleguide/package.json
  styleguide/pages/migration_v6.md
  styleguide/tsconfig.json
  styleguide/utils/index.js
  styleguide/utils/third-party/lodash/index.js
  styleguide/utils/third-party/lodash/unicodeWords.js
  styleguide/utils/third-party/lodash/words.js
  styleguide/utils/third-party/react-children-utils/index.js
  yarn.lock
Labels: docs, technical task

#6275 chore(migration_v6): add subheaders to sublist of page list
  styleguide/pages/migration_v6.md
Labels: docs

#6276 fix(PopoutRoot): use className by props in Popout and Modal sub-cmp
  packages/vkui/src/components/PopoutRoot/PopoutRoot.test.tsx
  packages/vkui/src/components/PopoutRoot/PopoutRoot.tsx
Labels: type:bug, cmp:popout

#6230 (ModalCardBase): Remove cascade offset using Spacing component
  packages/vkui/src/components/FormField/FormField.module.css
  packages/vkui/src/components/ModalCard/ModalCard.e2e-playground.tsx
  packages/vkui/src/components/ModalCardBase/ModalCardBase.module.css
  packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
  packages/vkui/src/components/ModalCardBase/Readme.md
  packages/vkui/src/components/ModalRoot/Readme.md
  packages/vkui/src/components/UsersStack/UsersStack.module.css
  packages/vkui/src/components/UsersStack/UsersStack.tsx
  styleguide/pages/migration_v6.md
Labels: type:enhancement

#6323 ci(publish_prerelease): remove close_milestone
  .github/workflows/publish_prerelease.yml
Labels: technical task

#6318 fix(HorizontalCell): use max-width for size="m"
  packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
Labels: type:bug, cmp:horizontal-cell

#6341 bump(deps): prepare for Stylelint v16
  package.json
  stylelint.config.js
  tools/stylelint-bad-multiplication/index.js
  tools/stylelint-bad-multiplication/jest.config.js
  tools/stylelint-bad-multiplication/jest.setup.js
  tools/stylelint-bad-multiplication/package.json
  yarn.lock
Labels: technical task

#6339 chore(docs): use relative links
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/Alert/Readme.md
  packages/vkui/src/components/AppRoot/Readme.md
  packages/vkui/src/components/Avatar/Readme.md
  packages/vkui/src/components/ConfigProvider/Readme.md
  packages/vkui/src/components/FormField/Readme.md
  packages/vkui/src/components/ModalCardBase/Readme.md
  packages/vkui/src/components/ModalRoot/Readme.md
  packages/vkui/src/components/OnboardingTooltip/Readme.md
  packages/vkui/src/components/PanelSpinner/Readme.md
  packages/vkui/src/components/ScreenSpinner/Readme.md
  packages/vkui/src/components/Spinner/Readme.md
  packages/vkui/src/components/SubnavigationButton/Readme.md
  packages/vkui/src/components/TabsItem/Readme.md
  packages/vkui/src/components/Tappable/Readme.md
  packages/vkui/src/components/TooltipBase/Readme.md
  styleguide/pages/adaptivity.md
  styleguide/pages/html.md
  styleguide/pages/integrations_vk_mini_apps.md
  styleguide/pages/intro.md
  styleguide/pages/migration_v6.md
  styleguide/pages/modes.md
Labels: docs, v6.0.0-beta.3

#6342 docs(Input): textInputRef.focus() when clear()
  packages/vkui/src/components/Input/Readme.md
Labels: type:enhancement, docs, cmp:input, v6.0.0-beta.3

#6324 fix(README.md): update doc links to v6.0.0-beta.3
  README.md
Labels: type:bug, docs, v6.0.0-beta.3
