Repository VKCOM/VKUI, pull requests merged in 2023-11, with the labels that each got.

#6074 docs: Add versions sorting
  styleguide/Components/Modals/Versions.js
Labels: patch, v5

#6075 tech: rm migration_v6.md
  styleguide/pages/migration_v6.md
Labels: technical task

#6076 fix(Select/CustomSelect): Allow to use custom options in renderOption prop
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/Select/Select.tsx
  packages/vkui/src/index.ts
  packages/vkui/src/lib/select.ts
Labels: patch, v5

#6054 feat(Modal): focus to modal container if controllable element doesn't focused
  packages/vkui/src/components/ModalCard/ModalCard.e2e-playground.tsx
  packages/vkui/src/components/ModalCard/ModalCard.module.css
  packages/vkui/src/components/ModalCard/ModalCard.test.tsx
  packages/vkui/src/components/ModalCard/ModalCard.tsx
  packages/vkui/src/components/ModalPage/ModalPage.module.css
  packages/vkui/src/components/ModalPage/ModalPage.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
  packages/vkui/src/components/ModalRoot/types.ts
Labels: patch, v5

#6086 build(deps-dev): Bump @vkontakte/vkui-tokens from 4.41.0 to 4.41.1
  package.json
  yarn.lock
Labels: v5

#6048 docs: add icons and tokens
  packages/vkui/shared.config.js
  styleguide/Components/StyleGuide/StyleGuideHeader.js
  styleguide/pages/customize.md
Labels: docs, v5

#6109 build(deps): bump @vkontakte/vkui-floating-ui to v0.1.2
  packages/vkui/package.json
  yarn.lock
Labels: dependencies, technical task, v5

#6046 docs(View): add info about correct Panel order
  packages/vkui/src/components/View/Readme.md
Labels: docs, v5

#6107 build: remove @types/css-font-loading-module
  package.json
  yarn.lock
Labels: dependencies, technical task, v5

#5833 feat(Cell): add auto scroll for draggable mode
  packages/vkui/jest.setup.js
  packages/vkui/src/components/Cell/Cell.module.css
  packages/vkui/src/components/Cell/Cell.test.tsx
  packages/vkui/src/components/Cell/Cell.tsx
  packages/vkui/src/components/Cell/CellDragger/CellDragger.module.css
  packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx
  packages/vkui/src/components/Cell/constants.ts
  packages/vkui/src/components/Cell/useDraggable.tsx
  packages/vkui/src/components/List/List.module.css
  packages/vkui/src/components/List/List.tsx
  packages/vkui/src/components/List/ListContext.ts
  packages/vkui/src/components/Touch/Touch.tsx
  packages/vkui/src/hooks/useDraggableWithDomApi/autoScroll.test.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/autoScroll.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/constants.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/index.tsx
  packages/vkui/src/hooks/useDraggableWithDomApi/types.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/useDraggableWithDomApi.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/utils.test.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/utils.ts
  packages/vkui/src/lib/dom.test.ts
  packages/vkui/src/lib/dom.tsx
  packages/vkui/src/lib/rafSchd.ts
  packages/vkui/src/styles/constants.css
  packages/vkui/src/testing/e2e/index.playwright.ts
  packages/vkui/src/testing/e2e/types.ts
  packages/vkui/src/testing/e2e/utils.tsx
  packages/vkui/src/testing/utils.tsx
  packages/vkui/tsconfig.json
  tsconfig.json
Labels: v5

#6125 fix(TabsItem): use hasReactNode for status
  packages/vkui/src/components/Tabs/Tabs.e2e-playground.tsx
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/TabsItem/TabsItem.tsx
Labels: v5

#6068 feat(ModalCard): add dismissButtonMode
  packages/vkui/src/components/ModalCard/ModalCard.e2e-playground.tsx
  packages/vkui/src/components/ModalCard/ModalCard.tsx
  packages/vkui/src/components/ModalCard/Readme.md
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCardBase/ModalCardBase.module.css
  packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
  packages/vkui/src/components/ModalCardBase/ModalCardBaseCloseButton.tsx
  packages/vkui/src/components/ModalCardBase/Readme.md
Labels: v5

#5866 feat(Calendar): add min/max date with time
  packages/vkui/src/components/Calendar/Calendar.e2e-playground.tsx
  packages/vkui/src/components/Calendar/Calendar.stories.tsx
  packages/vkui/src/components/Calendar/Calendar.test.tsx
  packages/vkui/src/components/Calendar/Calendar.tsx
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-android-chromium-light-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/CalendarTime/CalendarTime.tsx
  packages/vkui/src/hooks/useCalendar.ts
  packages/vkui/src/lib/calendar.test.tsx
  packages/vkui/src/lib/calendar.ts
Labels: no-stale, v5

#5908 feat: add provenance
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
  .github/workflows/publish_token_translator.yml
  .github/workflows/publish_vkui_floating_ui_react_dom.yml
  packages/token-translator/package.json
  packages/vkui-floating-ui/package.json
  packages/vkui/package.json
Labels: no-stale, v5

#5790 feat(Search): add Find button
  packages/vkui/src/components/Search/Readme.md
  packages/vkui/src/components/Search/Search.e2e-playground.tsx
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-light-1-snap.png
Labels: no-stale, v5

#6087 fix(Select): make Select accessible for screen readers
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelect/CustomSelectClearButton.tsx
  packages/vkui/src/components/CustomSelect/CustomSelectInput.module.css
  packages/vkui/src/components/CustomSelect/CustomSelectInput.tsx
  packages/vkui/src/components/CustomSelect/Readme.md
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
  packages/vkui/src/components/CustomSelectOption/Readme.md
  packages/vkui/src/components/FormItem/Readme.md
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/NativeSelect/Readme.md
  packages/vkui/src/components/Select/Readme.md
  packages/vkui/src/components/Select/Select.test.tsx
Labels: v5

#6114 feat(Tabs): add layoutFillMode prop
  packages/vkui/src/components/Tabs/Readme.md
  packages/vkui/src/components/Tabs/Tabs.e2e-playground.tsx
  packages/vkui/src/components/Tabs/Tabs.e2e.tsx
  packages/vkui/src/components/Tabs/Tabs.tsx
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-layout-fill-mode-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-layout-fill-mode-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-layout-fill-mode-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-layout-fill-mode-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-layout-fill-mode-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/TabsItem/TabsItem.module.css
  packages/vkui/src/components/TabsItem/TabsItem.tsx
Labels: v5

#6134 ci(pr-auto-add-label): rm v5; a.i. disable patch
  .github/workflows/pull_request_common.yml
Labels: technical task

#6135 feat(usePatchChildren): opportunity to provide props
  packages/vkui/src/components/HoverPopper/HoverPopper.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/helpers/getMergedSameEventsByProps.test.ts
  packages/vkui/src/helpers/getMergedSameEventsByProps.ts
  packages/vkui/src/hooks/usePatchChildren.test.tsx
  packages/vkui/src/hooks/usePatchChildren.ts
  packages/vkui/src/hooks/usePatchChildrenRef.ts
  packages/vkui/src/lib/utils.ts
  packages/vkui/src/types.ts
Labels: type:feature

#6137 feat: create utilities functions
  packages/vkui/src/hooks/useGlobalOnClickOutside.test.tsx
  packages/vkui/src/hooks/useGlobalOnClickOutside.ts
  packages/vkui/src/hooks/useStableCallback.test.ts
  packages/vkui/src/hooks/useStableCallback.ts
  packages/vkui/src/lib/createPortal.test.tsx
  packages/vkui/src/lib/createPortal.ts
  packages/vkui/src/lib/dom.test.ts
  packages/vkui/src/lib/dom.tsx
Labels: type:feature

#6136 feat(useEnsuredControl): opportunity to use dispatch fn for change state
  packages/vkui/src/hooks/useEnsuredControl.test.tsx
  packages/vkui/src/hooks/useEnsuredControl.ts
Labels: type:feature

#6145 BREAKING CHANGE(ActionSheet, Alert): remove autoClose
  packages/vkui/src/components/ActionSheet/ActionSheet.stories.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/ActionSheet/ActionSheetDefaultIosCloseItem.tsx
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
  packages/vkui/src/components/ActionSheetItem/Readme.md
  packages/vkui/src/components/Alert/Alert.stories.tsx
  packages/vkui/src/components/Alert/Alert.test.tsx
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/Alert/AlertActions.tsx
  packages/vkui/src/components/Alert/Readme.md
  packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
  styleguide/Components/Setting/Setting.js
  styleguide/pages/migration_v6.md
Labels: breaking-change

#6150 feat: extend lib/floating
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
  packages/vkui/src/lib/dom.test.ts
  packages/vkui/src/lib/dom.tsx
  packages/vkui/src/lib/floating/adapters.ts
  packages/vkui/src/lib/floating/index.ts
  packages/vkui/src/lib/floating/types.ts
  packages/vkui/src/lib/floating/useFloatingMiddlewaresBootstrap/index.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/__snapshots__/useFloatingWithInteractions.test.tsx.snap
  packages/vkui/src/lib/floating/useFloatingWithInteractions/constants.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/index.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useResolveTriggerType.test.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useResolveTriggerType.ts
  packages/vkui/src/testing/utils.tsx
Labels: type:feature

#6130 BREAKING CHANGE: [Headlline] change default Component to span
  packages/vkui/src/components/Typography/Headline/Headline.tsx
  packages/vkui/src/components/Typography/Headline/Readme.md
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-android-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/Headline/__image_snapshots__/headline-vkcom-webkit-light-1-snap.png
  styleguide/pages/migration_v6.md
Labels: breaking-change

#6133 BREAKING CHANGE: [Subhead] change default component to span
  packages/vkui/src/components/Typography/Subhead/Readme.md
  packages/vkui/src/components/Typography/Subhead/Subhead.tsx
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-android-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/Subhead/__image_snapshots__/subhead-vkcom-webkit-light-1-snap.png
  styleguide/pages/migration_v6.md
Labels: breaking-change

#6161 feat(Title): Don't link Component with level by default
  packages/vkui/src/components/Typography/Title/Title.tsx
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-android-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/Title/__image_snapshots__/title-vkcom-webkit-light-1-snap.png
  styleguide/pages/migration_v6.md
Labels: breaking-change

#6163 feat(Header): Allow to change subtitle component
  packages/vkui/src/components/Header/Header.stories.tsx
  packages/vkui/src/components/Header/Header.test.tsx
  packages/vkui/src/components/Header/Header.tsx
  packages/vkui/src/components/Header/Readme.md
  styleguide/pages/migration_v6.md
Labels: cmp:header, breaking-change

#6172 feat(FormItem): Allow to change default tag for top prop
  packages/vkui/src/components/FormItem/FormItem.test.tsx
  packages/vkui/src/components/FormItem/FormItem.tsx
  styleguide/pages/migration_v6.md
Labels: cmp:form-item, breaking-change

#6166 feat(useFloatingWithInteractions): extend API
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
  packages/vkui/src/lib/floating/types.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/__snapshots__/useFloatingWithInteractions.test.tsx.snap
  packages/vkui/src/lib/floating/useFloatingWithInteractions/index.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: type:feature, technical task
