Repository VKCOM/VKUI, pull requests merged in 2023-03, with the labels that each got.

#4348 fix(Input): throw up mode param to form-field
  packages/vkui/src/components/Input/Input.tsx
Labels: patch

#4347 fix(CustomSelect): correct placeholder appearance
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-android-chromium-dark-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-android-chromium-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-ios-webkit-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-android-chromium-light-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SelectMimicry/__image_snapshots__/selectmimicry-vkcom-webkit-light-1-snap.png
Labels: patch

#4389 docs(List): update docs to reflect proper usage
  packages/vkui/src/components/List/Readme.md
Labels: patch

#4236 fix(RichCell): fix design review notes
  packages/vkui/src/components/RichCell/Readme.md
  packages/vkui/src/components/RichCell/RichCell.e2e.tsx
  packages/vkui/src/components/RichCell/RichCell.module.css
  packages/vkui/src/components/RichCell/RichCell.tsx
  packages/vkui/src/components/RichCell/RichCellIcon/RichCellIcon.module.css
  packages/vkui/src/components/RichCell/RichCellIcon/RichCellIcon.tsx
  packages/vkui/src/components/RichTooltip/Readme.md
Labels: patch

#4400 fix(UsersStack): fix unnecessary margin
  packages/vkui/src/components/UsersStack/UsersStack.e2e.tsx
  packages/vkui/src/components/UsersStack/UsersStack.module.css
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-android-chromium-dark-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-android-chromium-light-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-ios-webkit-light-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/UsersStack/__image_snapshots__/usersstack-vkcom-webkit-light-1-snap.png
Labels: patch

#4433 fix(Touch): сбрасываем состояние для тач-устройств при touchmove
  packages/vkui/src/components/Touch/Touch.tsx
Labels: patch

#4441 fix(UsersStack): hide if count > 99
  packages/vkui/src/components/UsersStack/UsersStack.tsx
Labels: patch

#4451 fix(WriteBarIcon): cleanup browser styles
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
Labels: patch

#4483 fix(pull_request_packages.yml): fix glob pattern in paths-ignore
  .github/workflows/pull_request_packages.yml
Labels: patch

#4493 fix(SplitCol): `spaced` deprecated
  packages/vkui/src/components/SplitCol/SplitCol.tsx
  styleguide/pages/adaptivity.md
Labels: patch

#4518 docs: internal css
  styleguide/pages/customize.md
Labels: patch

#4534 ci(@actions-internal/patch): fix 'invalid refspec' problem
  .github/actions/patch/src/main.ts
  .github/actions/patch/src/message.ts
Labels: technical task

#4387 feat(Header): Add large variant for Header
  packages/vkui/src/components/Header/Header.e2e.tsx
  packages/vkui/src/components/Header/Header.test.tsx
  packages/vkui/src/components/Header/Header.tsx
  packages/vkui/src/components/Header/Readme.md
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:header

#4496 fix(PopperArrow): add vertical offset for remove white space
  packages/vkui/src/components/PopperArrow/PopperArrow.module.css
  packages/vkui/src/components/PopperArrow/PopperArrow.tsx
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-webkit-light-1-snap.png
Labels: patch

#4578 ci(file-filters.yml): fix bad glob pattern for package_vkui
  .github/file-filters.yml
Labels: technical task

#4575 fix(@vkontakte/vkui): copy docs/assets dir before publish
  packages/vkui/package.json
Labels: technical task

#4608 fix(Counter): secondary background
  packages/vkui/src/components/Counter/Counter.module.css
  packages/vkui/src/components/Counter/__image_snapshots__/counter-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-android-chromium-light-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Counter/__image_snapshots__/counter-vkcom-webkit-light-1-snap.png
Labels: patch

#4624 fix(ModalPage): header:empty + content radius
  packages/vkui/src/components/ModalPage/ModalPage.module.css
Labels: patch

#4628 fix(Tappable): hasHover cursor
  packages/vkui/src/components/Tappable/Tappable.module.css
  packages/vkui/src/components/Tappable/Tappable.tsx
Labels: patch

#4625 fix(ModalPage): ModalPage__content-in height: 100%
  packages/vkui/src/components/ModalPage/ModalPage.module.css
Labels: patch

#4650 fix(CustomSelect): getRef
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch

#4629 docs(TabbarItem): add aria-label
  packages/vkui/src/components/TabbarItem/Readme.md
  packages/vkui/src/components/TabbarItem/TabbarItem.tsx
Labels: patch
