Repository VKCOM/VKUI, pull requests merged in 2023-09, with the labels that each got.

#5447 Add milestone automatization
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
Labels: no-stale

#5739 fix: rm font-smoothing
  packages/vkui/src/styles/common.css
Labels: patch

#5743 feat: add useNavId
  packages/vkui/src/components/NavIdContext/NavIdContext.tsx
  packages/vkui/src/components/NavIdContext/useNavId.test.tsx
  packages/vkui/src/components/NavIdContext/useNavId.ts
  packages/vkui/src/components/Panel/Panel.tsx
  packages/vkui/src/components/View/View.tsx
  packages/vkui/src/components/View/ViewInfinite.tsx
  packages/vkui/src/index.ts
Labels: v5

#5663 feat(Alert): add inside close button (part 1)
  packages/vkui/src/components/Alert/Alert.module.css
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/Alert/Readme.md
  packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-ios-webkit-light-1-snap.png
  packages/vkui/src/components/IconButton/IconButton.module.css
Labels: v5

#5750 fix(TabbarItem): change text color token
  packages/vkui/src/components/Tabbar/Tabbar.e2e.tsx
  packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabbar/__image_snapshots__/tabbar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/TabbarItem/TabbarItem.module.css
  packages/vkui/src/testing/e2e/index.playwright.ts
  packages/vkui/src/testing/e2e/types.ts
Labels: patch, v5

#5717 tech: Use yarn v3
  .codesandbox/ci.json
  .gitattributes
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
  .github/workflows/publish_token_translator.yml
  .github/workflows/pull_request_common.yml
  .github/workflows/pull_request_packages.yml
  .github/workflows/reusable_workflow_test.yml
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
  .gitignore
  .prettierignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.6.3.cjs
  .yarnrc
  .yarnrc.yml
  docs/CONTRIBUTING.md
  package.json
  packages/token-translator/package.json
  packages/vkui/docker-compose.yml
  packages/vkui/package.json
  packages/vkui/yarn.lock
  tools/postcss-restructure-variable/package.json
  tools/stylelint-atomic/package.json
  tools/stylelint-bad-multiplication/package.json
  yarn.lock
Labels: v5

#5766 fix: bad env NODE_ENVIRONMENT
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx
  packages/vkui/src/components/AppRoot/AppRoot.tsx
  packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx
  packages/vkui/types/env.d.ts
Labels: patch, v5

#5761 tech(dependabot): add v5 label
  .github/dependabot.yml
Labels: technical task

#5781 tech: sync `v5` with `master`
  package.json
  packages/token-translator/package.json
  packages/vkui/package.json
  yarn.lock
Labels: dependencies, technical task, javascript

#5762 tech: Skip close milestone if needed with flag close_milestone
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
Labels: v5

#5784 tech: deduplication dependencies
  yarn.lock
Labels: dependencies, technical task, javascript, v5

#5764 Fix ModalDismissButton appearance in the doc
  packages/vkui/src/components/ModalDismissButton/Readme.md
Labels: patch, v5

#5768 chore: fix ActionSheet doc link
  packages/vkui/src/components/ActionSheet/Readme.md
Labels: patch, v5

#5783 feat: dynamic tokens
  packages/vkui/playwright/index.css
  packages/vkui/scripts/postcss.js
  packages/vkui/shared.config.js
  packages/vkui/src/components/Banner/Banner.module.css
  packages/vkui/src/components/Card/Card.module.css
  packages/vkui/src/components/Chip/Chip.module.css
  packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.module.css
  packages/vkui/src/components/FocusVisible/FocusVisible.module.css
  packages/vkui/src/components/FormField/FormField.module.css
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css
  packages/vkui/src/components/Group/Group.module.css
  packages/vkui/src/components/HorizontalCell/Readme.md
  packages/vkui/src/components/HorizontalCellShowMore/Readme.md
  packages/vkui/src/components/ImageBase/ImageBase.module.css
  packages/vkui/src/components/PanelHeader/PanelHeader.module.css
  packages/vkui/src/components/PromoBanner/PromoBanner.module.css
  packages/vkui/src/components/Separator/Separator.module.css
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css
  packages/vkui/src/components/Tabbar/Tabbar.module.css
  packages/vkui/src/components/TabsItem/TabsItem.module.css
  packages/vkui/src/components/WriteBar/WriteBar.module.css
  packages/vkui/src/index.ts
  packages/vkui/src/styles/constants.css
  packages/vkui/src/styles/dynamicTokens.css
  stylelint.config.js
Labels: v5

#5748 tech: turn on declaration map for vkui package
  packages/vkui/package.json
  packages/vkui/tsconfig.dist.json
Labels: v5

#5801 chore(ci): add latest tag support
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
Labels: v5

#5800 BREAKING CHANGE: target es2015
  .browserslistrc
  packages/vkui/package.swcrc
  styleguide/pages/migration_v6.md
Labels: technical task

#5805 fix(ModalRoot): fix modal overlay
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
Labels: patch, v5

#5799 fix(Group): header margin
  packages/vkui/src/components/Avatar/Readme.md
  packages/vkui/src/components/Gradient/Readme.md
  packages/vkui/src/components/Group/Group.e2e-playground.tsx
  packages/vkui/src/components/Group/Group.e2e.tsx
  packages/vkui/src/components/Group/Group.module.css
  packages/vkui/src/components/Group/Group.tsx
  packages/vkui/src/components/Group/__image_snapshots__/group-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-android-chromium-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Image/Readme.md
  packages/vkui/src/components/InfoRow/InfoRow.stories.tsx
  packages/vkui/src/components/InfoRow/Readme.md
  packages/vkui/src/components/SimpleCell/Readme.md
Labels: patch, v5

#5786 fix(Checkbox): simple width
  packages/vkui/src/components/Checkbox/Checkbox.e2e-playground.tsx
  packages/vkui/src/components/Checkbox/Checkbox.module.css
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-android-chromium-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-android-chromium-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-simple-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Checkbox/__image_snapshots__/checkbox-vkcom-webkit-light-1-snap.png
Labels: patch, v5

#5792 feature(ModalPage/Alert) Allow to pass testid to inner components
  packages/vkui/src/components/Alert/Alert.test.tsx
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/ModalPage/ModalPage.test.tsx
  packages/vkui/src/components/ModalPage/ModalPage.tsx
  packages/vkui/src/components/ModalPageHeader/ModalPageHeader.test.tsx
  packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx
  packages/vkui/src/components/PanelHeader/PanelHeader.tsx
Labels: v5

#5794 fix: SimpleCell rewrite padding
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-android-chromium-light-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Accordion/__image_snapshots__/accordion-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-android-chromium-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/CellButton/CellButton.module.css
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-android-chromium-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-ios-webkit-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-android-chromium-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-android-chromium-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/IconButton/IconButton.module.css
  packages/vkui/src/components/ImageBase/ImageBase.module.css
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
  packages/vkui/src/components/SimpleCell/SimpleCell.tsx
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Switch/Switch.module.css
Labels: patch, v5

#5803 feat(ImageBase): Clickable
  packages/vkui/src/components/Clickable/Clickable.module.css
  packages/vkui/src/components/Clickable/Clickable.test.tsx
  packages/vkui/src/components/Clickable/Clickable.tsx
  packages/vkui/src/components/ImageBase/ImageBase.tsx
Labels: v5

#5797 fix(ActionSheet): iOS Remove extra shadow padding
  packages/vkui/src/components/ActionSheet/ActionSheet.e2e.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.module.css
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.tsx
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
Labels: patch, v5

#5681 feat(Header): update margins
  packages/vkui/src/components/Header/Header.module.css
  packages/vkui/src/components/Header/Header.tsx
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-light-1-snap.png
Labels: v5

#5822 fix(Popper): mv to useLayoutEffect
  packages/vkui/src/components/Popper/Popper.tsx
Labels: patch, v5

#5829 feat(ActionSheet): add `mode`
  packages/vkui/src/components/ActionSheet/ActionSheet.module.css
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.tsx
  packages/vkui/src/components/ActionSheet/ActionSheetContext.ts
  packages/vkui/src/components/ActionSheet/ActionSheetDropdownMenu.tsx
  packages/vkui/src/components/ActionSheet/ActionSheetDropdownSheet.tsx
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
Labels: v5

#5828 feat(ActionSheetItem): add `after`
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
  packages/vkui/src/components/ActionSheetItem/subcomponents/Radio/Radio.module.css
  packages/vkui/src/components/ActionSheetItem/subcomponents/Radio/Radio.tsx
Labels: v5

#5824 fix(Banner): padding in
  packages/vkui/src/components/Banner/Banner.module.css
  packages/vkui/src/components/Banner/Banner.tsx
  packages/vkui/src/components/Banner/__image_snapshots__/banner-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-android-chromium-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-webkit-light-1-snap.png
Labels: patch, v5

#5826 feat(Tappable): add `activated`
  packages/vkui/src/components/Tappable/Tappable.e2e-playground.tsx
  packages/vkui/src/components/Tappable/Tappable.e2e.tsx
  packages/vkui/src/components/Tappable/Tappable.tsx
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Tappable/__image_snapshots__/tappable-vkcom-webkit-light-1-snap.png
Labels: v5

#5830 feature(ModalPage): Add height prop to ModalPage
  packages/vkui/src/components/ModalPage/ModalPage.tsx
  packages/vkui/src/components/ModalRoot/Readme.md
Labels: v5

#5832 chore: rm lib/is
  packages/vkui/src/lib/is.ts
Labels: patch, v5

#5831 docs(PanelHeader): if after is Banner
  packages/vkui/src/components/PanelHeader/Readme.md
Labels: patch, v5

#5841 chore: add storybook dist to ts ignore
  tsconfig.json
Labels: v5

#5839 feat(ScrollArrow): add `up` & `down`
  packages/vkui/src/components/ScrollArrow/ScrollArrow.e2e-playground.tsx
  packages/vkui/src/components/ScrollArrow/ScrollArrow.module.css
  packages/vkui/src/components/ScrollArrow/ScrollArrow.tsx
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-android-chromium-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ScrollArrow/__image_snapshots__/scrollarrow-vkcom-webkit-light-1-snap.png
Labels: v5

#5809 feat: Export useful types from vkui library
  packages/vkui/src/index.ts
Labels: v5

#5844 docs(MiniInfoCell): rm separator
  packages/vkui/src/components/MiniInfoCell/Readme.md
Labels: patch, v5

#5851 fix(PanelHeaderButton): fix preset links
  packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx
  packages/vkui/src/components/PanelHeaderClose/PanelHeaderClose.tsx
  packages/vkui/src/components/PanelHeaderEdit/PanelHeaderEdit.tsx
  packages/vkui/src/components/PanelHeaderSubmit/PanelHeaderSubmit.tsx
Labels: patch, v5

#5802 feat(FormLayoutGroup): segmented vertical
  packages/vkui/src/components/FormField/FormField.module.css
  packages/vkui/src/components/FormItem/FormItem.module.css
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.e2e-playground.tsx
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.module.css
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx
  packages/vkui/src/components/FormLayoutGroup/Readme.md
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-light-1-snap.png
Labels: v5

#5836 fix(WriteBar): icons shift
  packages/vkui/src/components/WriteBar/WriteBar.e2e-playground.tsx
  packages/vkui/src/components/WriteBar/WriteBar.e2e.tsx
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-icons-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-icons-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
Labels: patch, v5

#5864 fix(AspectRatio): children prop passing
  packages/vkui/src/components/AspectRatio/AspectRatio.tsx
Labels: patch, v5

#5843 docs(FixedLayout): PanelHeader fixed
  packages/vkui/src/components/FixedLayout/Readme.md
Labels: docs, patch, v5

#5877 chore: Add prop mapping support for Storybook cartesian
  packages/vkui/src/components/Avatar/Avatar.stories.tsx
  packages/vkui/src/components/GridAvatar/GridAvatar.stories.tsx
  tools/storybook-addon-cartesian/src/withCartesian.tsx
Labels: patch, v5

#5880 Add PanelHeader to HorizontalCellShowMore doc
  packages/vkui/src/components/HorizontalCellShowMore/Readme.md
Labels: patch, v5

#5873 fix(SimpleCell): Get rid of selector complexity to define icon color
  packages/vkui/src/components/CellButton/CellButton.module.css
  packages/vkui/src/components/CellButton/CellButton.tsx
  packages/vkui/src/components/ImageBase/ImageBase.module.css
  packages/vkui/src/components/Removable/Removable.module.css
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
Labels: v5

#5885 fix(Button): Specify correct font-family for the Button in different modes
  packages/vkui/src/components/Button/Button.module.css
Labels: v5

#5884 fix(HorizontalCell): Don't render HorizontalCell__content if it's empty
  packages/vkui/src/components/HorizontalCell/HorizontalCell.test.tsx
  packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx
Labels: v5

#5845 fix(ModalRoot/ModalPage): Fix flacky expanding and scrolling
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: v5

#5889 feat(chore): expand file-filters.yml for storybook
  .github/file-filters.yml
  .github/workflows/pull_request_packages.yml
Labels: v5

#5886 fix(storybook): add dynamicTokens.css file
  packages/vkui/.storybook/preview.ts
Labels: v5

#5804 fix(View): Fix shadow on iOS swipe back
  packages/vkui/src/components/Panel/Panel.tsx
  packages/vkui/src/components/View/View.module.css
  packages/vkui/src/components/View/View.tsx
Labels: v5

#5888 fix(Panel): background color layout=card
  packages/vkui/src/components/Panel/Panel.module.css
  packages/vkui/src/components/Panel/Panel.tsx
Labels: v5
