Repository VKCOM/VKUI, pull requests merged in 2023-02, with the labels that each got.

#4033 fix(Epic): add hasTabbar
  packages/vkui/src/components/Epic/Epic.module.css
  packages/vkui/src/components/Epic/Epic.tsx
  packages/vkui/src/components/FixedLayout/FixedLayout.module.css
  packages/vkui/src/components/Panel/Panel.module.css
  packages/vkui/src/components/Snackbar/Snackbar.module.css
Labels: type:bug, cmp:epic, patch

#4037 fix(Adaptivity): use `not` in media rule
  packages/vkui/shared.config.js
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx
  packages/vkui/src/shared/breakpoints.js
Labels: type:bug, adaptivity, patch

#4082 fix(PanelHeader): android className default
  packages/vkui/src/components/PanelHeader/PanelHeader.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
Labels: type:bug, cmp:panel-header, patch

#4053 fix(Slider): fix behavior for zero `value` and negative `min`
  packages/vkui/src/components/Slider/Slider.e2e.tsx
  packages/vkui/src/components/Slider/Slider.tsx
  packages/vkui/src/components/Slider/__image_snapshots__/slider-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-android-chromium-light-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Slider/__image_snapshots__/slider-vkcom-webkit-light-1-snap.png
Labels: patch

#4052 docs(Select): fix missing Select doc page
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/Select/Select.module.css
  packages/vkui/src/components/Select/Select.tsx
  packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
  packages/vkui/src/components/SelectTypography/SelectTypography.module.css
  packages/vkui/src/components/SelectTypography/SelectTypography.tsx
  packages/vkui/src/styles/components.css
Labels: patch

#4097 [v4] fix(Dropdown): add capture
  src/components/Dropdown/Dropdown.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: patch

#4100 chore(doc): Fix docs minor bugs
  packages/vkui/src/components/Footer/Readme.md
  packages/vkui/src/components/Panel/Readme.md
  packages/vkui/src/components/Popper/Readme.md
  packages/vkui/src/components/Touch/Readme.md
Labels: patch

#4099 fix(CustomSelect): invalid value not call onChange
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch

#4106 fix: fallback css properties
  postcss.config.js
Labels: technical task, patch

#4102 fix(Button): Fix width for single icon buttons
  packages/vkui/src/components/Button/Button.module.css
Labels: patch

#4127 Fix styleguide deploying v4
  .github/workflows/publish.yml
Labels: patch

#4110 chore: replace `IS_DEV` w/ `process.env.NODE_ENV === 'development'`
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
Labels: patch

#4105 fix(Switch): remove role="presentation"
  packages/vkui/src/components/Switch/Switch.tsx
Labels: patch

#4104 fix(DateInput): remove dangerous tabIndex={1}
  packages/vkui/src/components/DateInput/DateInput.tsx
Labels: patch

#4103 fix(Progress): add title
  packages/vkui/src/components/Progress/Progress.tsx
Labels: patch

#4150 fix(Card): outline add `pointer-events: none`
  packages/vkui/src/components/Card/Card.module.css
Labels: patch

#4138 fix(Search): fix padding token
  packages/vkui/src/components/Search/Search.module.css
Labels: patch

#3932 fix Touch click handler after slide
  packages/vkui/src/components/Touch/Touch.test.tsx
  packages/vkui/src/components/Touch/Touch.tsx
Labels: patch, 🔥 fix bounty: persistence boost 🥊

#4155 feat(Tabs): use vkui-tokens for x-gaps
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.module.css
  packages/vkui/src/components/Tabs/Tabs.module.css
  packages/vkui/src/components/Tabs/Tabs.tsx
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/TabsItem/TabsItem.module.css
Labels: patch

#4156 [v4] feat(Tabs): use vkui-tokens for x-gaps
  src/components/HorizontalScroll/HorizontalScroll.css
  src/components/TabsItem/TabsItem.css
Labels: patch

#4108 fix(ActionSheetItem): Fix accent color for item on iOS
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-ios-webkit-dark-w_2-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-ios-webkit-light-w_2-1-snap.png
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
Labels: patch

#4140 feat(Checkbox): provide states props of Tappable
  packages/vkui/src/components/Checkbox/Checkbox.tsx
Labels: patch

#4180 fix: return vkui__root
  packages/vkui/src/components/AppRoot/AppRoot.tsx
  packages/vkui/src/styles/common.css
  styleguide/pages/migration_v5.md
  styleguide/pages/quick_start.md
Labels: patch

#4241 tech(css modules): rm getSizeXClassName()
  packages/vkui/src/components/AppRoot/AppRoot.tsx
  packages/vkui/src/components/CardGrid/CardGrid.tsx
  packages/vkui/src/components/CardScroll/CardScroll.tsx
  packages/vkui/src/components/Group/Group.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/Panel/Panel.tsx
  packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.tsx
  packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
  packages/vkui/src/components/SplitCol/SplitCol.tsx
  packages/vkui/src/helpers/getSizeXClassName.test.ts
  packages/vkui/src/helpers/getSizeXClassName.ts
Labels: patch

#4250 style: use @typescript-eslint/parser
  styleguide/.eslintrc.json
  styleguide/Components/Modals/Platforms.js
  styleguide/Components/Modals/Versions.js
  styleguide/Components/Preview.js
  styleguide/Components/ReactComponent/ReactComponent.js
  styleguide/Components/StyleGuide/StyleGuideDesktop.js
  styleguide/Components/StyleGuide/StyleGuideMobile.js
  styleguide/Components/TableOfContents/TableOfContents.js
Labels: technical task

#4200 chore: Update VKUI logo in README.md
  README.md
  docs/assets/vkui-logo-dark.svg
  docs/assets/vkui-logo-light.svg
  styleguide/assets/static/vkui_logo.png
  styleguide/config.js
Labels: patch

#4249 fix(Adaptivity): using hack-width in media queries
  packages/vkui/shared.config.js
  packages/vkui/src/shared/breakpoints.js
Labels: patch

#4258 Add icon for doc site
  index.html
Labels: docs

#4260 Add favicon into config for gh-pages doc site
  styleguide/config.js
Labels: docs, patch

#4261 refactor: remove null variant from class names maps
  docs/ADAPTIVITY_GUIDE.md
  packages/vkui/src/components/AppRoot/AppRoot.tsx
  packages/vkui/src/components/CardGrid/CardGrid.tsx
  packages/vkui/src/components/Chip/Chip.tsx
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
  packages/vkui/src/components/FormField/FormField.tsx
  packages/vkui/src/components/FormItem/FormItem.tsx
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx
  packages/vkui/src/components/IconButton/IconButton.tsx
  packages/vkui/src/components/Input/Input.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx
  packages/vkui/src/components/Radio/Radio.tsx
  packages/vkui/src/components/RangeSlider/UniversalSlider.tsx
  packages/vkui/src/components/RichCell/RichCell.tsx
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
  packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx
  packages/vkui/src/components/Switch/Switch.tsx
  packages/vkui/src/components/TabsItem/TabsItem.tsx
  packages/vkui/src/components/Textarea/Textarea.tsx
  packages/vkui/src/components/Typography/Headline/Headline.tsx
  packages/vkui/src/components/Typography/Subhead/Subhead.tsx
  packages/vkui/src/components/Typography/Text/Text.tsx
Labels: technical task, patch

#4269 ci(@actions-internal/patch): mv fetch to try catch block
  .github/actions/patch/src/main.ts
Labels: technical task, patch

#4274 tech(css modules): rm unused adaptivity helpers
  docs/ADAPTIVITY_GUIDE.md
  packages/vkui/src/helpers/getHoverClassName.test.ts
  packages/vkui/src/helpers/getHoverClassName.ts
  packages/vkui/src/helpers/getPointerClassName.test.ts
  packages/vkui/src/helpers/getPointerClassName.ts
  packages/vkui/src/helpers/getViewHeightClassName.test.ts
  packages/vkui/src/helpers/getViewHeightClassName.ts
Labels: patch

#4275 tech(css modules): rm getViewWidthClassName()
  docs/ADAPTIVITY_GUIDE.md
  packages/vkui/global.d.ts
  packages/vkui/src/components/SplitCol/SplitCol.tsx
  packages/vkui/src/helpers/getViewWidthClassName.test.ts
  packages/vkui/src/helpers/getViewWidthClassName.ts
Labels: patch

#4276 fix(SegmentedControl): fix animation on initial render
  packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx
Labels: patch

#4287 fix(adaptivity): create viewWidthToClassName()
  docs/ADAPTIVITY_GUIDE.md
  packages/vkui/src/components/SplitCol/SplitCol.module.css
  packages/vkui/src/components/SplitCol/SplitCol.tsx
  packages/vkui/src/lib/adaptivity/constants.ts
  packages/vkui/src/lib/adaptivity/functions.test.ts
  packages/vkui/src/lib/adaptivity/functions.ts
  packages/vkui/src/lib/adaptivity/types.ts
  packages/vkui/src/types.ts
Labels: patch

#4302 docs(migration_v5.md): add info about VK Sans Display
  styleguide/pages/migration_v5.md
Labels: patch

#4303 refactor: remove empty variant from class names maps
  packages/vkui/src/components/ModalPage/ModalPage.tsx
  packages/vkui/src/components/PanelHeader/PanelHeader.tsx
  packages/vkui/src/components/SelectTypography/SelectTypography.tsx
Labels: patch

#4316 fix(Header): add margin Group > Tappable > Header
  packages/vkui/src/components/Header/Header.module.css
Labels: patch

#4317 [v4] fix(Header): add margin Group > Tappable > Header
  src/components/Header/Header.css
Labels: patch

#4136 fix(WriteBar): fix design review notes
  packages/vkui/src/components/Counter/Counter.module.css
  packages/vkui/src/components/WriteBar/Readme.md
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.module.css
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
  packages/vkui/src/components/WriteBarIcon/WriteBarIconRenderer.tsx
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-android-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-android-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-webkit-light-1-snap.png
Labels: patch

#4214 fix(SubnavigationButton): fix design review notes
  packages/vkui/src/components/Counter/Counter.module.css
  packages/vkui/src/components/SubnavigationButton/Readme.md
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-webkit-dark-1-snap.png
Labels: patch

#4315 tech(css modules): deprecate getPlatformClassName()
  docs/TESTING.md
  packages/vkui/src/components/Cell/CellCheckbox/CellCheckbox.tsx
  packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx
  packages/vkui/src/components/File/File.tsx
  packages/vkui/src/components/ModalCard/ModalCard.tsx
  packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
  packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/PanelHeader/PanelHeader.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
  packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.tsx
  packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
  packages/vkui/src/components/SelectTypography/SelectTypography.tsx
  packages/vkui/src/components/SimpleCell/SimpleCell.tsx
  packages/vkui/src/components/Switch/Switch.tsx
  packages/vkui/src/components/View/ViewInfinite.tsx
  packages/vkui/src/helpers/getPlatformClassName.ts
  styleguide/pages/migration_v5.md
  styleguide/pages/utils.md
Labels: patch

#4323 fix(Pagination): a11y use ellipsis
  packages/vkui/src/components/Pagination/Pagination.tsx
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-android-chromium-light-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Pagination/__image_snapshots__/pagination-vkcom-webkit-light-1-snap.png
Labels: patch
