Repository VKCOM/VKUI, pull requests merged in 2023-04, with the labels that each got.

#4644 fix(Select): remove clear button props from NativeSelect
  packages/vkui/src/components/Select/Select.tsx
Labels: type:bug, cmp:select, patch

#4675 fix(UsersStack): add aria-hidden to othersElement
  packages/vkui/src/components/UsersStack/UsersStack.tsx
Labels: type:bug, cmp:users-stack, a11y, patch, a11y:audit

#4671 test(lib/warnOnce): add unit tests
  packages/vkui/src/lib/warnOnce.test.ts
  packages/vkui/src/lib/warnOnce.ts
Labels: technical task, patch

#4689 fix(ModalPage): expandable content-in height: 100%
  packages/vkui/src/components/ModalPage/ModalPage.module.css
Labels: patch

#4670 fix(CustomSelect): callback deps
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch

#4703 fix(ChipsInput): add mode prop
  packages/vkui/src/components/ChipsInput/ChipsInput.tsx
Labels: patch

#4702 fix(Banner, FormStatus): add root ref
  packages/vkui/src/components/Banner/Banner.tsx
  packages/vkui/src/components/FormStatus/FormStatus.tsx
Labels: patch

#4695 types: fixes
  packages/vkui/src/components/ActionSheet/types.ts
  packages/vkui/src/components/Typography/Caption/Caption.tsx
  packages/vkui/src/components/Typography/Footnote/Footnote.tsx
  packages/vkui/src/components/Typography/Headline/Headline.tsx
  packages/vkui/src/components/Typography/Paragraph/Paragraph.tsx
  packages/vkui/src/components/Typography/Subhead/Subhead.tsx
  packages/vkui/src/components/Typography/Text/Text.tsx
  packages/vkui/src/components/Typography/Title/Title.tsx
  packages/vkui/src/components/Typography/types.ts
Labels: types, technical task, patch

#4701 fix(docs:styleguidist): Некостыльный `@deprecated` и другие фиксы для стайлгайда
  styleguide/Components/ReactComponent/ReactComponent.js
  styleguide/Components/Table/TableRenderer.js
  styleguide/Components/TableOfContents/TableOfContents.js
  styleguide/config.js
  styleguide/deprecated.js
  styleguide/utils/index.js
Labels: docs, patch

#4693 chore(PromoBanner): deprecated
  packages/vkui/src/components/PromoBanner/PromoBanner.tsx
Labels: patch

#4755 docs: ConfigProvider appearance from vk-bridge
  styleguide/pages/platforms_and_themes.md
Labels: patch

#4757 fix(WriteBar): fix border token + add e2e tests
  packages/vkui/src/components/WriteBar/WriteBar.e2e.tsx
  packages/vkui/src/components/WriteBar/WriteBar.module.css
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-light-1-snap.png
Labels: patch

#4574 fix(SubnavigationButton): fix aria-label
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.a11y.test.tsx
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx
Labels: type:bug, a11y, cmp:subnavigation-button, a11y:audit

#4736 refactor(Separator, Spacing): fix a11y
  packages/vkui/src/components/Separator/Separator.a11y.test.tsx
  packages/vkui/src/components/Separator/Separator.module.css
  packages/vkui/src/components/Separator/Separator.tsx
  packages/vkui/src/components/Spacing/Spacing.a11y.test.tsx
  packages/vkui/src/components/Spacing/Spacing.tsx
Labels: cmp:spacing, a11y, cmp:separator, patch, a11y:audit

#4849 tech(e2e): change type of PLAYWRIGHT_FORCE_PROJECT env var
  packages/vkui/.env.development.local
  packages/vkui/playwright-ct.config.ts
Labels: technical task

#4852 tech(e2e): add PLAYWRIGHT_WORKERS
  docs/TESTING.md
  packages/vkui/.env.development.local
  packages/vkui/playwright-ct.config.ts
Labels: technical task

#4834 refactor(SimpleCell): rm SimpleCell__typography
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
  packages/vkui/src/components/SimpleCell/SimpleCell.tsx
Labels: cmp:simple-cell

#4855 build(devDeps): update storybook to 7.0.5
  tools/storybook-addon-cartesian/package.json
  yarn.lock
Labels: dependencies, javascript

#4856 types(AdaptivityProvider): update types
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx
Labels: types

#4872 chore(types): use `HasChildren`
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/AppRoot/AppRootPortal.tsx
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
  packages/vkui/src/components/Epic/ScrollSaver.tsx
  packages/vkui/src/components/Group/Group.tsx
  packages/vkui/src/components/IconButton/IconButton.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.stories.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/ModalRoot/ModalRootAdaptive.tsx
  packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
  packages/vkui/src/components/ModalRoot/types.ts
  packages/vkui/src/components/ModalRoot/useModalManager.tsx
  packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
  packages/vkui/src/components/Removable/Removable.tsx
  packages/vkui/src/components/SelectTypography/SelectTypography.tsx
  packages/vkui/src/components/Spacing/Spacing.tsx
  packages/vkui/src/components/Tabs/Tabs.e2e-playground.tsx
  packages/vkui/src/components/Tappable/Tappable.tsx
  packages/vkui/src/components/Typography/Typography.stories.tsx
  packages/vkui/src/index.ts
Labels: types

#4891 tech(playwright): reset mouse pos for every tests
  packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e.tsx
  packages/vkui/src/testing/e2e/index.playwright.ts
Labels: technical task

#4838 refactor(Typography): add Typography
  packages/vkui/src/components/Typography/Caption/Caption.module.css
  packages/vkui/src/components/Typography/Caption/Caption.tsx
  packages/vkui/src/components/Typography/Footnote/Footnote.module.css
  packages/vkui/src/components/Typography/Footnote/Footnote.tsx
  packages/vkui/src/components/Typography/Headline/Headline.module.css
  packages/vkui/src/components/Typography/Headline/Headline.tsx
  packages/vkui/src/components/Typography/Paragraph/Paragraph.module.css
  packages/vkui/src/components/Typography/Paragraph/Paragraph.tsx
  packages/vkui/src/components/Typography/Subhead/Subhead.module.css
  packages/vkui/src/components/Typography/Subhead/Subhead.tsx
  packages/vkui/src/components/Typography/Text/Text.module.css
  packages/vkui/src/components/Typography/Text/Text.tsx
  packages/vkui/src/components/Typography/Title/Title.module.css
  packages/vkui/src/components/Typography/Title/Title.tsx
  packages/vkui/src/components/Typography/Typography.module.css
  packages/vkui/src/components/Typography/Typography.tsx
  packages/vkui/src/components/Typography/types.ts
Labels: type:feature, cmp:typography

#4871 feat(Header): address design review notes
  packages/vkui/src/components/Header/Header.module.css
  packages/vkui/src/components/Header/Header.tsx
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Link/Link.module.css
Labels: patch

#4897 fix(ModalPage): bottom safe area
  packages/vkui/src/components/ModalPage/ModalPage.module.css
Labels: type:bug, cmp:modal-page, patch

#4920 fix(@actions-internal/patch): rm `--depth=1` flag
  .github/actions/patch/src/main.ts
Labels: type:bug, technical task

#4933 build(deps-dep): bump stylelint to v15
  package.json
  stylelint.config.js
  yarn.lock
Labels: dependencies

#4927 build(deps-dev): Bump storybook to 7.0.7
  tools/storybook-addon-cartesian/package.json
  yarn.lock
Labels: dependencies

#4903 fix(RichCell): add word-break
  packages/vkui/src/components/RichCell/RichCell.module.css
Labels: patch

#4905 fix(Button): rm --android
  packages/vkui/src/components/Button/Button.module.css
  packages/vkui/src/components/Button/Button.tsx
Labels: type:bug, cmp:button, patch
