Repository VKCOM/VKUI, pull requests merged in 2023-08, with the labels that each got.

#5555 fix(PopoutWrapper): add position
  packages/vkui/src/components/ActionSheet/ActionSheet.module.css
  packages/vkui/src/components/ModalDismissButton/Readme.md
  packages/vkui/src/components/PopoutWrapper/PopoutWrapper.module.css
  packages/vkui/src/components/Popover/Popover.module.css
  packages/vkui/src/components/Popover/Popover.tsx
Labels: type:bug, cmp:popover, cmp:popout-wrapper

#5563 tech(dependabot): ignore react 18.x
  .github/dependabot.yml
Labels: dependencies, technical task, javascript

#5573 chore: fix dependabot ignore version type
  .github/dependabot.yml
Labels: type:bug

#5586 tech(dependabot): freeze @testing-library/react
  .github/dependabot.yml
Labels: dependencies, technical task

#5592 docs(migration_v5): rm info about vkui__root
  styleguide/pages/migration_v5.md
Labels: docs, patch, cmp:app-root

#5595 fix(HorizontalScroll): Show arrows on hover even though element is memorized
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
Labels: patch

#5607 feat(Input): disable controls for type="number"
  packages/vkui/src/components/Input/Input.module.css
Labels: type:enhancement, cmp:input

#5605 fix(PanelHeader): add z-index for visor={false}
  packages/vkui/src/components/PanelHeader/PanelHeader.module.css
  packages/vkui/src/styles/constants.css
Labels: patch

#5606 fix(useIsClient): use useIsomorphicLayoutEffect
  packages/vkui/src/hooks/useIsClient.ts
Labels: patch

#5623 fix(Group): Show only separator--separator (not space) in the separator force mode
  packages/vkui/src/components/Group/Group.tsx
Labels: patch

#5602 fix(Avatar/BaseImage): Dispatch load img event if resource is already loaded but onload was not fired
  packages/vkui/src/components/ImageBase/ImageBase.test.tsx
  packages/vkui/src/components/ImageBase/ImageBase.tsx
Labels: patch

#5626 ci(pr_close): add workflow_dispatch
  .github/workflows/pr_close.yml
Labels: technical task

#5638 ci(pull_request_dependabot): add write permissions
  .github/workflows/pull_request_dependabot.yml
Labels: technical task, github_actions

#5664 ci: use always() for test_e2e_prepare_report job
  .github/workflows/pull_request_packages.yml
Labels: type:bug, technical task

#5667 fix: Do not use classNames with one argument
  packages/vkui/.eslintrc.js
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx
Labels: technical task

#5662 fix(useFocusWithin): check autofocus
  packages/vkui/src/hooks/useFocusWithin.test.tsx
  packages/vkui/src/hooks/useFocusWithin.ts
Labels: patch

#5665 fix(SelectMimicry): useAutoFocus
  packages/vkui/src/components/SelectMimicry/SelectMimicry.tsx
  packages/vkui/src/hooks/useAutoFocus.test.tsx
  packages/vkui/src/hooks/useAutoFocus.ts
Labels: type:bug, cmp:select-mimicry, patch

#5637 fix(Banner): use Icon24Dismiss for iOS; use color secondary for icons
  packages/vkui/src/components/Banner/Banner.module.css
  packages/vkui/src/components/Banner/Banner.tsx
  packages/vkui/src/components/Banner/__image_snapshots__/banner-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-android-chromium-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Banner/__image_snapshots__/banner-vkcom-webkit-light-1-snap.png
Labels: type:bug, cmp:banner, patch

#5671 ci(pull_request_dependabot): use GITHUB_TOKEN
  .github/workflows/pull_request_dependabot.yml
Labels: type:bug, technical task, github_actions

#5641 fix(ActionSheet/SplitLayout): Make PopoutRoot fixed on desktop
  packages/vkui/src/components/PopoutRoot/PopoutRoot.module.css
  packages/vkui/src/components/PopoutRoot/PopoutRoot.tsx
Labels: patch

#5668 fix(useAdaptivityHasHover): two pass rendering
  packages/vkui/src/hooks/useAdaptivityHasHover.test.tsx
  packages/vkui/src/hooks/useAdaptivityHasHover.ts
  packages/vkui/src/hooks/useAdaptivityHasPointer.ts
Labels: type:bug, adaptivity, patch

#5672 fix(Image): correct borderRadius conditions
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/Image.tsx
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png
Labels: type:bug, patch, cmp:image

#5684 fix(ChipsSelect): Use showSelected prop
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/hooks/useChipsSelect.ts
Labels: patch

#5696 fix(MiniInfoCell): check before
  packages/vkui/src/components/MiniInfoCell/MiniInfoCell.e2e-playground.tsx
  packages/vkui/src/components/MiniInfoCell/MiniInfoCell.tsx
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-chromium-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-webkit-light-1-snap.png
Labels: cmp:mini-info-cell, patch

#5631 fix(ci): create new workflow for report CI results
  .github/workflows/branch_test_coverage.yml
  .github/workflows/pr_close.yml
  .github/workflows/pr_close_undeploy.yml
  .github/workflows/pull_request_common.yml
  .github/workflows/pull_request_packages.yml
  .github/workflows/pull_request_packages_deploy.yml
  .github/workflows/reusable_workflow_pr_worfklow_payload.yml
  .github/workflows/reusable_workflow_test.yml
Labels: technical task, github_actions

#5695 fix(ChipsInputBase): use typography styles by design
  packages/vkui/src/components/Chip/Chip.module.css
  packages/vkui/src/components/Chip/Chip.tsx
  packages/vkui/src/components/Chip/__image_snapshots__/chip-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Chip/__image_snapshots__/chip-android-chromium-light-1-snap.png
  packages/vkui/src/components/Chip/__image_snapshots__/chip-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Chip/__image_snapshots__/chip-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-android-chromium-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.module.css
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-light-1-snap.png
Labels: type:bug, cmp:chips-input
