Repository VKCOM/VKUI, pull requests merged in 2023-07, with the labels that each got.

#5398 fix(docs): refactor styleguide layout
  styleguide/Components/Heading/Heading.css
  styleguide/Components/StyleGuide/StyleGuideDesktop.css
  styleguide/Components/StyleGuide/StyleGuideDesktop.js
  styleguide/Components/StyleGuide/StyleGuideHeader.css
  styleguide/Components/StyleGuide/StyleGuideRenderer.css
Labels: type:bug, docs

#5408 fix(ci): set working dir to schedule cargo update
  .github/workflows/schedule_cargo_update.yml
Labels: type:bug, dependencies, github_actions, rust

#5407 build(deps): cargo update
  tools/swc-transform-css-modules/Cargo.lock
Labels: dependencies, rust

#5399 feat(dependabot): add group updates for npm
  .github/actions/complete_playwright_update/action.yml
  .github/actions/complete_storybook_update/action.yml
  .github/dependabot.yml
  .github/workflows/pull_request_dependabot.yml
Labels: type:feature, technical task, github_actions

#5415 ci(pr_dependabot): use correct branch ref
  .github/workflows/pull_request_dependabot.yml
Labels: type:bug, github_actions

#5416 fix(Tappable): reset outline
  packages/vkui/src/components/Tappable/Tappable.module.css
Labels: patch

#5426 tech: generate customMedias.generated.css once
  docs/CONTRIBUTING.md
  packages/vkui/cssm/postcss.config.js
  packages/vkui/package.json
  packages/vkui/scripts/generateCSSCustomMedias.js
  packages/vkui/shared.config.js
  packages/vkui/src/styles/customMedias.generated.css
  packages/vkui/tsconfig.json
  postcss.config.js
  shared.js
  stylelint.config.js
Labels: technical task

#5402 Fix modal height
  packages/vkui/src/components/ModalPage/ModalPage.module.css
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: patch

#5427 ci: check if the generated files have been updated
  .github/workflows/pull_request_packages.yml
  package.json
  packages/vkui/package.json
Labels: technical task

#5435 Cargo update
  tools/swc-transform-css-modules/Cargo.lock
Labels: dependencies, rust

#5397 fix(ModalCardBase): Subhead regular
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
Labels: type:bug, cmp:modal-card, cmp:modal-card-base, pr-needs-work

#5424 fix(docs): edit header and desktop layout
  styleguide/Components/Heading/Heading.css
  styleguide/Components/Logo/Logo.js
  styleguide/Components/StyleGuide/StyleGuideDesktop.js
  styleguide/Components/StyleGuide/StyleGuideHeader.css
  styleguide/Components/StyleGuide/StyleGuideHeader.js
  styleguide/Components/StyleGuide/StyleGuideRenderer.css
Labels: type:bug, docs

#5329 feat(SimpleCell): update chevron
  packages/vkui/src/components/SimpleCell/Chevron/Chevron.tsx
  packages/vkui/src/components/SimpleCell/SimpleCell.e2e-playground.tsx
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
  packages/vkui/src/components/SimpleCell/SimpleCell.tsx
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:simple-cell

#5422 fix(FormItem): add `aria-labelledby` support for `bottom` + `Input`
  packages/vkui/src/components/FormItem/FormItem.tsx
  packages/vkui/src/components/FormItem/Readme.md
Labels: type:bug, cmp:form-item, a11y, patch

#5284 fix(Math.ts): updated `decimatedClamp` implementation
  packages/vkui/src/helpers/math.test.ts
  packages/vkui/src/helpers/math.ts
Labels: patch

#5455 feat(Progress): add height
  packages/vkui/src/components/Progress/Progress.e2e-playground.tsx
  packages/vkui/src/components/Progress/Progress.test.tsx
  packages/vkui/src/components/Progress/Progress.tsx
  packages/vkui/src/components/Progress/__image_snapshots__/progress-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-android-chromium-light-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Progress/__image_snapshots__/progress-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:progress

#5465 fix(Switch): user-select: none;
  packages/vkui/src/components/Switch/Switch.module.css
Labels: patch

#5460 Remove onCancel call from Search
  packages/vkui/src/components/Search/Search.tsx
Labels: cmp:search, patch

#5225 fix(SubnavigationBar): combining buttons into a list [a11y]
  packages/vkui/src/components/SubnavigationBar/SubnavigationBar.module.css
  packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css
Labels: patch

#5474 feat(doc-epic): move active story styles to object
  packages/vkui/src/components/Epic/Readme.md
Labels: patch

#5470 fix(Search): input width stretch
  packages/vkui/src/components/Search/Search.e2e-playground.tsx
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-light-1-snap.png
Labels: patch

#5491 ci: fix playwright Docker container update
  .github/actions/complete_playwright_update/action.yml
Labels: type:bug

#5400 fix(Alert): remove duplicate ids
  packages/vkui/src/components/Alert/Alert.tsx
Labels: a11y, patch

#5490 Fix search placeholder
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tooltip/__image_snapshots__/tooltip-vkcom-webkit-light-1-snap.png
Labels: type:bug, cmp:search, patch

#5462 refactoring(Tooltip): Move appearance logic of Tooltip to TooltipBase component
  packages/vkui/src/components/PopperArrow/PopperArrow.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/components/TooltipBase/Readme.md
  packages/vkui/src/components/TooltipBase/TooltipBase.module.css
  packages/vkui/src/components/TooltipBase/TooltipBase.tsx
Labels: type:enhancement, cmp:tooltip

#5502 feat(ActionSheet): add default iOS close item
  packages/vkui/src/components/ActionSheet/ActionSheet.e2e-playground.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.stories.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.tsx
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
Labels: cmp:action-sheet

#5523 docs(styleguide): fix configuration
  styleguide/Components/Section/SectionRenderer.js
  styleguide/Components/Section/index.js
Labels: type:bug, docs

#5522 feat(Search): add noPadding
  packages/vkui/src/components/Search/Search.e2e-playground.tsx
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-android-chromium-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:search

#5519 fix(Link): line-height inherit
  packages/vkui/src/components/Link/Link.module.css
Labels: type:bug, cmp:link, patch

#5539 fix(NativeSelect): apply selectType to FormField
  packages/vkui/src/components/NativeSelect/NativeSelect.e2e-playground.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-android-chromium-dark-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-android-chromium-light-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-ios-webkit-light-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/NativeSelect/__image_snapshots__/nativeselect-vkcom-webkit-light-1-snap.png
Labels: type:bug, cmp:native-select

#5532 fix(Button): Fix counter bg color in buttons
  packages/vkui/src/components/Button/Button.e2e-playground.tsx
  packages/vkui/src/components/Button/Button.e2e.tsx
  packages/vkui/src/components/Button/Button.module.css
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-android-chromium-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-counter-vkcom-webkit-light-1-snap.png
Labels: type:bug, cmp:counter, cmp:button
