Repository VKCOM/VKUI, pull requests merged in 2023-10, with the labels that each got.

#5902 fix(Link): add font-weight: inherit
  packages/vkui/src/components/Link/Link.module.css
Labels: cmp:link, v5

#5890 Remove overflow-x: hidden from body
  packages/vkui/src/styles/common.css
Labels: type:bug, v5

#5744 feat(Carousel): add Gallery with loop
  packages/vkui/src/components/BaseGallery/CarouselBase/CarouselBase.tsx
  packages/vkui/src/components/BaseGallery/CarouselBase/constants.ts
  packages/vkui/src/components/BaseGallery/CarouselBase/helpers.ts
  packages/vkui/src/components/BaseGallery/CarouselBase/hooks.ts
  packages/vkui/src/components/BaseGallery/CarouselBase/types.ts
  packages/vkui/src/components/Gallery/Gallery.tsx
  packages/vkui/src/components/Gallery/Readme.md
  packages/vkui/src/lib/animate.ts
  packages/vkui/src/lib/fx.ts
Labels: v5

#5906 fix(Group): plain header margin
  packages/vkui/src/components/Group/Group.module.css
Labels: patch, v5

#5905 feat: add vkui-floating-ui-react-dom
  .github/workflows/publish_vkui_floating_ui_react_dom.yml
  packages/vkui-floating-ui-react-dom/LICENSE
  packages/vkui-floating-ui-react-dom/README.md
  packages/vkui-floating-ui-react-dom/index.mjs
  packages/vkui-floating-ui-react-dom/package.json
  packages/vkui-floating-ui-react-dom/types.d.ts
  yarn.lock
Labels: v5

#5916 fix: change getRootRefTest check for null
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/AppRoot/AppRoot.test.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx
  packages/vkui/src/components/CustomScrollView/CustomScrollView.test.tsx
  packages/vkui/src/components/CustomScrollView/CustomScrollView.tsx
  packages/vkui/src/components/FormLayout/FormLayout.tsx
  packages/vkui/src/components/LocaleProvider/LocaleProvider.test.tsx
  packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/Tooltip/Tooltip.test.tsx
  packages/vkui/src/components/VisuallyHiddenInput/VisuallyHiddenInput.tsx
  packages/vkui/src/testing/utils.tsx
Labels: patch, v5

#5913 fix(lib/floating): Use compatible with old browsers version of floating-ui/react-dom using @vkontakte/floating-ui-react-dom
  .yarnrc.yml
  package.json
  packages/vkui/package.json
  packages/vkui/src/lib/floating/adapters.ts
  packages/vkui/src/lib/floating/index.ts
  packages/vkui/src/lib/floating/types.ts
  yarn.lock
Labels: patch, v5

#5923 feat(Avatar): export getInitialsFontSize
  packages/vkui/src/components/Avatar/Avatar.tsx
Labels: v5

#5926 ci(pr_template): add documentation
  .github/pull_request_template.md
Labels: v5

#5924 feature(BaseImage): Add prop to turn on transparent background
  packages/vkui/src/components/Image/Image.e2e-playground.tsx
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ImageBase/ImageBase.module.css
  packages/vkui/src/components/ImageBase/ImageBase.tsx
Labels: v5

#5930 build(deps-dev): Bump @vkontakte/vkui-tokens from 4.40.0 to 4.41.0
  package.json
  yarn.lock
Labels: v5

#5942 fix(vkui-floating-ui-react-dom): regex quotes
  packages/vkui-floating-ui-react-dom/index.mjs
Labels: patch, v5

#5944 fix(Snackbar): set size_card_border_radius
  packages/vkui/src/components/Snackbar/Snackbar.module.css
Labels: patch, v5

#5920 fix(ModalPage): Fix scrolling behaviour in the collapsed state of ModalPage
  packages/vkui/src/components/ModalPage/ModalPage.module.css
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: patch, v5

#5919 fix(Button): after/before padding for stretched
  packages/vkui/src/components/Button/Button.e2e-playground.tsx
  packages/vkui/src/components/Button/Button.e2e.tsx
  packages/vkui/src/components/Button/Button.module.css
  packages/vkui/src/components/Button/__image_snapshots__/button-paddings-android-chromium-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-paddings-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-paddings-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-paddings-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Button/__image_snapshots__/button-paddings-vkcom-webkit-light-1-snap.png
Labels: patch, v5

#5950 fix(CustomSelect): CustomSelectRenderOption
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch, v5

#5682 feat(Image): width & height
  packages/vkui/src/components/Avatar/Avatar.tsx
  packages/vkui/src/components/Image/Image.e2e-playground.tsx
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/components/ImageBase/helpers.ts
  packages/vkui/src/lib/comparing.test.ts
  packages/vkui/src/lib/comparing.ts
Labels: v5

#5948 fix(CustomSelectOption): wrap text
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.module.css
  packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-android-chromium-dark-1-snap.png
  packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-android-chromium-light-1-snap.png
  packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/CustomSelectOption/__image_snapshots__/customselectoption-ios-webkit-light-1-snap.png
Labels: patch, v5

#5953 ci(pr): add labels
  .github/workflows/pull_request_common.yml
Labels: v5

#5954 fix(Gallery): timeout inactive tab issue
  packages/vkui/src/components/Gallery/Gallery.tsx
  packages/vkui/src/components/Gallery/hooks.ts
Labels: patch, v5

#5956 fix: vkui-floating-ui-react-dom caret version
  packages/vkui/package.json
  yarn.lock
Labels: patch, v5

#5958 refactor: mv vkui-floating-ui-react-dom to vkui-floating-ui
  .github/workflows/publish_vkui_floating_ui_react_dom.yml
  .prettierignore
  packages/vkui-floating-ui-react-dom/README.md
  packages/vkui-floating-ui-react-dom/index.mjs
  packages/vkui-floating-ui-react-dom/package.json
  packages/vkui-floating-ui-react-dom/types.d.ts
  packages/vkui-floating-ui/.gitignore
  packages/vkui-floating-ui/LICENSE
  packages/vkui-floating-ui/README.md
  packages/vkui-floating-ui/index.mjs
  packages/vkui-floating-ui/package.json
  packages/vkui/package.json
  packages/vkui/src/lib/floating/adapters.ts
  packages/vkui/src/lib/floating/index.ts
  packages/vkui/src/lib/floating/types.ts
  yarn.lock
Labels: type:feature, technical task, patch, v5

#5963 tech(workflow/deprecate): add package_name input
  .github/workflows/deprecate.yml
  .github/workflows/unpublish.yml
Labels: technical task

#5965 tech: remove .github/workflows/unpublish.yml
  .github/workflows/unpublish.yml
Labels: technical task

#5959 feat(SegmentedControl): add before
  packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e-playground.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControl.module.css
  packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.module.css
  packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-chromium-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:segmented-control, v5

#5969 feat(HorizontalScroll): disable scroll arrows for screen readers
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
Labels: patch, v5

#5968 docs(typography): add description
  packages/vkui/src/components/Typography/Caption/Caption.tsx
  packages/vkui/src/components/Typography/Footnote/Footnote.tsx
  packages/vkui/src/components/Typography/Headline/Headline.tsx
  packages/vkui/src/components/Typography/Paragraph/Paragraph.tsx
  packages/vkui/src/components/Typography/Subhead/Subhead.tsx
  packages/vkui/src/components/Typography/Text/Text.tsx
  packages/vkui/src/components/Typography/Title/Readme.md
  packages/vkui/src/components/Typography/Title/Title.tsx
Labels: patch, v5

#5966 fix(ActionSheet): rm header
  packages/vkui/src/components/ActionSheet/ActionSheet.tsx
Labels: patch, v5

#5973 fix(CustomSelectRenderOption): option is request
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: patch, v5

#5994 patch: pr5981
  package.json
  yarn.lock
Labels: v5

#5993 patch: pr5982
  package.json
  yarn.lock
Labels: v5

#5977 chore(e2e): fix tests wrapper
  packages/vkui/src/components/ActionSheet/ActionSheet.e2e-playground.tsx
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Alert/Alert.e2e-playground.tsx
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-android-chromium-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-mobile-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/ModalCard.e2e-playground.tsx
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Panel/Panel.e2e-playground.tsx
  packages/vkui/src/components/Panel/__image_snapshots__/panel-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-android-chromium-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Panel/__image_snapshots__/panel-vkcom-webkit-light-1-snap.png
  packages/vkui/src/testing/e2e/index.playground.ts
Labels: v5

#5995 ci(labels): ignore patch
  .github/workflows/pull_request_common.yml
Labels: patch, v5

#5996 Header a11y
  packages/vkui/src/components/Header/Header.test.tsx
  packages/vkui/src/components/Header/Header.tsx
Labels: patch, v5

#5957 feat(Tabs): Allow to scroll to selected tab
  packages/vkui/src/components/Tabs/Readme.md
  packages/vkui/src/components/Tabs/Tabs.stories.tsx
  packages/vkui/src/components/Tabs/Tabs.tsx
  packages/vkui/src/components/TabsItem/TabsItem.tsx
Labels: v5

#6001 patch: pr5996
  packages/vkui/src/components/Header/Header.test.tsx
  packages/vkui/src/components/Header/Header.tsx
Labels: patch

#6000 fix(Alert): add word-break
  packages/vkui/src/components/Alert/Alert.e2e-playground.tsx
  packages/vkui/src/components/Alert/Alert.e2e.tsx
  packages/vkui/src/components/Alert/Alert.module.css
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-android-chromium-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-webkit-light-1-snap.png
Labels: patch, v5

#5967 fix(PullToRefresh): Detect pull to refresh gesture in the document's touchmove
  packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
Labels: patch, v5

#5974 chore: add stable branch screenshots
  .github/workflows/branch_test_coverage.yml
  .github/workflows/update_screens.yml
Labels: v5

#6005 chore: Add deps deduplication
  .github/workflows/dedupe_deps.yml
Labels: v5

#5827 feat(Gradient): add new default mode
  packages/vkui/src/components/Gradient/Gradient.e2e-playground.tsx
  packages/vkui/src/components/Gradient/Gradient.e2e.tsx
  packages/vkui/src/components/Gradient/Gradient.module.css
  packages/vkui/src/components/Gradient/Gradient.tsx
  packages/vkui/src/components/Gradient/Readme.md
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-light-1-snap.png
Labels: v5

#6009 fix: rm useAdaptivityHasHover
  packages/vkui/src/components/Tappable/Tappable.tsx
  packages/vkui/src/hooks/useAdaptivityHasHover.test.tsx
  packages/vkui/src/hooks/useAdaptivityHasHover.ts
Labels: patch, v5

#6004 fix(ModalRoot/ModalPage/PullToRefresh): Disable native pull-to-refresh
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
  packages/vkui/src/styles/common.css
Labels: patch, v5

#6028 bump: update transitive deps
  package.json
  yarn.lock
Labels: v5

#6030 fix(build): rm single quote from floating-ui regex
  packages/vkui-floating-ui/index.mjs
Labels: type:bug, technical task, patch, v5

#6036 tech: provide custom port to storybook dev server
  packages/vkui/.env.development.local
  packages/vkui/package.json
Labels: technical task

#6039 docs: Touch add touch-action: none
  packages/vkui/src/components/Touch/Readme.md
Labels: patch, v5

#6044 fix(ConfigProvider): exclude prop with undefined value
  packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx
  packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx
  packages/vkui/src/lib/utils.test.ts
  packages/vkui/src/lib/utils.ts
Labels: type:bug, patch, v5

#6037 feat(Radio): Allow to pass data-* attributes to label element
  packages/vkui/src/components/Radio/Radio.test.tsx
  packages/vkui/src/components/Radio/Radio.tsx
Labels: v5

#6052 feat(ModalRoot): add modalOverlayTestId
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
  packages/vkui/src/components/ModalRoot/types.ts
Labels: type:feature, cmp:modal, v5

#6053 docs: fix default layout for examples
  styleguide/Components/Playground/PlaygroundRenderer.js
  styleguide/Components/Preview.js
Labels: patch, v5

#6051 feat(modal): add modalDismissButtonTestId
  packages/vkui/src/components/ModalCard/ModalCard.test.tsx
  packages/vkui/src/components/ModalCard/ModalCard.tsx
  packages/vkui/src/components/ModalCardBase/ModalCardBase.tsx
  packages/vkui/src/components/ModalPage/ModalPage.test.tsx
  packages/vkui/src/components/ModalPage/ModalPage.tsx
Labels: type:feature, cmp:modal, v5

#6045 feat(CustomSelect,ChipsSelect): add noMaxHeight prop
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.e2e-playground.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.e2e.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-android-chromium-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-ios-webkit-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-no-max-height-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.module.css
  packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
Labels: v5

#5932 feat(Snackbar): Basic
  packages/vkui/src/components/Snackbar/Readme.md
  packages/vkui/src/components/Snackbar/Snackbar.module.css
  packages/vkui/src/components/Snackbar/Snackbar.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.e2e-playground.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.e2e.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.module.css
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.stories.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.test.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-android-chromium-light-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/__image_snapshots__/snackbarbasic-vkcom-webkit-light-1-snap.png
Labels: pr-needs-work, v5

#6067 ci: use node v20
  .github/workflows/dedupe_deps.yml
  .github/workflows/deprecate.yml
  .github/workflows/pr_close.yml
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
  .github/workflows/publish_token_translator.yml
  .github/workflows/publish_vkui_floating_ui_react_dom.yml
  .github/workflows/pull_request_common.yml
  .github/workflows/pull_request_dependabot.yml
  .github/workflows/pull_request_packages.yml
  .github/workflows/reusable_workflow_test.yml
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
Labels: v5
