Repository VKCOM/VKUI, pull requests merged in 2024-03, with the labels that each got.

#6658 docs(storybook): add Source tab
  packages/vkui/.storybook/addons/source-tab/SourceTab.tsx
  packages/vkui/.storybook/addons/source-tab/constants.ts
  packages/vkui/.storybook/addons/source-tab/register.tsx
  packages/vkui/.storybook/main.ts
  packages/vkui/.storybook/preview.ts
  packages/vkui/src/components/Accordion/Accordion.tsx
  packages/vkui/src/components/Accordion/AccordionContent.tsx
  packages/vkui/src/components/Accordion/AccordionSummary.tsx
  packages/vkui/src/components/Avatar/Avatar.tsx
  packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadge.tsx
  packages/vkui/src/components/Avatar/AvatarBadge/AvatarBadgeWithPreset.tsx
  packages/vkui/src/components/Image/Image.tsx
  packages/vkui/src/components/Image/ImageBadge/ImageBadge.tsx
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.tsx
  packages/vkui/src/components/ImageBase/ImageBaseOverlay/ImageBaseOverlay.tsx
Labels: docs, technical task

#6663 fix(NativeSelect): Don't pass unused props to NativeSelect
  packages/vkui/src/components/Select/Select.tsx
Labels: patch, cmp:native-select

#6664 fix(CalendarRange): onChange value is not undefined
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
Labels: patch

#6665 fix(CalendarRange): onChange value is not undefined (v5)
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
Labels: patch

#6675 fix(Banner): fix nesting issue
  packages/vkui/src/components/Banner/Banner.tsx
Labels: patch

#6667 Feat(Select, DatePicker): add type to catch unsupported props
  packages/vkui/src/components/DatePicker/DatePicker.tsx
  packages/vkui/src/components/Select/Select.tsx
  packages/vkui/src/types.ts
Labels: patch

#6666 patch(v5): pr6663
  packages/vkui/src/components/DatePicker/DatePicker.tsx
  packages/vkui/src/components/Select/Select.tsx
  packages/vkui/src/types.ts
Labels: patch

#6685 docs(storybook): revert expanded prop for controls addon
  packages/vkui/.storybook/preview.ts
Labels: type:bug, docs, technical task

#6687 fix(HorizontalScroll): disable navigation to arrow by keyboard
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
Labels: patch

#6681 fix(FocusTrap): preventDefault on Escape
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
Labels: patch

#6689 docs: rm declarations & parent from props
  styleguide/Components/Table/TableRenderer.js
  styleguide/propsParser.config.js
Labels: patch

#6690 docs: rm profiling
  styleguide/Components/Preview.js
  styleguide/setup.js
  styleguide/utils/index.js
  styleguide/webpack.config.js
Labels: patch

#6693 docs(CustomSelectOption): add withListBox
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.stories.tsx
Labels: patch

#6691 docs: don't mount icons on start
  styleguide/Components/Frame/Frame.js
  styleguide/setup.js
Labels: patch

#6694 fix(CustomSelectOption): add nbsp
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
Labels: type:bug, cmp:custom-select-option, a11y, patch

#6696 fix(File): add empty title
  packages/vkui/src/components/File/File.tsx
Labels: patch

#6698 docs(Tappable): change inscription
  packages/vkui/src/components/Tappable/Tappable.stories.tsx
Labels: patch

#6697 docs: Button with icon add label
  packages/vkui/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/vkui/src/components/ButtonGroup/Readme.md
  packages/vkui/src/components/Popover/Readme.md
Labels: patch

#6701 fix(FormStatus): add role=status or alert
  packages/vkui/src/components/FormStatus/FormStatus.tsx
Labels: patch

#6712 fix(Pagination): resolve hover/active state for current page
  packages/vkui/src/components/Pagination/PaginationPage/PaginationPageButton.tsx
Labels: patch

#6714 fix(docs): trim search input
  styleguide/Components/TableOfContents/TableOfContents.js
Labels: docs, patch

#6703 docs: add dir and writing mode
  packages/vkui/.storybook/preview.ts
  packages/vkui/scripts/postcss.js
  packages/vkui/src/components/AppRoot/AppRoot.module.css
  packages/vkui/src/storybook/VKUIDecorators.tsx
Labels: docs, patch

#6717 tech(deps): get playwright docker image version dynamically
  .github/actions/complete_playwright_update/action.yml
  .github/actions/get-playwright-docker-image/action.yml
  .github/workflows/pull_request_dependabot.yml
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
  .gitignore
  packages/vkui/.env.docker
  packages/vkui/docker-compose.yml
  packages/vkui/package.json
  packages/vkui/scripts/generate_env_docker.sh
Labels: dependencies, technical task

#6723 fix(PullToRefresh): Prevent multiple calls of runRefreshing on iOS
  packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
Labels: patch

#6724 fix(Search): correct side margins of `after` element on iOS
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-ios-webkit-light-1-snap.png
Labels: patch

#6753 fix(FormItem): sync margin with design system value
  packages/vkui/src/components/FormItem/FormItem.module.css
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-android-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormLayoutGroup/__image_snapshots__/formlayoutgroup-vkcom-webkit-light-1-snap.png
Labels: patch

#6736 feat(Panel): Allow to use gradient in Panel background
  packages/vkui/src/components/Panel/Panel.module.css
Labels: patch

#6754 build(deps): Bump@vkontakte/icons from 2.62.0 to 2.104.1
  packages/vkui/package.json
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-android-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-android-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBarIcon/__image_snapshots__/writebaricon-vkcom-webkit-light-1-snap.png
  yarn.lock
Labels: dependencies

#6751 build(deps-dev): Bump webpack-dev-middleware from 6.1.1 to 6.1.2
  yarn.lock
Labels: dependencies

#6726 fix(ModalPageHeader): Широкий сепаратор в режиме regular
  packages/vkui/src/components/ModalPageHeader/ModalPageHeader.tsx
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-mobile-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-mobile-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-mobile-ios-only-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalPageHeader/__image_snapshots__/modalpageheader-viewwidth-mobile-ios-only-ios-webkit-light-1-snap.png
Labels: patch

#6731 feat(Snackbar): Let layout prop to take priority
  packages/vkui/src/components/Snackbar/Snackbar.test.tsx
  packages/vkui/src/components/Snackbar/Snackbar.tsx
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
Labels: patch

#6768 fix: revert #6664
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
  packages/vkui/src/hooks/useDateInput.ts
Labels: patch

#6725 feat(Popover): support arrow
  packages/vkui/src/components/Popover/Popover.module.css
  packages/vkui/src/components/Popover/Popover.test.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/index.ts
Labels: pr-needs-work

#6771 fix(HorizontalCell): replace break-all with break-word
  packages/vkui/src/components/HorizontalCell/HorizontalCell.e2e-playground.tsx
  packages/vkui/src/components/HorizontalCell/HorizontalCell.e2e.tsx
  packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-android-chromium-light-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/HorizontalCell/__image_snapshots__/horizontalcell-vkcom-webkit-light-1-snap.png
Labels: patch
