Repository VKCOM/VKUI, pull requests merged in 2024-07, with the labels that each got.

#7010 docs: add maintainers guide
  docs/MAINTAINERS.md
Labels: pr-needs-work

#7120 docs(Snackbar): swipe
  packages/vkui/src/components/Snackbar/Readme.md
Labels: docs, cmp:snackbar, patch

#7090 fix(Typography): add color style token
  packages/vkui/src/lib/tokens/TokensClassProvider.module.css
  packages/vkui/src/lib/tokens/TokensClassProvider.tsx
Labels: patch

#7082 fix(ModalDismissButton): fix hover & active state
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-desktop-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Alert/__image_snapshots__/alert-long-word-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.e2e-playground.tsx
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.e2e.tsx
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.module.css
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-webkit-light-1-snap.png
Labels: patch

#7126 fix(CustomSelect): focus index
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: type:bug, cmp:custom-select, patch

#7098 fix(ChipsSelect/ChipsInput): Pass option disabled and readonly to renderChip
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx
  packages/vkui/src/components/ChipsInputBase/constants.tsx
Labels: cmp:chips-select, cmp:chips-input, patch

#7099 fix(useCustomEnsuredControl/useFloatingWithInteractions): Initialize preservedControlledValueRef with value
  packages/vkui/src/hooks/useEnsuredControl.ts
Labels: type:bug

#7134 fix(Popover): revert `customMiddlewares` prop
  packages/vkui/src/components/Popover/Popover.tsx
Labels: patch

#7131 fix(CustomSelect): fix scroll to element
  packages/vkui/src/components/CustomSelect/CustomSelect.e2e-playground.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.e2e.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-scroll-to-option-android-chromium-light-1-snap.png
Labels: patch

#7146 fix(GridAvatar): fix key prop
  packages/vkui/src/components/GridAvatar/GridAvatar.tsx
Labels: type:bug, cmp:grid-avatar, patch

#7100 feat(Image): borderRadius corner
  packages/vkui/src/components/Image/Image.e2e-playground.tsx
  packages/vkui/src/components/Image/Image.module.css
  packages/vkui/src/components/Image/Image.tsx
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:image

#7160 fix: update screenshot
  packages/vkui/src/components/CustomSelect/__image_snapshots__/customselect-scroll-to-option-android-chromium-light-1-snap.png
Labels: technical task

#7161 tech: mv breakpoints from js to ts
  docs/ADAPTIVITY_GUIDE.md
  packages/vkui/package.json
  packages/vkui/scripts/generateCSSCustomMedias.js
  packages/vkui/scripts/generateCSSCustomMedias.mjs
  packages/vkui/shared.config.js
  packages/vkui/src/components/Textarea/Textarea.e2e-playground.tsx
  packages/vkui/src/lib/adaptivity/breakpoints.ts
  packages/vkui/src/lib/adaptivity/constants.ts
  packages/vkui/src/lib/adaptivity/functions.ts
  packages/vkui/src/lib/adaptivity/index.ts
  packages/vkui/src/lib/adaptivity/types.ts
  packages/vkui/src/shared/breakpoints.d.ts
  packages/vkui/tsconfig.json
  styleguide/Components/Preview.js
Labels: technical task, adaptivity

#7163 fix(Checkbox): remove mutating ref
  packages/vkui/src/components/Checkbox/Checkbox.tsx
Labels: patch

#7178 docs(intro.md): fix typo
  styleguide/pages/intro.md
Labels: docs, patch

#7147 fix(FocusTrap): fix first render modal autoFocus
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
  packages/vkui/src/helpers/array.test.ts
  packages/vkui/src/helpers/array.ts
Labels: patch

#7135 refactor(Snackbar): show snackbar always from bottom-start in mobile
  packages/vkui/src/components/Snackbar/Snackbar.module.css
  packages/vkui/src/components/Snackbar/Snackbar.test.tsx
  packages/vkui/src/components/Snackbar/Snackbar.tsx
  packages/vkui/src/components/Snackbar/types.ts
  packages/vkui/src/components/Snackbar/utils.ts
  packages/vkui/src/components/Spinner/Spinner.test.tsx
  packages/vkui/src/testing/utils.tsx
Labels: patch

#7156 fix(docs): fix path to story for components(DropZone, HorizontalCellShowMore, HorizontalScroll)
  packages/vkui/src/components/DropZone/DropZone.stories.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalCellShowMore/HorizontalCellShowMore.stories.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.stories.tsx
Labels: patch

#7197 docs(CustomSelect): fix token
  packages/vkui/src/components/CustomSelect/Readme.md
Labels: docs, cmp:custom-select, patch

#7151 feat: add autoHideScrolbar and autoHodeScrollbarDelay props to CustomSelect and ChipsSelect
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
Labels: type:feature, cmp:custom-select, cmp:chips-input

#7189 doc(DateRangeInput): remove wrapper
  packages/vkui/src/components/DateRangeInput/Readme.md
Labels: cmp:date-range-input, patch

#7170 fix(Popover): fix multiple trigger behavior
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: patch

#7033 feat(Cell/SimpleCell/MiniInfoCell/RichCell): Use spacing size tokens
  packages/vkui/src/components/Cell/Cell.module.css
  packages/vkui/src/components/MiniInfoCell/MiniInfoCell.module.css
  packages/vkui/src/components/RichCell/RichCell.module.css
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
Labels: type:feature, cmp:cell, cmp:rich-cell, cmp:mini-info-cell, cmp:simple-cell

#7193 fix(PanelHeaderContext): remove init animation
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.test.tsx
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.tsx
Labels: patch

#7205 docs(customize.md): fix imports and add additional comments
  styleguide/pages/customize.md
Labels: docs, vkui-tokens, patch

#7199 fix(useFloatingWithInteractions): prevent mouse events when `willBeHide` is `true`
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: patch

#7196 fix(Search): fix ios button animation
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Search/__image_snapshots__/search-shows-after-when-focused-on-ios-vkcom-firefox-light-1-snap.png
Labels: patch

#7167 fix(ChipsSelect): add open select when focus to form field
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx
Labels: patch

#7168 docs(CSS_GUIDE): update info
  docs/CSS_GUIDE.md
Labels: docs

#7232 fix: double animation-fade-in
  packages/vkui/src/components/Accordion/Accordion.module.css
  packages/vkui/src/components/ModalRoot/ModalRoot.module.css
Labels: type:bug, cmp:modal, patch, cmp:accordion

#7233 fix(TabsItem): hover background
  packages/vkui/src/components/TabsItem/TabsItem.e2e-playground.tsx
  packages/vkui/src/components/TabsItem/TabsItem.e2e.tsx
  packages/vkui/src/components/TabsItem/TabsItem.module.css
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-android-chromium-dark-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-android-chromium-light-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-ios-webkit-light-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/TabsItem/__image_snapshots__/tabsitem-state-vkcom-webkit-light-1-snap.png
Labels: patch

#7236 feat(Gradient): mode overlay
  packages/vkui/src/components/Gradient/Gradient.e2e-playground.tsx
  packages/vkui/src/components/Gradient/Gradient.module.css
  packages/vkui/src/components/Gradient/Gradient.tsx
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-android-chromium-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Gradient/__image_snapshots__/gradient-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:gradient

#7240 fix(Flex): flexBasis in style
  packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx
Labels: patch

#6233 tech: add SimpleGrid component
  packages/vkui/src/components/Flex/Flex.tsx
  packages/vkui/src/components/SimpleGrid/Readme.md
  packages/vkui/src/components/SimpleGrid/SimpleGrid.e2e-playground.tsx
  packages/vkui/src/components/SimpleGrid/SimpleGrid.e2e.tsx
  packages/vkui/src/components/SimpleGrid/SimpleGrid.module.css
  packages/vkui/src/components/SimpleGrid/SimpleGrid.stories.tsx
  packages/vkui/src/components/SimpleGrid/SimpleGrid.test.tsx
  packages/vkui/src/components/SimpleGrid/SimpleGrid.tsx
  packages/vkui/src/components/SimpleGrid/__image_snapshots__/simplegrid-rendering-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleGrid/__image_snapshots__/simplegrid-rendering-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleGrid/__image_snapshots__/simplegrid-rendering-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleGrid/__image_snapshots__/simplegrid-rendering-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleGrid/__image_snapshots__/simplegrid-rendering-vkcom-webkit-light-1-snap.png
  packages/vkui/src/index.ts
  styleguide/config.js
Labels: no-stale

#7242 fix(Cell): Ignore falsy explicit undefined Component value with href
  packages/vkui/src/components/Cell/Cell.test.tsx
  packages/vkui/src/components/Cell/Cell.tsx
Labels: type:bug, cmp:cell, patch

#7243 fix(ModalDismissButton): Changed transition from opacity to background
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.module.css
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-android-chromium-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ModalDismissButton/__image_snapshots__/modaldismissbutton-vkcom-webkit-light-1-snap.png
Labels: cmp:modal-dismiss-button, patch

#7241 refactor: rm debounce
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/lib/utils.ts
Labels: technical task

#7261 chore: rm vkui.js
  packages/vkui/shared.config.js
  packages/vkui/src/vkui.js
  webpack.common.config.js
Labels: technical task

#7259 chore(husky): run command directly
  .husky/pre-commit
  package.json
Labels: technical task

#7262 feat(Popover): add onShownChanged prop
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: patch

#7260 build(dev-deps): Bump @storybook/addon-webpack5-compiler-swc to 1.0.5
  tools/storybook-addon-cartesian/package.json
  yarn.lock
Labels: dependencies

#7267 feat(Tooltip): disable trigger on focus with disableTriggerOnFocus prop
  packages/vkui/src/components/Tooltip/Tooltip.tsx
Labels: type:feature

#7266 feat(useCSSKeyframesAnimationController): exclude first rerender
  packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.test.ts
  packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.ts
Labels: type:feature, technical task

#7271 tech(docker-compose.yml): add corepack enable; rm unused flag
  benchmark/docker-compose.yml
Labels: technical task

#7216 fix(ActionSheetItem): fix navigation by arrows in selectable ActionSheetItem
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.tsx
  packages/vkui/src/components/ActionSheet/ActionSheetContext.ts
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.test.tsx
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.tsx
  packages/vkui/src/components/ActionSheetItem/helpers.ts
Labels: pr-needs-work
