Repository VKCOM/VKUI, pull requests merged in 2024-01, with the labels that each got.

#6381 fix: button add onClick = noop
  packages/vkui/src/components/Button/Button.tsx
  packages/vkui/src/components/Link/Link.tsx
Labels: type:bug, cmp:button, cmp:link

#6390 fix(README.md): mv 6.0.0-beta.3 to 6.0.0 in links
  README.md
Labels: type:bug, docs, patch

#6391 tech(pull_request_common): rm disabled labels job
  .github/workflows/pull_request_common.yml
Labels: technical task

#6386 fix(NativeDatePicker): Exclude monthNames prop from passed props
  packages/vkui/src/components/DatePicker/DatePicker.tsx
Labels: type:bug, cmp:date-picker, patch

#6385 fix(WriteBarIcon): [v5] update missing label warning logic
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.test.tsx
  packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
Labels: patch

#6393 fix(View): Restore scroll position on swipe back cancel (cherry-picked from #6325)
  packages/vkui/src/components/View/View.test.tsx
  packages/vkui/src/components/View/View.tsx
Labels: patch

#6398 fix(useDraggableWithDomApi): placeholder double render (React 18) (cherry-picked from #6187)
  packages/vkui/src/hooks/useDraggableWithDomApi/useDraggableWithDomApi.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/utils.ts
Labels: patch

#6399 fix(ActionSheetItem): hover on desktop without border-radius (#6309)
  packages/vkui/src/components/ActionSheet/ActionSheet.e2e-playground.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.e2e.tsx
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-desktop-sizey-regular-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-android-chromium-light-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ActionSheet/__image_snapshots__/actionsheet-viewwidth-mobile-sizey-regular-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
Labels: patch, v5

#6401 fix(DateInput): Clear DateInput focus when click Done button (#6312)
  packages/vkui/src/hooks/useDateInput.ts
Labels: patch

#6402 fix[CustomSelect]: Disable autocomplete tooltip on iOS in readonly mode (#6274)
  packages/vkui/src/components/CustomSelect/CustomSelect.e2e.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelect/CustomSelectClearButton.tsx
  packages/vkui/src/components/CustomSelect/CustomSelectInput.tsx
  packages/vkui/src/components/CustomSelect/Readme.md
Labels: patch, v5

#6406 codemode(chips-input): mv inputAriaLabel to placeholder
  packages/codemods/src/transforms/__tests__/__snapshots__/chips-input.ts.snap
  packages/codemods/src/transforms/chips-input.ts
Labels: technical task

#6405 fix(Switch): Show focus in android talkback (#6365)
  packages/vkui/src/components/Switch/Switch.stories.tsx
  packages/vkui/src/components/Switch/Switch.test.tsx
  packages/vkui/src/components/Switch/Switch.tsx
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.module.css
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.test.tsx
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
Labels: patch

#6404 fix(DateRangeInput): Treat array of nulls as empty value to set start date on click (#6215)
  packages/vkui/src/components/CalendarRange/CalendarRange.stories.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.stories.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
Labels: patch

#6408 [CustomSelect]: Pass required prop to native select instead of search input (#6373)
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: v5

#6409 [DatePicker]: Exclude monthNames prop from passed props to NativeDatePicker (#6386)
  packages/vkui/src/components/DatePicker/DatePicker.tsx
Labels: v5

#6429 fix(Accordion): use max-height
  packages/vkui/src/components/Accordion/Accordion.module.css
  packages/vkui/src/components/Accordion/AccordionContent.tsx
Labels: patch

#6395 feat(ChipsInputBase): add cycle navigates between chips
  packages/vkui/src/components/ChipsInput/Readme.md
  packages/vkui/src/components/ChipsInput/useChipsInput.ts
  packages/vkui/src/components/ChipsInputBase/Chip/Chip.test.tsx
  packages/vkui/src/components/ChipsInputBase/Chip/Chip.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.module.css
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx
  packages/vkui/src/components/ChipsInputBase/helpers.ts
  packages/vkui/src/components/ChipsInputBase/types.ts
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
Labels: type:feature, cmp:chips, cmp:chips-select, cmp:chips-input, patch

#6442 fix(SubnavigationBar): ignore falsy children
  packages/vkui/src/components/SubnavigationBar/SubnavigationBar.test.tsx
  packages/vkui/src/components/SubnavigationBar/SubnavigationBar.tsx
Labels: patch

#6447 docs: fix selection in chrome
  styleguide/Components/Editor/Editor.css
Labels: patch

#6455 feat(Radio): extend by Tappablep props
  packages/vkui/src/components/Radio/Radio.tsx
Labels: type:feature, cmp:radio

#6456 fix(Cell): patch client height of html (see `draggable` mode)
  packages/vkui/src/lib/dom.test.ts
  packages/vkui/src/lib/dom.tsx
Labels: patch

#6310 feat: add Mark
  package.json
  packages/vkui/src/components/Mark/Mark.e2e-playground.tsx
  packages/vkui/src/components/Mark/Mark.e2e.tsx
  packages/vkui/src/components/Mark/Mark.module.css
  packages/vkui/src/components/Mark/Mark.stories.tsx
  packages/vkui/src/components/Mark/Mark.test.tsx
  packages/vkui/src/components/Mark/Mark.tsx
  packages/vkui/src/components/Mark/Readme.md
  packages/vkui/src/components/Mark/__image_snapshots__/mark-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-android-chromium-light-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Mark/__image_snapshots__/mark-vkcom-webkit-light-1-snap.png
  packages/vkui/src/index.ts
  styleguide/config.js
  yarn.lock
Labels: type:feature, no-stale, cmp:mark

#6461 patch(v5): pr6456
  packages/vkui/src/lib/dom.test.ts
  packages/vkui/src/lib/dom.tsx
Labels: patch

#6483 fix(ImageBase): export ImageBaseProps
  packages/vkui/src/index.ts
Labels: patch, v5

#6389 fix(Snackbar/AppRootPortal): fix default shouldDisablePortalLogic in AppRootPortal
  packages/vkui/src/components/AppRoot/AppRootPortal.test.tsx
  packages/vkui/src/components/AppRoot/AppRootPortal.tsx
Labels: patch

#6477 fix(SimpleCell): disable indicator's shrinking
  packages/vkui/src/components/SimpleCell/SimpleCell.e2e-playground.tsx
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-light-1-snap.png
Labels: patch

#6482 fix: Add popper changes for v6
  packages/codemods/src/transforms/__testfixtures__/tooltip-container/basic.input.tsx
  packages/codemods/src/transforms/__testfixtures__/tooltip/basic.input.tsx
  packages/codemods/src/transforms/__tests__/__snapshots__/tooltip-container.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/tooltip.ts.snap
  packages/codemods/src/transforms/__tests__/tooltip-container.ts
  packages/codemods/src/transforms/tooltip-container.ts
  packages/codemods/src/transforms/tooltip.ts
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.test.tsx
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx
  packages/vkui/src/components/Popover/Popover.test.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popper/Popper.tsx
  packages/vkui/src/components/Tooltip/Tooltip.test.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/lib/floating/index.ts
  packages/vkui/src/lib/floating/types/common.ts
  packages/vkui/src/lib/floating/types/component.ts
  packages/vkui/src/lib/floating/usePlacementChangeCallback.ts
  styleguide/pages/migration_v6.md
Labels: patch

#6485 tech(jest): resolve warnings in packages/vkui
  package.json
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/Alert/Alert.test.tsx
  packages/vkui/src/components/Avatar/Avatar.test.tsx
  packages/vkui/src/components/Calendar/Calendar.test.tsx
  packages/vkui/src/components/ChipsInput/ChipsInput.test.tsx
  packages/vkui/src/components/ChipsInputBase/Chip/Chip.test.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
  packages/vkui/src/components/Gallery/Gallery.test.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx
  packages/vkui/src/components/ImageBase/ImageBase.test.tsx
  packages/vkui/src/components/LocaleProvider/LocaleProvider.test.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/ModalRoot/useModalManager.test.tsx
  packages/vkui/src/components/NavTransitionDirectionContext/NavTransitionDirectionContext.test.tsx
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.test.tsx
  packages/vkui/src/components/PopoutWrapper/PopoutWrapper.test.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx
  packages/vkui/src/components/Root/Root.test.tsx
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Slider/Slider.test.tsx
  packages/vkui/src/components/Snackbar/Snackbar.test.tsx
  packages/vkui/src/components/TabbarItem/TabbarItem.test.tsx
  packages/vkui/src/components/Tabs/Tabs.test.tsx
  packages/vkui/src/components/Tappable/Tappable.test.tsx
  packages/vkui/src/components/Textarea/Textarea.test.tsx
  packages/vkui/src/components/Touch/Touch.test.tsx
  packages/vkui/src/components/View/View.test.tsx
  packages/vkui/src/components/View/ViewInfinite.test.tsx
  packages/vkui/src/hooks/useAutoFocus.test.tsx
  packages/vkui/src/hooks/usePatchChildren.test.tsx
  packages/vkui/src/hooks/useTimeout.test.ts
  packages/vkui/src/lib/getNavId.test.ts
  packages/vkui/src/lib/warnOnce.test.ts
  packages/vkui/src/testing/utils.tsx
  yarn.lock
Labels: technical task

#6484 fix(Tooltip)[v5]: Merge getRootRef prop with floating ref and pass to BaseTooltip getRootRef
  packages/vkui/src/components/Tooltip/Tooltip.test.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
Labels: patch

#6486 build(vkui-floating-ui): fix exports path
  packages/vkui-floating-ui/index.mjs
  packages/vkui-floating-ui/package.json
Labels: technical task
