Repository VKCOM/VKUI, pull requests merged in 2024-06, with the labels that each got.

#6976 feat(ChipsSelect): add dropdownOffsetDistance
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: type:feature, cmp:chips-select

#6987 fix(SplitLayout): center on inner
  packages/vkui/src/components/SplitLayout/SplitLayout.e2e-playground.tsx
  packages/vkui/src/components/SplitLayout/SplitLayout.e2e.tsx
  packages/vkui/src/components/SplitLayout/SplitLayout.module.css
  packages/vkui/src/components/SplitLayout/SplitLayout.tsx
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-android-chromium-light-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SplitLayout/__image_snapshots__/splitlayout-vkcom-webkit-light-1-snap.png
Labels: patch

#6985 feat(CustomSelect): export CustomSelectClearButtonProps
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/index.ts
Labels: type:feature, cmp:custom-select

#6991 refactor(stylelint): mv to `tools/stylelint-plugin-vkui`
  package.json
  stylelint.config.js
  tools/stylelint-plugin-vkui/.eslintrc.mjs
  tools/stylelint-plugin-vkui/index.js
  tools/stylelint-plugin-vkui/jest.config.js
  tools/stylelint-plugin-vkui/jest.setup.js
  tools/stylelint-plugin-vkui/package.json
  tools/stylelint-plugin-vkui/rules/bad-multiplication/index.js
  tools/stylelint-plugin-vkui/rules/bad-multiplication/index.test.js
  tools/stylelint-plugin-vkui/rules/index.js
  tools/stylelint-plugin-vkui/tsconfig.json
  yarn.lock
Labels: technical task

#6978 fix(DatePicker): support value & defaultValue
  packages/vkui/src/components/DatePicker/DatePicker.test.tsx
  packages/vkui/src/components/DatePicker/DatePicker.tsx
  packages/vkui/src/components/DatePicker/Readme.md
Labels: patch

#6993 fix(Textarea): add overflow: hidden
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-mobile-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-tablet-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ModalCard/__image_snapshots__/modalcard-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Textarea/Textarea.module.css
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-android-chromium-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-state-focus-visible-android-chromium-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-firefox-light-1-snap.png
Labels: type:bug, cmp:textarea, patch

#7008 fix: fix warning of React.use usage
  packages/vkui/src/lib/utils.ts
Labels: type:bug, patch

#6918 fix(Popover): fix multiple trigger behavior
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: patch

#6955 fix(ActionSheet)Make ActionSheet accessible
  packages/vkui/src/components/ActionSheet/ActionSheet.stories.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/ActionSheet/ActionSheet.tsx
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/Alert/Alert.e2e-playground.tsx
  packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
  packages/vkui/src/components/ModalRoot/ModalRootDesktop.tsx
  packages/vkui/src/components/PopoutRoot/PopoutRoot.tsx
  packages/vkui/src/components/Popover/Popover.stories.tsx
  packages/vkui/src/components/Popover/Popover.test.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popover/Readme.md
  packages/vkui/src/lib/accessibility.test.tsx
  packages/vkui/src/lib/accessibility.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/testing/utils.tsx
Labels: pr-needs-work

#6986 Bump jscodeshift to fix ast error with TS satisfies operator
  packages/codemods/README.md
  packages/codemods/package.json
  packages/codemods/src/index.ts
  packages/codemods/src/testHelpers/testHelper.ts
  packages/codemods/src/transforms/__tests__/__snapshots__/action-sheet-item.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/action-sheet.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/alert.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/appearance-provider.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/calendar-range.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/calendar.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/card-scroll.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/chip.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/chips-input.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/config-provider.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/content-card.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/date-input.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/date-range-input.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/fixed-layout.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/form-item.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/gallery.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/image-base.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/modal-card.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/modal-page-header.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/pagination.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/panel-header.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/placeholder.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/popout-wrapper.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/popover.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/popper.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/range-slider.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/search.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/select.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/simple-cell.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/split-col.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/tabbar.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/text-tooltip.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/tooltip-container.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/tooltip.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/typography.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/users-stack.ts.snap
  packages/codemods/src/transforms/__tests__/__snapshots__/visually-hidden-input.ts.snap
  packages/codemods/src/transforms/banner.ts
  packages/codemods/src/transforms/custom-scroll-view.ts
  yarn.lock
Labels: subpackage:@vkontakte/vkui-codemods

#7003 feat: add DisplayTitle
  packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.e2e-playground.tsx
  packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.e2e.tsx
  packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.module.css
  packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.stories.tsx
  packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.test.tsx
  packages/vkui/src/components/Typography/DisplayTitle/DisplayTitle.tsx
  packages/vkui/src/components/Typography/DisplayTitle/Readme.md
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-android-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/DisplayTitle/__image_snapshots__/displaytitle-vkcom-webkit-light-1-snap.png
  packages/vkui/src/index.ts
  styleguide/config.js
Labels: type:feature, cmp:typography

#7011 fix(Select): use conditional render
  packages/vkui/src/components/Select/Select.test.tsx
  packages/vkui/src/components/Select/Select.tsx
  packages/vkui/src/styles/adaptivity.module.css
Labels: type:bug, cmp:select, patch

#6957 feat(Switch): use m3 redesign
  packages/vkui/shared.config.js
  packages/vkui/src/components/Link/Link.module.css
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Switch/Switch.module.css
  packages/vkui/src/components/Switch/Switch.stories.tsx
  packages/vkui/src/components/Switch/Switch.test.tsx
  packages/vkui/src/components/Switch/Switch.tsx
  packages/vkui/src/components/Switch/__image_snapshots__/switch-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-android-chromium-light-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-state-focus-visible-android-chromium-light-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Switch/__image_snapshots__/switch-vkcom-webkit-light-1-snap.png
  packages/vkui/src/styles/customMedias.generated.css
  styleguide/Components/Settings/HasCustomPanelHeaderAfter.js
  styleguide/Components/Settings/HasPointerCheckbox.js
Labels: no-stale

#7029 fix(Clickable): lockState block events
  packages/vkui/src/components/Clickable/useState.tsx
  packages/vkui/src/components/Tappable/Tappable.test.tsx
Labels: patch

#7034 build(css): fix source-map generated by webpack
  package.json
  packages/vkui/scripts/postcss.js
  packages/vkui/webpack.styles.config.js
  yarn.lock
Labels: type:bug, technical task

#7035 fix(Spacing): padding style wasn't applied
  packages/vkui/src/components/Spacing/Spacing.e2e-playground.tsx
  packages/vkui/src/components/Spacing/Spacing.module.css
  packages/vkui/src/components/Spacing/Spacing.test.tsx
  packages/vkui/src/components/Spacing/Spacing.tsx
Labels: type:bug, cmp:spacing, patch

#7037 tech: bump prettier from 2.8.8 to 3.3.2; use stylelint-prettier
  package.json
  packages/vkui/playwright-ct.config.ts
  packages/vkui/playwright/index.html
  packages/vkui/src/components/ActionSheetItem/ActionSheetItem.module.css
  packages/vkui/src/components/Alert/Alert.module.css
  packages/vkui/src/components/Button/Button.module.css
  packages/vkui/src/components/CustomScrollView/CustomScrollView.module.css
  packages/vkui/src/components/FixedLayout/Readme.md
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.module.css
  packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css
  packages/vkui/src/components/PullToRefresh/PullToRefresh.stories.tsx
  packages/vkui/src/components/PullToRefresh/Readme.md
  packages/vkui/src/components/Search/Search.module.css
  packages/vkui/src/components/SegmentedControl/SegmentedControl.module.css
  packages/vkui/src/components/TabsItem/TabsItem.module.css
  packages/vkui/src/components/Touch/Touch.test.tsx
  packages/vkui/src/components/View/Readme.md
  packages/vkui/src/components/View/View.tsx
  packages/vkui/src/components/View/ViewInfinite.tsx
  packages/vkui/src/hooks/useAdaptivityConditionalRender/helpers.ts
  packages/vkui/src/hooks/useFocusVisible.test.tsx
  packages/vkui/src/hooks/usePatchChildren.ts
  packages/vkui/src/lib/dom.tsx
  packages/vkui/src/testing/e2e/ComponentPlayground.tsx
  stylelint.config.js
  tools/storybook-addon-cartesian/src/Tool.tsx
  yarn.lock
Labels: technical task

#7038 tech(generate_env_docker): mv `jq` to `cut`
  packages/vkui/scripts/generate_env_docker.sh
Labels: technical task

#7039 fix(ToolButton): mv gap to wrapper of children prop
  packages/vkui/src/components/ToolButton/ToolButton.module.css
  packages/vkui/src/components/ToolButton/ToolButton.tsx
Labels: type:bug, patch, cmp:tool-button

#7046 docs(ModalRoot): ButtonGroup gap
  packages/vkui/src/components/ModalRoot/Readme.md
Labels: patch

#7066 chore: yarn.lock update
  yarn.lock
Labels: dependencies

#7068 fix(focusVisible): revert animation duration
  packages/vkui/src/styles/focusVisible.module.css
Labels: type:bug

#7041 fix(FocusTrap): add mutation observer
  packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
Labels: patch

#7076 test: use no memo
  packages/vkui/src/components/ConfigProvider/ConfigProvider.test.tsx
  packages/vkui/src/components/LocaleProvider/LocaleProvider.test.tsx
  packages/vkui/src/components/PlatformProvider/PlatformProvider.test.tsx
  packages/vkui/src/components/Popover/Popover.test.tsx
  packages/vkui/src/hooks/useExternRef.test.tsx
  packages/vkui/src/hooks/useFocusWithin.test.tsx
Labels: technical task

#7084 docs: Replace forcePortal with usePortal
  packages/vkui/src/components/Popper/Readme.md
Labels: docs

#7080 fix(Tappable): Remove will-change hack from ripple effect layer
  packages/vkui/src/components/Calendar/__image_snapshots__/calendar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Tappable/Tappable.module.css
Labels: cmp:tappable

#7085 chore(tsconfig): disallow JS
  packages/vkui/.eslintrc.js
  packages/vkui/jest.config.js
  packages/vkui/jest.setup.ts
  packages/vkui/scripts/postcss.d.ts
  packages/vkui/src/lib/accessibility.test.tsx
  packages/vkui/src/shared/breakpoints.d.ts
  packages/vkui/tsconfig.eslint.json
  packages/vkui/tsconfig.json
  tsconfig.json
Labels: technical task

#6226 tech: Add Flex component
  .eslintrc.json
  packages/vkui/src/components/Avatar/Readme.md
  packages/vkui/src/components/Button/Readme.md
  packages/vkui/src/components/ButtonGroup/Readme.md
  packages/vkui/src/components/Checkbox/Readme.md
  packages/vkui/src/components/DateInput/Readme.md
  packages/vkui/src/components/DateRangeInput/Readme.md
  packages/vkui/src/components/Flex/Flex.e2e-playground.tsx
  packages/vkui/src/components/Flex/Flex.e2e.tsx
  packages/vkui/src/components/Flex/Flex.module.css
  packages/vkui/src/components/Flex/Flex.stories.tsx
  packages/vkui/src/components/Flex/Flex.test.tsx
  packages/vkui/src/components/Flex/Flex.tsx
  packages/vkui/src/components/Flex/FlexItem/FlexItem.module.css
  packages/vkui/src/components/Flex/FlexItem/FlexItem.test.tsx
  packages/vkui/src/components/Flex/FlexItem/FlexItem.tsx
  packages/vkui/src/components/Flex/Readme.md
  packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-android-chromium-light-1-snap.png
  packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Flex/__image_snapshots__/flex-rendering-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/FormField/Readme.md
  packages/vkui/src/components/Gallery/Readme.md
  packages/vkui/src/components/Gradient/Readme.md
  packages/vkui/src/components/GridAvatar/Readme.md
  packages/vkui/src/components/HorizontalCell/HorizontalCell.stories.tsx
  packages/vkui/src/components/HorizontalCell/Readme.md
  packages/vkui/src/components/HorizontalScroll/Readme.md
  packages/vkui/src/components/IconButton/Readme.md
  packages/vkui/src/components/Image/Readme.md
  packages/vkui/src/components/Input/Readme.md
  packages/vkui/src/components/ModalPage/ModalPage.stories.tsx
  packages/vkui/src/components/ModalRoot/Readme.md
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.stories.tsx
  packages/vkui/src/components/Pagination/Readme.md
  packages/vkui/src/components/Popover/Popover.stories.tsx
  packages/vkui/src/components/Popover/Readme.md
  packages/vkui/src/components/Spacing/Spacing.module.css
  packages/vkui/src/components/Spinner/Readme.md
  packages/vkui/src/components/SubnavigationButton/Readme.md
  packages/vkui/src/components/ToolButton/Readme.md
  packages/vkui/src/components/Typography/Footnote/Readme.md
  packages/vkui/src/components/UsersStack/Readme.md
  packages/vkui/src/components/View/Readme.md
  packages/vkui/src/components/View/View.stories.tsx
  packages/vkui/src/index.ts
  packages/vkui/src/lib/layouts/gaps.test.ts
  packages/vkui/src/lib/layouts/gaps.ts
  packages/vkui/src/lib/layouts/index.ts
  packages/vkui/src/styles/constants.css
  packages/vkui/src/styles/gaps.module.css
  styleguide/config.js
Labels: no-stale

#7079 feat(FloatingArrow): Apply offset according to the placement Align
  packages/vkui/src/components/FloatingArrow/FloatingArrow.tsx
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.e2e-playground.tsx
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-android-chromium-dark-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-android-chromium-light-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-ios-webkit-light-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/OnboardingTooltip/__image_snapshots__/onboardingtooltip-vkcom-webkit-light-1-snap.png
Labels: type:feature

#7092 fix(CustomSelectOption): add word-break: break-word
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.module.css
Labels: patch

#7097 fix(CustomScrollView): add size styles to box-content
  packages/vkui/src/components/CustomScrollView/CustomScrollView.module.css
Labels: type:bug, cmp:custom-select, patch
