Repository VKCOM/VKUI, pull requests merged in 2024-05, with the labels that each got.

#6818 fix: SegmentedControlOption hover
  packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.module.css
  packages/vkui/src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
Labels: cmp:segmented-control, patch

#6692 feat: add ellipsistext
  packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.e2e-playground.tsx
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.e2e.tsx
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.module.css
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.stories.tsx
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.test.tsx
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx
  packages/vkui/src/components/Typography/EllipsisText/Readme.md
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-android-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Typography/EllipsisText/__image_snapshots__/ellipsistext-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Typography/Typography.stories.tsx
  packages/vkui/src/index.ts
  styleguide/config.js
Labels: pr-needs-work

#6875 fix: useRef need args
  packages/vkui/src/components/ActionSheet/Readme.md
  packages/vkui/src/components/Input/Readme.md
  packages/vkui/src/components/Popper/Readme.md
  packages/vkui/src/components/Touch/Readme.md
  packages/vkui/src/components/WriteBar/Readme.md
  styleguide/Components/Setting/Setting.js
  styleguide/Components/Table/TableRenderer.js
Labels: patch

#6876 fix(doc): add example ActionSheetItem without autoClose prop
  styleguide/pages/migration_v6.md
Labels: patch

#6879 docs: resolve @since comments
  packages/vkui/src/components/Mark/Mark.tsx
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx
  packages/vkui/src/components/VisuallyHidden/VisuallyHidden.tsx
Labels: docs

#6881 fix(Button/Link): reset user-agent styles
  packages/vkui/src/components/Button/Button.module.css
  packages/vkui/src/components/Clickable/Clickable.module.css
  packages/vkui/src/components/Clickable/Clickable.tsx
  packages/vkui/src/components/Link/Link.module.css
Labels: patch

#6806 feat(Snackbar): add placement prop
  packages/vkui/src/components/Epic/Epic.module.css
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Slider/Slider.test.tsx
  packages/vkui/src/components/Snackbar/Snackbar.e2e-playground.tsx
  packages/vkui/src/components/Snackbar/Snackbar.e2e.tsx
  packages/vkui/src/components/Snackbar/Snackbar.module.css
  packages/vkui/src/components/Snackbar/Snackbar.stories.tsx
  packages/vkui/src/components/Snackbar/Snackbar.test.tsx
  packages/vkui/src/components/Snackbar/Snackbar.tsx
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-mode-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-mode-android-chromium-light-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-android-chromium-light-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Snackbar/__image_snapshots__/snackbar-placement-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.module.css
  packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
  packages/vkui/src/components/Snackbar/types.ts
  packages/vkui/src/components/Snackbar/utils.ts
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/hooks/useGlobalEscKeyDown.ts
  packages/vkui/src/lib/animation/fades.ts
  packages/vkui/src/lib/animation/index.ts
  packages/vkui/src/lib/animation/rubberbandIfOutOfBounds.test.ts
  packages/vkui/src/lib/animation/rubberbandIfOutOfBounds.ts
  packages/vkui/src/lib/animation/transformOrigin.ts
  packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.test.ts
  packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.ts
  packages/vkui/src/lib/animation/useReducedMotion.ts
  packages/vkui/src/lib/cssAnimation/index.ts
  packages/vkui/src/lib/dom.test.ts
  packages/vkui/src/lib/dom.tsx
  packages/vkui/src/lib/touch/UIPanGestureRecognizer.test.ts
  packages/vkui/src/lib/touch/UIPanGestureRecognizer.ts
  packages/vkui/src/lib/touch/functions.test.ts
  packages/vkui/src/lib/touch/functions.ts
  packages/vkui/src/lib/touch/index.ts
  packages/vkui/src/testing/e2e/AppDefaultWrapper.tsx
  packages/vkui/src/testing/e2e/ComponentPlayground.tsx
  packages/vkui/src/testing/utils.tsx
Labels: no-stale

#6880 fix(Button): add transition property for background-color and color
  packages/vkui/src/components/Button/Button.module.css
Labels: patch

#6890 tech(playwright): fix docker warns
  packages/vkui/docker-compose.yml
  packages/vkui/package.json
Labels: technical task

#6908 fix: fetchPriority React@19 support
  packages/vkui/src/components/ContentCard/ContentCard.tsx
  packages/vkui/src/components/ImageBase/ImageBase.tsx
  packages/vkui/src/lib/utils.ts
Labels: patch

#6916 tech: fix jest deprecation and warnings
  packages/vkui/src/components/ActionSheet/ActionSheet.test.tsx
  packages/vkui/src/components/Alert/Alert.test.tsx
  packages/vkui/src/components/FocusTrap/FocusTrap.test.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/ModalRoot/useModalManager.test.tsx
  packages/vkui/src/components/NavTransitionDirectionContext/NavTransitionDirectionContext.test.tsx
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.test.tsx
  packages/vkui/src/components/PopoutWrapper/PopoutWrapper.test.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx
  packages/vkui/src/components/Root/Root.test.tsx
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Slider/Slider.test.tsx
  packages/vkui/src/components/Tabs/Tabs.test.tsx
  packages/vkui/src/components/Textarea/Textarea.test.tsx
  packages/vkui/src/components/View/View.test.tsx
  packages/vkui/src/components/View/ViewInfinite.test.tsx
  packages/vkui/src/helpers/getMergedSameEventsByProps.test.ts
  packages/vkui/src/hooks/useAutoDetectAppearance.test.ts
  packages/vkui/src/hooks/useBooleanState.test.tsx
  packages/vkui/src/hooks/useFocusVisible.test.tsx
  packages/vkui/src/hooks/useFocusVisibleClassName.test.ts
  packages/vkui/src/hooks/useFocusWithin.test.tsx
  packages/vkui/src/hooks/useKeyboardInputTracker.test.ts
  packages/vkui/src/hooks/usePatchChildren.test.tsx
  packages/vkui/src/hooks/useTimeout.test.ts
  packages/vkui/src/lib/animation/useCSSKeyframesAnimationController.test.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.test.tsx
  packages/vkui/src/testing/utils.tsx
Labels: technical task

#6938 feat(ConfigProvider): raster icons support
  packages/vkui/package.json
  packages/vkui/src/components/AppearanceProvider/AppearanceProvider.tsx
  packages/vkui/src/components/ConfigProvider/ConfigProvider.tsx
  yarn.lock
Labels: type:feature, dependencies

#6906 fix(DatePicker, Popper, Popout): extend usePlacementChangeCallback logic
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popper/Popper.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/lib/floating/usePlacementChangeCallback.test.ts
  packages/vkui/src/lib/floating/usePlacementChangeCallback.ts
Labels: patch

#6925 feat(Spacing): Use vkui-tokens in the Spacing component
  packages/vkui/src/components/Spacing/Spacing.e2e-playground.tsx
  packages/vkui/src/components/Spacing/Spacing.e2e.tsx
  packages/vkui/src/components/Spacing/Spacing.tsx
  packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Spacing/__image_snapshots__/spacing-vkcom-webkit-light-1-snap.png
Labels: cmp:spacing

#6967 feat: add AppearanceType export
  packages/vkui/src/index.ts
Labels: type:feature

#6966 fix(Search): hides clear button with external changes
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Search/Search.tsx
Labels: patch

#6968 fix(doc): fix Button doc toggles
  packages/vkui/src/components/Button/Readme.md
Labels: patch

#6971 fix(Cell): rm OUTBOX_OFFSET
  packages/vkui/src/hooks/useDraggableWithDomApi/autoScroll.test.ts
  packages/vkui/src/hooks/useDraggableWithDomApi/autoScroll.ts
Labels: type:bug, cmp:cell, patch

#6970 fix(ci): bring back stable branch step
  .github/actions/publish-workflow-4-complete/action.yml
  .github/workflows/publish_prerelease.yml
Labels: technical task, patch
