Repository VKCOM/VKUI, pull requests merged in 2024-11, with the labels that each got.

#7875 docs: update MAINTAINERS.md
  docs/MAINTAINERS.md
Labels: docs

#7881 feat(AppRoot): set overscrollBehavior to <html>
  packages/vkui/src/components/AppRoot/ScrollContext.test.tsx
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
Labels: type:feature

#7879 refactor(FocusTrap): mv to hook
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
  packages/vkui/src/hooks/useFocusTrap.ts
Labels: technical task

#7880 feat(Calendar): rename `onClose` prop to `onDoneButtonClick`
  packages/codemods/src/transforms/v7/__testfixtures__/calendar/basic.input.tsx
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/calendar.ts.snap
  packages/codemods/src/transforms/v7/__tests__/calendar.ts
  packages/codemods/src/transforms/v7/calendar.ts
  packages/vkui/src/components/Calendar/Calendar.tsx
  packages/vkui/src/components/CalendarTime/CalendarTime.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
Labels: cmp:calendar, breaking-change

#7878 feat(DateInput, DateRangeInput): add prop `onCalendarOpenChanged`
  packages/vkui/src/components/DateInput/DateInput.test.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
  packages/vkui/src/hooks/useDateInput.ts
Labels: v6

#7876 feat: create useCSSTransition()
  packages/vkui/src/lib/animation/index.ts
  packages/vkui/src/lib/animation/useCSSTransition.stories.module.css
  packages/vkui/src/lib/animation/useCSSTransition.stories.tsx
  packages/vkui/src/lib/animation/useCSSTransition.test.tsx
  packages/vkui/src/lib/animation/useCSSTransition.ts
Labels: type:feature, technical task

#7899 feat: add no gap to Flex example
  packages/vkui/src/components/Flex/Readme.md
Labels: docs, cmp:flex

#7877 fix(Galery): fix autoPlay when dragging slides
  packages/vkui/src/components/Gallery/Gallery.tsx
  packages/vkui/src/components/Gallery/hooks.test.ts
  packages/vkui/src/components/Gallery/hooks.ts
Labels: patch, v6

#7905 patch: pr7877
  packages/vkui/src/components/Gallery/Gallery.tsx
  packages/vkui/src/components/Gallery/hooks.test.ts
  packages/vkui/src/components/Gallery/hooks.ts
Labels: patch

#7705 feat: add tests ids props for Calendar, CalendarRange, DateInputRange, DateInput
  packages/vkui/src/components/Calendar/Calendar.test.tsx
  packages/vkui/src/components/Calendar/Calendar.tsx
  packages/vkui/src/components/CalendarDay/CalendarDay.test.tsx
  packages/vkui/src/components/CalendarDay/CalendarDay.tsx
  packages/vkui/src/components/CalendarDays/CalendarDays.tsx
  packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
  packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.test.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx
  packages/vkui/src/components/CalendarTime/CalendarTime.tsx
  packages/vkui/src/components/DateInput/DateInput.test.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
Labels: v6

#7906 fix(Tappable): force activated/hovered state
  packages/vkui/src/components/Clickable/useState.tsx
  packages/vkui/src/components/Tappable/Tappable.test.tsx
Labels: cmp:tappable, patch, v6

#7872 fix(DateInput): use zero values with keyboard input
  packages/vkui/src/components/DateInput/DateInput.test.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
Labels: cmp:date-input, v6

#7909 fix(EllipsisText): use RootComponent for host
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.test.tsx
  packages/vkui/src/components/Typography/EllipsisText/EllipsisText.tsx
Labels: type:bug, cmp:ellipsis-text

#7908 fix(Clickable): use correct CSS property values
  packages/vkui/src/components/Clickable/Clickable.module.css
  packages/vkui/src/components/Clickable/Clickable.tsx
Labels: type:bug, cmp:clickable

#7806 fix(useFloatingWithInteractions): improve restoreFocus, add restoreFocus to anchor element
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popover/Readme.md
  packages/vkui/src/hooks/useFocusTrap.ts
  packages/vkui/src/lib/floating/types/component.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/index.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: patch, v6

#7913 patch: pr7872
  packages/vkui/src/components/DateInput/DateInput.test.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
Labels: patch

#7910 fix(Tappable): force activated/hovered state (#7906)
  packages/vkui/src/components/Clickable/useState.tsx
  packages/vkui/src/components/Tappable/Tappable.test.tsx
Labels: patch

#7914 patch: pr7806 in v6
  packages/vkui/src/components/FocusTrap/FocusTrap.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popover/Readme.md
  packages/vkui/src/lib/floating/types/component.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/index.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/types.ts
  packages/vkui/src/lib/floating/useFloatingWithInteractions/useFloatingWithInteractions.ts
Labels: patch

#7918 fix(Gallery): try to fix flaky test
  packages/vkui/src/components/Gallery/Gallery.e2e-playground.tsx
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-show-arrows-vkcom-webkit-light-1-snap.png
Labels: technical task

#7928 fix(Calendar): fixed props passing with id for testing from Calendar to CalendarTime
  packages/vkui/src/components/Calendar/Calendar.tsx
Labels: type:bug, patch, cmp:calendar, v6

#7934 tech: revert hash classes
  packages/vkui/package.swcrc
  packages/vkui/rspack.styles.config.ts
  shared.js
Labels: technical task

#7942 feat(Select): return event arg to onChange callback
  packages/codemods/src/transforms/v7/common/warnSelectOnChange.ts
  packages/codemods/src/transforms/v7/custom-select.ts
  packages/codemods/src/transforms/v7/native-select.ts
  packages/codemods/src/transforms/v7/select.ts
  packages/vkui/src/components/Avatar/Readme.md
  packages/vkui/src/components/Button/Readme.md
  packages/vkui/src/components/ButtonGroup/Readme.md
  packages/vkui/src/components/Calendar/Readme.md
  packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
  packages/vkui/src/components/CalendarRange/Readme.md
  packages/vkui/src/components/CalendarTime/CalendarTime.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelect/Readme.md
  packages/vkui/src/components/DateInput/Readme.md
  packages/vkui/src/components/DateRangeInput/Readme.md
  packages/vkui/src/components/Flex/Readme.md
  packages/vkui/src/components/FormItem/Readme.md
  packages/vkui/src/components/Image/Readme.md
  packages/vkui/src/components/Input/Readme.md
  packages/vkui/src/components/NativeSelect/NativeSelect.test.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/NativeSelect/Readme.md
  packages/vkui/src/components/Pagination/Readme.md
  packages/vkui/src/components/SimpleGrid/Readme.md
  packages/vkui/src/components/Slider/Readme.md
  packages/vkui/src/components/SubnavigationButton/Readme.md
  packages/vkui/src/components/Tabs/Readme.md
  packages/vkui/src/components/ToolButton/Readme.md
Labels: cmp:select, cmp:custom-select, cmp:native-select, breaking-change

#7939 fix(packages/vkui): add missed "type": "module"
  packages/vkui/.eslintrc.cjs
  packages/vkui/cssm/postcss.config.cjs
  packages/vkui/jest.config.ts
  packages/vkui/package.json
  packages/vkui/playwright-ct.config.mjs
  packages/vkui/rspack.styles.config.mjs
  packages/vkui/scripts/generateCSSCustomMedias.mjs
  packages/vkui/scripts/postcss.cjs
  packages/vkui/scripts/postcss.d.ts
  packages/vkui/shared.config.js
  packages/vkui/tsconfig.json
  shared.js
  stylelint.config.mjs
  webpack.common.config.js
  yarn.lock
Labels: type:bug

#7954 fix(Spacing): fix jsdoc typo
  packages/vkui/src/components/Spacing/Spacing.tsx
Labels: docs, cmp:spacing

#7874 feat(PanelHeaderButton): refactor pressets
  packages/codemods/src/transforms/v7/__testfixtures__/panel-header-back/basic.input.tsx
  packages/codemods/src/transforms/v7/__testfixtures__/panel-header-close/basic.input.tsx
  packages/codemods/src/transforms/v7/__testfixtures__/panel-header-edit/basic.input.tsx
  packages/codemods/src/transforms/v7/__testfixtures__/panel-header-submit/basic.input.tsx
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-back.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-close.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-edit.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-submit.ts.snap
  packages/codemods/src/transforms/v7/__tests__/panel-header-back.ts
  packages/codemods/src/transforms/v7/__tests__/panel-header-close.ts
  packages/codemods/src/transforms/v7/__tests__/panel-header-edit.ts
  packages/codemods/src/transforms/v7/__tests__/panel-header-submit.ts
  packages/codemods/src/transforms/v7/common/moveFromChildrenToLabel.ts
  packages/codemods/src/transforms/v7/common/removeChildrenFromComponent.ts
  packages/codemods/src/transforms/v7/panel-header-back.ts
  packages/codemods/src/transforms/v7/panel-header-close.ts
  packages/codemods/src/transforms/v7/panel-header-edit.ts
  packages/codemods/src/transforms/v7/panel-header-submit.ts
  packages/vkui/src/components/Epic/Epic.e2e-playground.tsx
  packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.e2e-playground.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.stories.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
  packages/vkui/src/components/PanelHeaderButton/Readme.md
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-android-chromium-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-android-chromium-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-ios-webkit-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-android-chromium-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-android-chromium-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-ios-webkit-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheadersubmit-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/PanelHeaderClose/PanelHeaderClose.tsx
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.e2e-playground.tsx
  packages/vkui/src/components/PanelHeaderContext/__image_snapshots__/panelheadercontext-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderContext/__image_snapshots__/panelheadercontext-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/PanelHeaderEdit/PanelHeaderEdit.tsx
  packages/vkui/src/components/PanelHeaderSubmit/PanelHeaderSubmit.tsx
  packages/vkui/src/index.ts
Labels: breaking-change, cmp:panel-header-button

#7975 fix: fix Link with icon in styleguide
  styleguide/Components/Setting/Setting.js
  styleguide/Components/Settings/ThemeName.js
Labels: docs, cmp:link

#7977 feat(FloatingArrow): reexport
  packages/vkui/src/components/FloatingArrow/DefaultIcon.tsx
  packages/vkui/src/components/FloatingArrow/FloatingArrow.module.css
  packages/vkui/src/components/FloatingArrow/FloatingArrow.test.tsx
  packages/vkui/src/components/FloatingArrow/FloatingArrow.tsx
  packages/vkui/src/index.ts
Labels: type:feature, cmp:floating-arrow

#7999 docs: fix button with version
  styleguide/Components/StyleGuide/StyleGuideHeader.js
Labels: type:bug, docs, cmp:link
