Repository VKCOM/VKUI, pull requests merged in 2024-02, with the labels that each got.

#6499 fix(codemode): wait tooltip transform first before text-tooltip
  packages/codemods/package.json
  packages/codemods/src/getAvailableCodemods.ts
  packages/codemods/src/testHelpers/testHelper.ts
  packages/codemods/src/transforms/__tests__/__snapshots__/text-tooltip.ts.snap
  packages/codemods/src/transforms/__tests__/text-tooltip.ts
Labels: type:bug, patch, subpackage:@vkontakte/vkui-codemods

#6502 fix: Change editor color in doc
  styleguide/Components/Editor/Editor.css
Labels: patch

#6490 fix(vkui-floating-ui): refactor build
  .prettierignore
  packages/vkui-floating-ui/.eslintrc.json
  packages/vkui-floating-ui/.gitignore
  packages/vkui-floating-ui/build.mjs
  packages/vkui-floating-ui/import.test.cjs
  packages/vkui-floating-ui/import.test.mjs
  packages/vkui-floating-ui/index.mjs
  packages/vkui-floating-ui/jest.config.ts
  packages/vkui-floating-ui/main.mjs
  packages/vkui-floating-ui/package.json
  packages/vkui-floating-ui/tsconfig.json
  yarn.lock
Labels: patch

#6505 ci(pull_request_common): check to open state before add patch label
  .github/workflows/pull_request_common.yml
Labels: technical task

#6494 fix(ImageBase.Badge): shadow pointer-events none
  packages/vkui/src/components/ImageBase/ImageBaseBadge/ImageBaseBadge.module.css
Labels: patch

#6508 fix: Interactive demo in docs
  packages/vkui/src/components/Badge/Readme.md
  packages/vkui/src/components/Banner/Readme.md
  packages/vkui/src/components/Cell/Cell.stories.tsx
  packages/vkui/src/components/CellButton/CellButton.stories.tsx
  packages/vkui/src/components/CellButton/Readme.md
  packages/vkui/src/components/ContentCard/Readme.md
  packages/vkui/src/components/Counter/Readme.md
  packages/vkui/src/components/Epic/Epic.stories.tsx
  packages/vkui/src/components/Epic/Readme.md
  packages/vkui/src/components/FormItem/Readme.md
  packages/vkui/src/components/Gradient/Readme.md
  packages/vkui/src/components/Group/Group.stories.tsx
  packages/vkui/src/components/Group/Readme.md
  packages/vkui/src/components/IconButton/IconButton.stories.tsx
  packages/vkui/src/components/IconButton/Readme.md
  packages/vkui/src/components/ModalCard/ModalCard.stories.tsx
  packages/vkui/src/components/ModalCardBase/Readme.md
  packages/vkui/src/components/ModalDismissButton/ModalDismissButton.stories.tsx
  packages/vkui/src/components/ModalPage/ModalPage.stories.tsx
  packages/vkui/src/components/ModalPageHeader/ModalPageHeader.stories.tsx
  packages/vkui/src/components/ModalRoot/Readme.md
  packages/vkui/src/components/PanelHeader/PanelHeader.stories.tsx
  packages/vkui/src/components/PanelHeader/Readme.md
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.stories.tsx
  packages/vkui/src/components/PanelHeaderContent/PanelHeaderContent.stories.tsx
  packages/vkui/src/components/PanelHeaderContent/Readme.md
  packages/vkui/src/components/PanelHeaderContext/PanelHeaderContext.stories.tsx
  packages/vkui/src/components/PanelHeaderContext/Readme.md
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/SimpleCell/Readme.md
  packages/vkui/src/components/SimpleCell/SimpleCell.stories.tsx
  packages/vkui/src/components/SubnavigationButton/Readme.md
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.stories.tsx
  packages/vkui/src/components/Tabs/Readme.md
  packages/vkui/src/components/TabsItem/TabsItem.stories.tsx
  packages/vkui/src/components/Tappable/Tappable.stories.tsx
  packages/vkui/src/components/WriteBar/Readme.md
  styleguide/setup.js
Labels: patch

#6532 fix(dynamicTokens): rm universal selector
  packages/vkui/src/styles/dynamicTokens.css
Labels: patch

#6507 fix(dynamicTokens): rm universal selector
  packages/vkui/src/styles/dynamicTokens.css
Labels: patch

#6489 fix(AdaptivityProvider): calculate size y when viewWidth is provided
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx
  packages/vkui/src/lib/adaptivity/functions.ts
Labels: patch

#6526 ci(publish_prerelease): unify the workflow for all packages; separates deploy part
  .github/actions/publish-workflow-1-setup/action.yml
  .github/actions/publish-workflow-2-bump-version/action.yml
  .github/actions/publish-workflow-3-validation/action.yml
  .github/actions/publish-workflow-4-complete/action.yml
  .github/actions/setup/action.yml
  .github/workflows/publish_deploy.yml
  .github/workflows/publish_prerelease.yml
Labels: technical task

#6534 fix(.github/actions/publish-workflow-4-complete): add missed `shell: bash`
  .github/actions/publish-workflow-4-complete/action.yml
  .github/workflows/publish_deploy.yml
Labels: type:bug, technical task, patch

#6537 chore: add storybook dark theme
  packages/vkui/.storybook/addons/storybook-theme/StorybookTheme.tsx
  packages/vkui/.storybook/addons/storybook-theme/constants.ts
  packages/vkui/.storybook/addons/storybook-theme/preset.js
  packages/vkui/.storybook/addons/storybook-theme/register.ts
  packages/vkui/.storybook/addons/storybook-theme/vkui-logo-dark.svg
  packages/vkui/.storybook/addons/storybook-theme/vkui-logo-light.svg
  packages/vkui/.storybook/addons/storybook-theme/vkuiThemes.ts
  packages/vkui/.storybook/logo.svg
  packages/vkui/.storybook/main.ts
  packages/vkui/.storybook/manager.ts
  packages/vkui/.storybook/preview.ts
  packages/vkui/.storybook/vkuiTheme.ts
  packages/vkui/src/storybook/VKUIDecorators.tsx
Labels: patch

#6536 patch(v5): pr6489
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx
  packages/vkui/src/lib/adaptivity/functions.ts
Labels: v5.10.1

#6539 ci(publish_release, publish_deploy): fix workflows issues
  .github/actions/publish-workflow-4-complete/action.yml
  .github/workflows/publish_deploy.yml
  .github/workflows/publish_prerelease.yml
Labels: type:bug, technical task

#6558 fix(docs): remove param from hook in useLoadThemeTokens
  styleguide/lib/theme/useLoadThemeTokens.js
Labels: patch

#6555 build(deps-dev): update more
  package.json
  packages/codemods/package.json
  packages/vkui/package.json
  styleguide/package.json
  yarn.lock
Labels: dependencies

#6540 fix(PullToRefresh): rm global touchmove listener
  packages/vkui/src/components/PullToRefresh/PullToRefresh.stories.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.test.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.tsx
  packages/vkui/src/styles/common.css
Labels: patch

#6559 ci(publish): refactor like `publish_prerelease`
  .github/actions/publish-workflow-4-complete/action.yml
  .github/workflows/publish.yml
  .github/workflows/publish_codemods.yml
  .github/workflows/publish_deploy.yml
  .github/workflows/publish_prerelease.yml
  .github/workflows/publish_token_translator.yml
  .github/workflows/publish_vkui_floating_ui_react_dom.yml
  packages/codemods/package.json
  packages/token-translator/package.json
  packages/vkui-floating-ui/package.json
Labels: technical task

#6563 feat(ChipsInput/ChipsSelect): reset state after `form.reset()`
  packages/vkui/src/components/ChipsInput/useChipsInput.ts
  packages/vkui/src/hooks/useNativeFormResetListener.test.tsx
  packages/vkui/src/hooks/useNativeFormResetListener.ts
Labels: type:feature, cmp:chips-select, cmp:chips-input

#6561 fix: rm useEnsuredControl
  packages/vkui/src/components/NativeSelect/NativeSelect.test.tsx
  packages/vkui/src/components/NativeSelect/NativeSelect.tsx
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Search/Search.tsx
  packages/vkui/src/components/Textarea/Textarea.test.tsx
  packages/vkui/src/components/Textarea/Textarea.tsx
  packages/vkui/src/components/WriteBar/WriteBar.test.tsx
  packages/vkui/src/components/WriteBar/WriteBar.tsx
Labels: patch

#6567 fix(ChipsSelect): Remove initialUpdate logic from floating Mutation observer callback
  packages/vkui/src/lib/floating/adapters.ts
Labels: patch

#6538 fix(ModalPage): Properly calculate content height in expanded mode
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: patch

#6578 build(deps): Downgrade codecov/codecov-action from 4 to 3
  .github/workflows/branch_test_coverage.yml
  .github/workflows/pull_request_packages_deploy.yml
Labels: type:bug, technical task, github_actions

#6577 fix(Group): inline padding use token
  packages/vkui/src/components/Group/Group.e2e-playground.tsx
  packages/vkui/src/components/Group/Group.module.css
  packages/vkui/src/components/Group/Group.tsx
  packages/vkui/src/components/Group/__image_snapshots__/group-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-android-chromium-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Group/__image_snapshots__/group-vkcom-webkit-light-1-snap.png
Labels: patch

#6585 patch(5.10-stable): pr6489G
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.test.tsx
  packages/vkui/src/components/AdaptivityProvider/AdaptivityProvider.tsx
  packages/vkui/src/lib/adaptivity/functions.ts
Labels: v5.10.1

#6572 fix(Popper): use CustomResizeObserver fallback for ResizeObserver in auto update on target resize
  packages/vkui/src/lib/floating/adapters.test.ts
  packages/vkui/src/lib/floating/adapters.ts
  packages/vkui/src/lib/floating/customResizeObserver.test.ts
  packages/vkui/src/lib/floating/customResizeObserver.ts
Labels: patch

#6631 fix(ChipsSelect): add disabled prop
  packages/vkui/src/components/ChipsInputBase/types.ts
  packages/vkui/src/components/ChipsSelect/ChipsSelect.stories.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/ChipsSelect/Readme.md
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.tsx
Labels: patch

#6639 patch(v5): pr6446
  packages/vkui/src/components/DateInput/DateInput.tsx
Labels: patch

#6637 fix(ModalPage): account for prev expandable value
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: patch

#6641 patch(v5): pr6637
  packages/vkui/src/components/ModalRoot/ModalRoot.tsx
Labels: patch

#6614 fix(ScrollContext): Fix scroll position after opening ActionSheet from ModalPage
  packages/vkui/src/components/AppRoot/AppRoot.test.tsx
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
Labels: patch

#6613 fix(PullToRefresh): Stretch PullToRefresh horizontally
  packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-webkit-light-1-snap.png
Labels: patch, v5.10.1

#6642 patch(v5): pr6614
  packages/vkui/src/components/AppRoot/AppRoot.test.tsx
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
Labels: patch

#6602 fix(PanelHeaderButton, TabsItem): fix hover effect
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.tsx
  packages/vkui/src/components/TabsItem/TabsItem.tsx
Labels: patch

#6644 patch(v5): pr6613
  packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx
  packages/vkui/src/components/PullToRefresh/PullToRefresh.module.css
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-takes-whole-parent-height-and-allow-smaller-content-to-center-vertically-vkcom-webkit-light-1-snap.png
Labels: patch

#6647 docs: Auto detect hasPointer on mobile
  styleguide/Components/Preview.js
Labels: patch
