Repository VKCOM/VKUI, pull requests merged in 2025-01, with the labels that each got.

#8136 fix(Alert): add FocusTrap props to Alert props
  packages/vkui/src/components/Alert/Alert.tsx
Labels: patch

#8123 fix: double disabled opacity
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-android-chromium-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ChipsInput/__image_snapshots__/chipsinput-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.module.css
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-android-chromium-light-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-ios-webkit-light-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ChipsSelect/__image_snapshots__/chipsselect-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/CustomSelect/CustomSelectInput/CustomSelectInput.module.css
  packages/vkui/src/components/Input/Input.module.css
  packages/vkui/src/components/Input/__image_snapshots__/input-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-android-chromium-light-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Input/__image_snapshots__/input-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Tabs/__image_snapshots__/tabs-android-chromium-light-1-snap.png
  packages/vkui/src/components/Textarea/Textarea.module.css
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-android-chromium-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Textarea/__image_snapshots__/textarea-vkcom-webkit-light-1-snap.png
Labels: patch, pr-needs-work

#8040 refactor(Tooltip, Popover): refactor Tooltip and Popover logic
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popover/Readme.md
  packages/vkui/src/components/Popover/usePopover.tsx
  packages/vkui/src/components/Tooltip/Readme.md
  packages/vkui/src/components/Tooltip/Tooltip.test.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/components/Tooltip/useTooltip.tsx
  packages/vkui/src/hooks/useFloatingElement.tsx
  packages/vkui/src/hooks/useReferenceElement.tsx
  packages/vkui/src/index.ts
Labels: cmp:tooltip, cmp:popover, pr-needs-work

#8131 feat(blog): add blog pages
  .github/workflows/deploy_docs_on_branch_push.yml
  .github/workflows/pull_request_packages_deploy.yml
  packages/vkui-docs-theme/index.ts
  packages/vkui-docs-theme/src/blog/PostsLayout.tsx
  packages/vkui-docs-theme/src/blog/components/Heading.tsx
  packages/vkui-docs-theme/src/blog/components/Post/Post.module.css
  packages/vkui-docs-theme/src/blog/components/Post/Post.tsx
  packages/vkui-docs-theme/src/blog/components/Post/PostHeading.tsx
  packages/vkui-docs-theme/src/blog/components/Post/PostMeta.tsx
  packages/vkui-docs-theme/src/blog/components/Post/index.ts
  packages/vkui-docs-theme/src/blog/components/PostHeader.tsx
  packages/vkui-docs-theme/src/blog/helpers.ts
  packages/vkui-docs-theme/src/blog/index.ts
  packages/vkui-docs-theme/src/blog/tags.tsx
  packages/vkui-docs-theme/src/components/Navbar/Navbar.module.css
  packages/vkui-docs-theme/src/contexts/config.tsx
  packages/vkui-docs-theme/src/helpers/date.ts
  packages/vkui-docs-theme/src/index.tsx
  packages/vkui-docs-theme/src/mdx/Callout/Callout.module.css
  packages/vkui-docs-theme/src/mdx/Code/Code.module.css
  packages/vkui-docs-theme/src/mdx/HeadingLink/HeadingLink.tsx
  packages/vkui-docs-theme/src/mdx/Main/Main.module.css
  packages/vkui-docs-theme/src/mdx/Main/Main.tsx
  packages/vkui-docs-theme/src/mdx/Pre/CopyToClipboard/CopyToClipboard.tsx
  packages/vkui-docs-theme/src/mdx/Pre/Pre.module.css
  packages/vkui-docs-theme/src/mdx/Pre/Pre.tsx
  packages/vkui-docs-theme/src/mdx/index.module.css
  packages/vkui-docs-theme/src/mdx/index.tsx
  packages/vkui-docs-theme/src/wrappers/content/index.module.css
  packages/vkui-docs-theme/src/wrappers/content/index.tsx
  packages/vkui-docs-theme/src/wrappers/index.ts
  packages/vkui-docs-theme/styles/constants.css
  website/pages/_meta.tsx
  website/pages/blog.mdx
  website/pages/blog/_meta.tsx
  website/pages/blog/tags/[tag].mdx
  website/pages/blog/testing-vkui-apps.mdx
  website/pages/blog/vkui-v7-release.mdx
  website/pages/index.mdx
  website/public/blog/v7-release.png
  website/public/blog/vkui-testing.png
Labels: no-stale

#8092 feat(SegmentedControl): fix rtl view
  packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e-playground.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControl.module.css
  packages/vkui/src/components/SegmentedControl/SegmentedControl.stories.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControl.test.tsx
  packages/vkui/src/components/SegmentedControl/SegmentedControl.tsx
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-android-chromium-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SegmentedControl/__image_snapshots__/segmentedcontrol-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Tabs/Tabs.tsx
  packages/vkui/src/hooks/useTabsNavigation.test.tsx
  packages/vkui/src/hooks/useTabsNavigation.ts
Labels: type:feature, cmp:segmented-control

#8129 feat(PanelHeaderBack): fix rtl view
  packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.e2e-playground.tsx
  packages/vkui/src/components/PanelHeaderButton/PanelHeaderButton.module.css
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-android-chromium-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-android-chromium-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-ios-webkit-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/PanelHeaderButton/__image_snapshots__/panelheaderback-vkcom-webkit-light-1-snap.png
Labels: type:feature, cmp:panel-header-button

#8144 fix(Header, SimpleCell): fix icons position with multiline
  packages/vkui/src/components/Header/Header.e2e-playground.tsx
  packages/vkui/src/components/Header/Header.module.css
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-android-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Header/__image_snapshots__/header-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/SimpleCell.e2e-playground.tsx
  packages/vkui/src/components/SimpleCell/SimpleCell.module.css
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-light-1-snap.png
Labels: patch

#8181 fix(Popper): remove strategy by default
  packages/vkui/src/components/Popper/Popper.tsx
Labels: cmp:popper

#8177 fix(HorizontalScroll): fix prevent page scrolling
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
Labels: patch

#8145 a11y: allow to pass axeConfig to baseline unit test
  packages/vkui/src/components/Accordion/Accordion.test.tsx
  packages/vkui/src/components/Alert/Alert.test.tsx
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/Alert/Readme.md
  packages/vkui/src/components/CardScroll/CardScroll.test.tsx
  packages/vkui/src/components/ChipsInput/ChipsInput.test.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/CustomSelect/CustomSelectInput/CustomSelectInput.test.tsx
  packages/vkui/src/components/CustomSelectOption/CustomSelectOption.test.tsx
  packages/vkui/src/components/DateInput/DateInput.test.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx
  packages/vkui/src/components/ModalCard/ModalCard.test.tsx
  packages/vkui/src/components/ModalCard/Readme.md
  packages/vkui/src/components/ModalCardBase/Readme.md
  packages/vkui/src/components/ModalPage/ModalPage.test.tsx
  packages/vkui/src/components/ModalPage/Readme.md
  packages/vkui/src/components/ModalRoot/ModalRoot.test.tsx
  packages/vkui/src/components/TabsItem/TabsItem.test.tsx
  packages/vkui/src/testing/utils.tsx
Labels: a11y, pr-needs-work

#8199 fix(RichCell): revert fix with after overflow
  packages/vkui/src/components/RichCell/RichCell.e2e-playground.tsx
  packages/vkui/src/components/RichCell/RichCell.module.css
  packages/vkui/src/components/RichCell/RichCell.stories.tsx
  packages/vkui/src/components/RichCell/RichCell.test.tsx
  packages/vkui/src/components/RichCell/RichCell.tsx
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-light-1-snap.png
Labels: patch

#8201 fix(ToolButton): rm alpha from bg for `mode="secondary"`
  packages/vkui/src/components/ToolButton/ToolButton.module.css
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/ToolButton/__image_snapshots__/toolbutton-vkcom-webkit-light-1-snap.png
Labels: patch

#8203 doc: Help styleguidist to detect proper name for Tabs page
  packages/vkui/src/components/Tabs/Tabs.tsx
Labels: docs

#8200 fix(modal): return adaptivity by AdaptivityProvider
  packages/vkui/src/components/ModalCard/ModalCard.module.css
  packages/vkui/src/components/ModalCard/ModalCardInternal.tsx
  packages/vkui/src/components/ModalOutlet/ModalOutlet.module.css
  packages/vkui/src/components/ModalOutlet/ModalOutlet.tsx
  packages/vkui/src/components/ModalPage/ModalPage.module.css
  packages/vkui/src/components/ModalPage/ModalPageInternal.tsx
  packages/vkui/src/components/ModalPageFooter/ModalPageFooter.module.css
  packages/vkui/src/components/ModalPageFooter/ModalPageFooter.tsx
Labels: patch

#8209 fix(ModalPage): expect number for height
  packages/vkui/src/components/ModalPage/ModalPageInternal.tsx
Labels: type:bug, cmp:modal-page, patch

#8213 fix: useScrollLockController rm useEffect
  packages/vkui/src/components/AppRoot/ScrollContext.test.tsx
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
Labels: type:bug, patch, cmp:app-root

#8215 fix(FormItem): Use spacing size tokens
  packages/vkui/src/components/FormItem/FormItem.module.css
Labels: patch
