Repository VKCOM/VKUI, pull requests merged in 2025-04, with the labels that each got.

#8427 fix(ImageBase): fix border `z-index`
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-android-chromium-light-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Avatar/__image_snapshots__/avatar-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-android-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-state-focus-visible-overlay-android-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Image/__image_snapshots__/image-vkcom-webkit-light-1-snap.png
  packages/vkui/src/styles/constants.css
Labels: ci:cherry-pick:patch

#8426 fix(CustomSelect): fix option props drilling
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: type:bug, cmp:custom-select, ci:cherry-pick:patch

#8450 fix(ChipsSelect,ChipsInput): fix remove option with number value
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.test.tsx
  packages/vkui/src/components/ChipsInputBase/ChipsInputBase.tsx
  packages/vkui/src/components/ChipsInputBase/helpers.ts
Labels: ci:cherry-pick:patch

#8433 Fix typo in role attribute in documentation
  packages/vkui/src/components/Alert/Readme.md
  packages/vkui/src/components/ModalCard/Readme.md
  packages/vkui/src/components/ModalCardBase/Readme.md
  packages/vkui/src/components/ModalPage/Readme.md
  packages/vkui/src/components/OnboardingTooltip/Readme.md
Labels: docs, ci:cherry-pick:patch

#8454 fix(ChipsSelect): fix closing dropdown when placement change
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
Labels: ci:cherry-pick:patch

#8448 fix(FormItem): Disable overflow in label with multiline prop
  packages/vkui/src/components/FormItem/FormItem.module.css
Labels: type:bug, cmp:form-item, ci:cherry-pick:patch

#8435 feat(ChipsInput,ChipsSelect): add prop delimiter
  packages/vkui/src/components/ChipsInput/ChipsInput.test.tsx
  packages/vkui/src/components/ChipsInput/ChipsInput.tsx
  packages/vkui/src/components/ChipsInput/useChipsInput.ts
  packages/vkui/src/components/ChipsInputBase/types.ts
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/components/ChipsSelect/useChipsSelect.ts
Labels: no-stale

#8474 fix(Tappable): fix wave positioning
  packages/vkui/src/components/Tappable/Tappable.module.css
Labels: cmp:tappable, ci:cherry-pick:patch

#8457 fix(Calendar): fix tab ordering when we use enableTime and doneButtonShow
  packages/vkui/src/components/CalendarTime/CalendarTime.test.tsx
  packages/vkui/src/components/CalendarTime/CalendarTime.tsx
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
  packages/vkui/src/components/CustomSelectDropdown/CustomSelectDropdown.tsx
Labels: ci:cherry-pick:patch

#8470 fix(DateInput): fix clear date by button
  packages/vkui/src/components/Calendar/Calendar.tsx
  packages/vkui/src/components/CalendarDays/CalendarDays.tsx
  packages/vkui/src/components/CalendarRange/CalendarRange.tsx
  packages/vkui/src/components/DateInput/DateInput.test.tsx
  packages/vkui/src/components/DateInput/DateInput.tsx
  packages/vkui/src/components/DateInput/hooks.test.ts
  packages/vkui/src/components/DateInput/hooks.ts
  packages/vkui/src/components/DateRangeInput/DateRangeInput.test.tsx
  packages/vkui/src/components/DateRangeInput/DateRangeInput.tsx
  packages/vkui/src/hooks/useCalendar.ts
  packages/vkui/src/hooks/useDateInput.ts
  packages/vkui/src/lib/date.ts
Labels: ci:cherry-pick:patch

#8481 fix(useModalRootContext): add activeModal
  packages/vkui/src/components/ModalRoot/Readme.md
  packages/vkui/src/components/ModalRoot/types.ts
  packages/vkui/src/components/ModalRoot/useModalRootContext.ts
Labels: ci:cherry-pick:patch

#8480 fix(Touch): is svg element
  packages/vkui/src/components/Touch/Touch.test.tsx
  packages/vkui/src/components/Touch/Touch.tsx
  packages/vkui/src/lib/dom.tsx
Labels: ci:cherry-pick:patch

#8504 fix(Progress): appearance token type
  packages/vkui/src/components/Progress/Progress.tsx
Labels: ci:cherry-pick:patch

#8503 fix(Link): not interactive
  packages/vkui/src/components/Link/Link.module.css
  packages/vkui/src/components/Link/Link.test.tsx
  packages/vkui/src/components/Link/Link.tsx
Labels: ci:cherry-pick:patch

#8526 fix(ScrollContext): fix scroll lock
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
Labels: ci:cherry-pick:patch

#8528 fix(DateInput): fix month names
  packages/vkui/src/lib/calendar.ts
Labels: ci:cherry-pick:patch
