Repository VKCOM/VKUI, pull requests merged in 2025-07, with the labels that each got.

#8669 chore: add new docs to CI
  .github/workflows/publish_deploy.yml
  website/next.config.mjs
Labels: docs, technical task

#8668 feat(storybook): improve search by query on overview page
  packages/vkui/docs/common/hooks/useGetConfigByQuery.ts
  packages/vkui/docs/components-overview/ComponentsOverview.tsx
  packages/vkui/docs/icons-overview/IconsOverview.tsx
Labels: type:feature, technical task

#8700 fix(Popover): fix hide popover when reference hidden
  packages/vkui/src/components/ImageBase/ImageBase.module.css
  packages/vkui/src/lib/floating/functions.test.ts
Labels: ci:cherry-pick:patch

#8735 fix(OnboardingTooltipContainer): revert tooltip container from context
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltipContainer.tsx
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltipContext.tsx
Labels: type:bug, ci:cherry-pick:patch, cmp:onboarding-tooltip

#8736 tech(examples): format templates to new doc
  examples/vkui-nextjs-ts/.gitignore
  examples/vkui-nextjs-ts/.yarn/install-state.gz
  examples/vkui-nextjs-ts/src/app/layout.tsx
  examples/vkui-nextjs-ts/src/client/Layout.tsx
  examples/vkui-nextjs-ts/src/client/pages/AboutPageContent.tsx
  examples/vkui-nextjs-ts/src/client/pages/HomePageContent.tsx
  examples/vkui-vite-ts/.gitignore
  examples/vkui-vite-ts/.yarn/install-state.gz
  examples/vkui-vite-ts/index.html
  examples/vkui-vite-ts/src/App.tsx
  examples/vkui-vite-ts/src/main.tsx
  website/content/overview/install.mdx
  website/content/overview/ssr.mdx
Labels: docs

#8705 test(postcss-restructure-variable): use node test
  tools/postcss-restructure-variable/package.json
  tools/postcss-restructure-variable/postcss-restructure-variable.test.js
  tools/postcss-restructure-variable/postcss-restructure-variable.test.js.snapshot
Labels: pr-needs-work

#8749 fix(Clickable): rm RealClickable
  packages/vkui/src/components/Clickable/Clickable.test.tsx
  packages/vkui/src/components/Clickable/Clickable.tsx
  packages/vkui/src/components/Clickable/RealClickable.tsx
  packages/vkui/src/components/ModalPage/ModalPageBase.tsx
Labels: ci:cherry-pick:patch

#8759 feat(floating): add disableShiftMiddleware prop
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx
  packages/vkui/src/components/Popover/Popover.tsx
  packages/vkui/src/components/Popover/usePopover.tsx
  packages/vkui/src/components/Popper/Popper.tsx
  packages/vkui/src/components/Tooltip/Tooltip.tsx
  packages/vkui/src/components/Tooltip/useTooltip.tsx
  packages/vkui/src/hooks/useFloatingElement.tsx
  packages/vkui/src/lib/floating/useFloatingMiddlewaresBootstrap/index.ts
Labels: pr-needs-work

#8807 fix(codemods): fix removeProps utility
  packages/codemods/src/codemod-helpers.ts
  packages/codemods/src/transforms/v7/__testfixtures__/chips-select/basic.input.tsx
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/action-sheet.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/alert.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/appearance-provider.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/appearance.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/banner.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/calendar.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/card-grid.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/card-scroll.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/cell-button.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/cell.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/chips-select.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/config-provider.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/content-card.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/counter.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/custom-scroll-view.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/custom-select.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/flex.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/form-item.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/form-status.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/header.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/horizontal-cell-show-more.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/horizontal-cell.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/horizontal-scroll.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/image-overlay.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/mini-info-cell.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/modal-card.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/onboarding-tooltip.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-back.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-close.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-content.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-edit.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-header-submit.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/panel-spinner.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/placeholder.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/rich-cell.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/screen-spinner.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/scroll-arrow.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/select.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/separator.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/simple-cell.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/simple-grid.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/spacing.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/spinner.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/subnavigation-bar.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/subnavigation-button.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/tabbar-item.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/tooltip.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/typography.ts.snap
  packages/codemods/src/transforms/v7/__tests__/__snapshots__/users-stack.ts.snap
Labels: subpackage:@vkontakte/vkui-codemods
