Repository VKCOM/VKUI, pull requests merged in 2025-05, with the labels that each got.

#8540 ci: use local path for repo actions
  .github/workflows/branch_test_coverage.yml
  .github/workflows/dedupe_deps.yml
  .github/workflows/deploy_docs_on_branch_push.yml
  .github/workflows/monday.yml
  .github/workflows/pr_close.yml
  .github/workflows/pr_close_undeploy.yml
  .github/workflows/publish.yml
  .github/workflows/publish_deploy.yml
  .github/workflows/publish_prerelease.yml
  .github/workflows/pull_request_common.yml
  .github/workflows/pull_request_packages.yml
  .github/workflows/pull_request_packages_deploy.yml
  .github/workflows/reusable_workflow_test.yml
  .github/workflows/reusable_workflow_test_e2e.yml
  .github/workflows/update_screens.yml
Labels: technical task

#8516 docs(MAINTAINERS): add info about major changes
  docs/MAINTAINERS.md
  styleguide/pages/migration_v7.md
Labels: docs, pr-needs-work

#8537 fix(Search): fix renderIconButton typing
  packages/vkui/src/components/Search/Search.test.tsx
  packages/vkui/src/components/Search/Search.tsx
Labels: type:bug, cmp:search, ci:cherry-pick:patch

#8539 fix(WriteBar): fix long placeholder text view
  packages/vkui/src/components/WriteBar/WriteBar.e2e-playground.tsx
  packages/vkui/src/components/WriteBar/WriteBar.module.css
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-android-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-ios-webkit-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/WriteBar/__image_snapshots__/writebar-vkcom-webkit-light-1-snap.png
Labels: ci:cherry-pick:patch

#8550 fix(FormLayoutGroup): add disabled to removable
  packages/vkui/src/components/FormLayoutGroup/FormLayoutGroup.tsx
Labels: ci:cherry-pick:patch

#8553 chore(playwright-ct.config.mjs): resolve TODO
  packages/vkui/playwright-ct.config.mjs
Labels: technical task

#8555 fix(FormItem): add disabled to removable
  packages/vkui/src/components/FormItem/FormItem.tsx
Labels: ci:cherry-pick:patch

#8560 fix(Touch): handle touchstart events by DOM API
  packages/vkui/src/components/Touch/Touch.tsx
Labels: type:bug, cmp:cell, cmp:touch, ci:cherry-pick:patch

#8484 feat(Tabs): Add controlled mode with context
  packages/vkui/src/components/Tabs/Readme.md
  packages/vkui/src/components/Tabs/Tabs.e2e-playground.tsx
  packages/vkui/src/components/Tabs/Tabs.stories.tsx
  packages/vkui/src/components/Tabs/Tabs.test.tsx
  packages/vkui/src/components/Tabs/Tabs.tsx
  packages/vkui/src/components/Tabs/TabsController.ts
  packages/vkui/src/components/Tabs/TabsModeContext.ts
  packages/vkui/src/components/TabsItem/TabsItem.tsx
Labels: type:feature, cmp:tabs, cmp:tabs-item

#8562 fix(Gallery): fix arrow label
  packages/vkui/src/components/CarouselBase/CarouselBase.tsx
  packages/vkui/src/components/CarouselBase/ScrollArrows.tsx
  packages/vkui/src/components/Gallery/Gallery.test.tsx
Labels: ci:cherry-pick:patch

#8565 fix(ContentBadge): IconSlot
  packages/vkui/src/components/ContentBadge/ContentBadge.e2e-playground.tsx
  packages/vkui/src/components/ContentBadge/ContentBadge.stories.tsx
  packages/vkui/src/components/ContentBadge/ContentBadge.test.tsx
  packages/vkui/src/components/ContentBadge/ContentBadge.tsx
  packages/vkui/src/components/ContentBadge/ContentBadgeIconSlot.tsx
  packages/vkui/src/components/ContentBadge/Readme.md
Labels: ci:cherry-pick:patch

#8563 docs(Gallery): slideWidth description
  packages/vkui/src/components/CarouselBase/types.ts
Labels: cmp:gallery, ci:cherry-pick:patch

#8568 fix(Spinner): icons add className
  packages/vkui/src/components/Spinner/icons.tsx
Labels: ci:cherry-pick:patch

#8567 fix(ChipsSelect): fix onChange with custom fields
  packages/vkui/src/components/ChipsInput/useChipsInput.ts
  packages/vkui/src/components/ChipsSelect/ChipsSelect.test.tsx
Labels: type:bug, cmp:chips-select, cmp:chips-input, ci:cherry-pick:patch

#8569 docs(HorizontalCell): rm unexist `mode` from `Avatar`
  packages/vkui/src/components/HorizontalCell/Readme.md
Labels: docs, cmp:horizontal-cell, ci:cherry-pick:patch

#8570 docs(Tappable): mv `activated` to `active`
  packages/vkui/src/components/Clickable/useState.tsx
Labels: docs, cmp:tappable, ci:cherry-pick:patch

#8582 fix(ChipsSelect): fix close dropdown with `closeAfterSelect`
  packages/vkui/src/components/ChipsSelect/ChipsSelect.tsx
  packages/vkui/src/hooks/useGlobalOnClickOutside.test.tsx
  packages/vkui/src/hooks/useGlobalOnClickOutside.ts
Labels: type:bug, cmp:chips-select, ci:cherry-pick:patch

#8581 fix: add @vkontakte/vkui-date-fns-tz
  .github/workflows/deprecate.yml
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
  .prettierignore
  package.json
  packages/vkui-date-fns-tz/.eslintrc.json
  packages/vkui-date-fns-tz/.gitignore
  packages/vkui-date-fns-tz/LICENSE
  packages/vkui-date-fns-tz/README.md
  packages/vkui-date-fns-tz/build.ts
  packages/vkui-date-fns-tz/import.test.ts
  packages/vkui-date-fns-tz/package.json
  packages/vkui-date-fns-tz/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: ci:cherry-pick:patch

#8590 fix(CustomSelect): fix readonly mode
  packages/vkui/src/components/CustomSelect/CustomSelect.tsx
Labels: ci:cherry-pick:patch

#8591 fix(vkui-date-fns-tz): cjs
  packages/vkui-date-fns-tz/.gitignore
  packages/vkui-date-fns-tz/build.ts
  packages/vkui-date-fns-tz/package.json
Labels: ci:cherry-pick:patch

#8592 fix(vkui-date-fns-tz): add index.cjs files
  packages/vkui-date-fns-tz/package.json
Labels: ci:cherry-pick:patch

#8588 fix: use vkui-date-fns-tz
  packages/vkui-date-fns-tz/package.json
  packages/vkui/jest.config.ts
  packages/vkui/package.json
  packages/vkui/src/lib/date.ts
  yarn.lock
Labels: ci:cherry-pick:patch

#8402 tech: add `vkui-vite-ts` example
  .eslintrc.json
  examples/vkui-vite-ts/.eslintrc.json
  examples/vkui-vite-ts/.gitignore
  examples/vkui-vite-ts/.yarnrc.yml
  examples/vkui-vite-ts/README.md
  examples/vkui-vite-ts/index.html
  examples/vkui-vite-ts/package.json
  examples/vkui-vite-ts/public/vite.svg
  examples/vkui-vite-ts/src/App.module.css
  examples/vkui-vite-ts/src/App.tsx
  examples/vkui-vite-ts/src/ColorSchemeSwitcher.tsx
  examples/vkui-vite-ts/src/main.tsx
  examples/vkui-vite-ts/src/vite-env.d.ts
  examples/vkui-vite-ts/tsconfig.json
  examples/vkui-vite-ts/tsconfig.node.json
  examples/vkui-vite-ts/vite.config.ts
  examples/vkui-vite-ts/yarn.lock
  tsconfig.json
Labels: technical task, no-stale

#8610 fix(docs): url storybook to its own version
  styleguide/Components/ReactComponent/ReactComponent.js
  styleguide/Components/StyleGuide/StyleGuideHeader.js
Labels: ci:cherry-pick:patch

#8616 fix(Clickable): ignore undefined Component
  packages/vkui/src/components/Clickable/Clickable.tsx
  packages/vkui/src/components/Tappable/Tappable.test.tsx
Labels: ci:cherry-pick:patch

#8618 fix(Flex): fix nested Flex gap reset
  packages/vkui/src/components/Flex/Flex.test.tsx
  packages/vkui/src/lib/layouts/gaps.ts
Labels: type:bug, ci:cherry-pick:patch, cmp:flex
