Repository VKCOM/VKUI, pull requests merged in 2025-02, with the labels that each got.

#8212 tech(Flex): add support flex with gap
  packages/vkui/src/components/Flex/Flex.module.css
  packages/vkui/src/components/Flex/Flex.stories.tsx
  packages/vkui/src/components/Flex/Flex.tsx
  packages/vkui/src/components/Flex/Readme.md
Labels: technical task, cmp:flex

#8231 tech(Storybook): add `@storybook/addon-console` to storybook
  package.json
  packages/vkui/.storybook/preview.ts
  yarn.lock
Labels: technical task

#8232 fix: FormItem noPadding with removable
  packages/vkui/src/components/FormItem/FormItem.e2e-playground.tsx
  packages/vkui/src/components/FormItem/FormItem.tsx
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-android-chromium-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-android-chromium-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-ios-webkit-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/FormItem/__image_snapshots__/formitem-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/Removable/Removable.module.css
  packages/vkui/src/components/Removable/Removable.tsx
Labels: patch

#8237 fix(Pagination):Update a11y labels
  packages/vkui/src/components/Pagination/Pagination.tsx
  packages/vkui/src/components/Pagination/PaginationPage/PaginationPageButton.tsx
  packages/vkui/src/components/Pagination/Readme.md
  packages/vkui/src/components/Pagination/utils.ts
Labels: patch

#8243 feat(SubnavigationButton): add disabled styles
  packages/vkui/src/components/SubnavigationButton/Readme.md
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.e2e-playground.tsx
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.module.css
  packages/vkui/src/components/SubnavigationButton/SubnavigationButton.tsx
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-android-chromium-light-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SubnavigationButton/__image_snapshots__/subnavigationbutton-vkcom-webkit-light-1-snap.png
Labels: cmp:subnavigation-button

#8245 fix(Storybook): fix double scroll in controls panel
  packages/vkui/.storybook/addons/source-tab/SourceTab.tsx
  packages/vkui/.storybook/addons/source-tab/register.tsx
Labels: technical task, patch

#8241 fix(TabbarItem): avoid double focus
  packages/vkui/src/components/TabbarItem/TabbarItem.test.tsx
  packages/vkui/src/components/TabbarItem/TabbarItem.tsx
Labels: patch

#8249 tech: add storybook addon story source-button
  packages/vkui/.storybook/addons/source-button/SourceButton.tsx
  packages/vkui/.storybook/addons/source-button/constants.ts
  packages/vkui/.storybook/addons/source-button/register.ts
  packages/vkui/.storybook/main.ts
Labels: technical task

#8085 feat(Gallery): add rtl support
  packages/vkui/src/components/CarouselBase/CarouselBase.module.css
  packages/vkui/src/components/CarouselBase/CarouselBase.tsx
  packages/vkui/src/components/CarouselBase/helpers.test.ts
  packages/vkui/src/components/CarouselBase/helpers.ts
  packages/vkui/src/components/Gallery/Gallery.e2e-playground.tsx
  packages/vkui/src/components/Gallery/Gallery.stories.tsx
  packages/vkui/src/components/Gallery/Gallery.test.tsx
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-android-chromium-light-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Gallery/__image_snapshots__/gallery-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/ScrollArrow/ScrollArrow.module.css
  packages/vkui/src/components/ScrollArrow/ScrollArrow.tsx
Labels: type:feature, cmp:gallery

#8248 fix(ModalPage, ModalCard): add prop `disableFocusTrap ` to fix conflict with several FocusTraps
  packages/vkui/src/components/ModalCard/ModalCard.test.tsx
  packages/vkui/src/components/ModalCard/ModalCardInternal.tsx
  packages/vkui/src/components/ModalCard/Readme.md
  packages/vkui/src/components/ModalCard/types.ts
  packages/vkui/src/components/ModalPage/ModalPage.test.tsx
  packages/vkui/src/components/ModalPage/ModalPageInternal.tsx
  packages/vkui/src/components/ModalPage/Readme.md
  packages/vkui/src/components/ModalPage/types.ts
  packages/vkui/src/hooks/useFocusTrap.ts
Labels: patch

#8247 fix(OnboardingTooltip): a11y
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.module.css
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.test.tsx
  packages/vkui/src/components/OnboardingTooltip/OnboardingTooltip.tsx
  packages/vkui/src/components/OnboardingTooltip/Readme.md
  packages/vkui/src/components/TooltipBase/TooltipBase.tsx
Labels: patch

#8137 feat(ScrollLock): export `useScroll` to scroll locked layout
  packages/vkui/src/components/AppRoot/ScrollContext.test.tsx
  packages/vkui/src/components/AppRoot/ScrollContext.tsx
  packages/vkui/src/index.ts
Labels: type:feature

#8246 e2e: add screenshot state custom height
  packages/vkui/src/components/Cell/Cell.e2e-playground.tsx
  packages/vkui/src/components/Cell/__image_snapshots__/cell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-android-chromium-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/Cell/__image_snapshots__/cell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/CellButton/CellButton.e2e-playground.tsx
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-android-chromium-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-android-chromium-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-ios-webkit-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/CellButton/__image_snapshots__/cellbutton-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/MiniInfoCell.e2e-playground.tsx
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-android-chromium-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/MiniInfoCell/__image_snapshots__/miniinfocell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/RichCell/RichCell.e2e-playground.tsx
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-android-chromium-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/RichCell/__image_snapshots__/richcell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/SimpleCell.e2e-playground.tsx
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-android-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-ios-webkit-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-chromium-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-firefox-light-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-dark-1-snap.png
  packages/vkui/src/components/SimpleCell/__image_snapshots__/simplecell-vkcom-webkit-light-1-snap.png
  packages/vkui/src/testing/e2e/ComponentPlayground.tsx
  packages/vkui/src/testing/e2e/utils.tsx
Labels: technical task

#8266 fix(Alert): Move dismiss button before actions to focus on it first
  packages/vkui/src/components/Alert/Alert.stories.tsx
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/Alert/Readme.md
  packages/vkui/src/types.ts
Labels: patch

#8292 fix(Gallery): remove add slide change animation to queue at not looped
  packages/vkui/src/components/CarouselBase/CarouselBase.tsx
Labels: type:bug, cmp:gallery, patch

#8259 tech(storybook): add storybook addon documentation link button
  packages/vkui/.storybook/addons/documentation-button/DocumentationButton.tsx
  packages/vkui/.storybook/addons/documentation-button/constants.ts
  packages/vkui/.storybook/addons/documentation-button/register.ts
  packages/vkui/.storybook/addons/source-button/SourceButton.tsx
  packages/vkui/.storybook/addons/source-button/constants.ts
  packages/vkui/.storybook/helpers/index.ts
  packages/vkui/.storybook/main.ts
  packages/vkui/.storybook/preview.ts
Labels: technical task

#8293 fix(HorizontalScroll): remove wheels event from container
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.test.tsx
  packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
Labels: type:bug, cmp:horizontal-scroll, patch

#8297 fix(Textarea): fix scroll when disabled
  packages/vkui/src/components/Textarea/Textarea.module.css
Labels: type:bug, cmp:textarea, patch

#8298 feat(Alert): add testid for title and description
  packages/vkui/src/components/Alert/Alert.test.tsx
  packages/vkui/src/components/Alert/Alert.tsx
  packages/vkui/src/components/Alert/AlertTypography.tsx
Labels: cmp:alert

#8295 fix: fix reload story
  packages/vkui/.storybook/addons/documentation-button/DocumentationButton.tsx
  packages/vkui/.storybook/addons/source-button/SourceButton.tsx
Labels: technical task
